/* eslint-disable */
// This file is generated by openapi-typescript.
// Run: npm run generate:sdk
export interface paths {
  "/auth/login": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            email: string;
            password: string;
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              token: string;
              user: components["schemas"]["User"];
            };
          };
        };
        401: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/me": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
        401: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/transactions": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["Transaction"][];
          };
        };
        401: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    User: {
      id: string;
      email: string;
      name: string;
      createdAt?: string;
    };
    Transaction: {
      id: string;
      userId: string;
      amount: number;
      currency: string;
      category: string;
      description?: string;
      occurredAt: string;
    };
    ErrorResponse: {
      code: string;
      message: string;
      details?: Record<string, unknown>;
    };
  };
}
