const de = {
  "+{{amount}} above plan 🚀": "+{{amount}} über dem Plan 🚀",
  "30 days": "30 Tage",
  "A subcategory cannot contain nested subcategories.": "Eine Unterkategorie kann keine verschachtelten Unterkategorien enthalten.",
  "Access denied.": "Zugriff verweigert.",
  "Access until: {{date}}": "Zugriff bis: {{date}}",
  "Account": "Konto",
  "Account settings": "Kontoeinstellungen",
  "Account unavailable.": "Konto nicht verfügbar.",
  "Account: {{name}}": "Konto: {{name}}",
  "Accounts": "Konten",
  "Across all accounts": "Über alle Konten",
  "Actual": "Tatsächlich",
  "Actual expense": "Tatsächliche Ausgabe",
  "Actual income": "Tatsächliche Einnahmen",
  "Add": "Hinzufügen",
  "Add account": "Konto hinzufügen",
  "Add budget": "Budget hinzufügen",
  "Add category": "Kategorie hinzufügen",
  "Add details": "Details hinzufügen",
  "Add subcategory": "Unterkategorie hinzufügen",
  "Add to budget": "Zum Budget hinzufügen",
  "Add transaction": "Transaktion hinzufügen",
  "Add your first expense": "Fügen Sie Ihre erste Ausgabe hinzu",
  "Adding...": "Hinzufügen...",
  "All accounts": "Alle Konten",
  "All categories": "Alle Kategorien",
  "All recorded income categories": "Alle erfassten Einnahmekategorien",
  "All steps completed": "Alle Schritte abgeschlossen",
  "All time": "Alle Zeiten",
  "All types": "Alle Arten",
  "Amount": "Betrag",
  "Analytics period": "Analysezeitraum",
  "Another store purchase is already in progress.": "Ein weiterer Ladenkauf ist bereits im Gange.",
  "Apple did not return an identity token.": "Apple hat kein Identitätstoken zurückgegeben.",
  "App Store saved {{actualProductId}} instead of {{requestedProductId}}. Check the current plan in App Store subscription settings.": "App Store hat {{actualProductId}} anstelle von {{requestedProductId}} gespeichert. Überprüfen Sie den aktuellen Plan in den Abonnementeinstellungen des App Store.",
  "Auto-renew off": "Automatische Verlängerung deaktiviert",
  "Auto-renewal is off. Premium access remains available through the date above.": "Die automatische Verlängerung ist deaktiviert. Der Premium-Zugang bleibt bis zum oben genannten Datum verfügbar.",
  "Available plans": "Verfügbare Pläne",
  "Back": "Zurück",
  "Back to sign in": "Zurück zur Anmeldung",
  "Balance": "Saldo",
  "Balance update timed out. Check that the backend API is available.": "Zeitüberschreitung bei der Aktualisierung des Kontostands. Überprüfen Sie, ob die Backend-API verfügbar ist.",
  "Base currency": "Basiswährung",
  "Budget": "Budget",
  "Budget category": "Budgetkategorie",
  "Budget changes and category editing will be added after the backend API is extended.": "Budgetänderungen und Kategoriebearbeitung werden hinzugefügt, nachdem die Backend-API erweitert wurde.",
  "Budget details": "Budgetdetails",
  "Budget not found.": "Budget nicht gefunden.",
  "Budget progress": "Budgetfortschritt",
  "Budgets": "Budgets",
  "C": "C",
  "Cancel": "Abbrechen",
  "Categories": "Kategorien",
  "Category": "Kategorie",
  "Category disabled": "Kategorie deaktiviert",
  "Category enabled": "Kategorie aktiviert",
  "Category not found in the budget.": "Kategorie wurde im Budget nicht gefunden.",
  "Category unavailable.": "Kategorie nicht verfügbar.",
  "Category \"{{name}}\" will become a group. It can no longer be selected in new transactions and budgets. Existing records will remain unchanged.": "Die Kategorie „{{name}}“ wird zu einer Gruppe. Sie kann nicht mehr für neue Transaktionen und Budgets ausgewählt werden. Vorhandene Datensätze bleiben unverändert.",
  "Category will become a group": "Aus der Kategorie wird eine Gruppe",
  "Change balance": "Saldo ändern",
  "Change password": "Passwort ändern",
  "Check your email": "Überprüfen Sie Ihre E-Mails",
  "Checking authentication...": "Authentifizierung wird überprüft...",
  "Choose an App Store or Google Play product below.": "Wählen Sie unten ein App Store- oder Google Play-Produkt aus.",
  "Comment": "Kommentar",
  "Complete all password fields.": "Füllen Sie alle Passwortfelder aus.",
  "Confirm new password": "Neues Passwort bestätigen",
  "Confirm password": "Passwort bestätigen",
  "Contact support": "Support kontaktieren",
  "Continue": "Weiter",
  "Create": "Erstellen",
  "Create account": "Benutzerkonto erstellen",
  "Creating...": "Erstellen...",
  "Currency": "Währung",
  "Current password": "Aktuelles Passwort",
  "Current plan": "Aktueller Plan",
  "Custom": "Benutzerdefiniert",
  "DONE": "ERLEDIGT",
  "Dashboard": "Übersicht",
  "Date": "Datum",
  "Date YYYY-MM-DD": "Datum JJJJ-MM-TT",
  "Delete": "Löschen",
  "Delete account?": "Konto löschen?",
  "Delete category": "Kategorie löschen",
  "Delete category?": "Kategorie löschen?",
  "Delete transaction": "Transaktion löschen",
  "Delete transaction?": "Transaktion löschen?",
  "Deleting...": "Löschen...",
  "Description": "Beschreibung",
  "Disabled": "Deaktiviert",
  "Edit": "Bearbeiten",
  "Edit account": "Konto bearbeiten",
  "Edit transaction": "Transaktion bearbeiten",
  "Editing": "Bearbeitung",
  "Email": "E-Mail",
  "Email resent. Retry in {{seconds}} seconds.": "E-Mail erneut gesendet. Versuchen Sie es in {{seconds}} Sekunden erneut.",
  "Email sent. You can retry in about {{seconds}} seconds.": "E-Mail gesendet. Sie können es in etwa {{seconds}} Sekunden erneut versuchen.",
  "Email verification": "E-Mail-Bestätigung",
  "Email verified. You can now sign in.": "E-Mail bestätigt. Sie können sich jetzt anmelden.",
  "Email was not sent. Try again in {{seconds}} seconds.": "E-Mail wurde nicht gesendet. Versuchen Sie es in {{seconds}} Sekunden erneut.",
  "End date": "Enddatum",
  "Enter a category name.": "Geben Sie einen Kategorienamen ein.",
  "Enter a date.": "Geben Sie ein Datum ein.",
  "Enter a message.": "Geben Sie eine Nachricht ein.",
  "Enter a new password.": "Geben Sie ein neues Passwort ein.",
  "Enter a subject.": "Geben Sie einen Betreff ein.",
  "Enter a valid amount.": "Geben Sie einen gültigen Betrag ein.",
  "Enter a valid balance.": "Geben Sie einen gültigen Saldo ein.",
  "Enter a valid email address.": "Geben Sie eine gültige E-Mail-Adresse ein.",
  "Enter a valid planned amount greater than 0.": "Geben Sie einen gültigen Planbetrag ein, der größer als 0 ist.",
  "Enter an account name.": "Geben Sie einen Kontonamen ein.",
  "Enter an amount greater than zero.": "Geben Sie einen Betrag größer als Null ein.",
  "Enter your email": "Geben Sie Ihre E-Mail-Adresse ein",
  "Enter your email, name, and password.": "Geben Sie Ihre E-Mail-Adresse, Ihren Namen und Ihr Passwort ein.",
  "Enter your email.": "Geben Sie Ihre E-Mail-Adresse ein.",
  "Enter your name": "Geben Sie Ihren Namen ein",
  "Expense": "Ausgabe",
  "Expense categories": "Ausgabenkategorien",
  "Expense categories are not available yet.": "Ausgabenkategorien sind noch nicht verfügbar.",
  "Expense not submitted: complete the required fields.": "Ausgabe nicht gespeichert: Füllen Sie die Pflichtfelder aus.",
  "Expenses": "Ausgaben",
  "Expenses and income": "Ausgaben und Einnahmen",
  "Expenses this period": "Ausgaben in diesem Zeitraum",
  "Fill password": "Passwort eingeben",
  "Forgot password?": "Passwort vergessen?",
  "Free": "Kostenlos",
  "From {{date}}": "Von {{date}}",
  "Go to sign in": "Gehen Sie zur Anmeldung",
  "Goal reached! 🎉": "Ziel erreicht! 🎉",
  "Google Sign-In is not configured for this build.": "Google Sign-In ist für diesen Build nicht konfiguriert.",
  "Google did not return an ID token.": "Google hat kein ID-Token zurückgegeben.",
  "Group": "Gruppe",
  "Hide": "Verstecken",
  "Hide form": "Formular ausblenden",
  "Hide password": "Passwort verbergen",
  "Home": "Startseite",
  "I have a token": "Ich habe einen Token",
  "Icon": "Symbol",
  "If the account exists, an email has been sent.": "Wenn das Konto vorhanden ist, wurde eine E-Mail gesendet.",
  "If the account exists, an email has been sent. Retry in {{seconds}} seconds.": "Wenn das Konto vorhanden ist, wurde eine E-Mail gesendet. Versuchen Sie es in {{seconds}} Sekunden erneut.",
  "If the email contains a production link, paste the token manually for local testing.": "Wenn die E-Mail einen Produktionslink enthält, fügen Sie das Token zum lokalen Testen manuell ein.",
  "Income": "Einnahmen",
  "Income categories": "Einnahmekategorien",
  "Income categories are not available yet.": "Einnahmekategorien sind noch nicht verfügbar.",
  "Income this period": "Einnahmen in diesem Zeitraum",
  "Initial setup": "Ersteinrichtung",
  "Interface language": "Sprache der Benutzeroberfläche",
  "Invalid accounts response format.": "Ungültiges Kontoantwortformat.",
  "Invalid budget response format.": "Ungültiges Budget-Antwortformat.",
  "Keep an eye on all of your balances.": "Behalten Sie alle Ihre Guthaben im Blick.",
  "Language and base currency": "Sprache und Basiswährung",
  "LiqPay subscription can be cancelled only in the web version of the app.": "Das LiqPay-Abonnement kann nur in der Webversion der App gekündigt werden.",
  "Loading accounts...": "Konten werden geladen...",
  "Loading budget...": "Budget wird geladen...",
  "Loading budgets...": "Budgets werden geladen...",
  "Loading categories...": "Kategorien werden geladen...",
  "Loading dashboard...": "Dashboard wird geladen...",
  "Loading icons...": "Symbole werden geladen...",
  "Loading onboarding...": "Onboarding wird geladen...",
  "Loading settings...": "Einstellungen werden geladen...",
  "Loading store products...": "Shop-Produkte werden geladen...",
  "Loading subscription status...": "Abonnementstatus wird geladen...",
  "Loading...": "Laden...",
  "Log in": "Anmelden",
  "Login with Google": "Mit Google anmelden",
  "Logout": "Abmelden",
  "Manage on web": "Im Web verwalten",
  "Manage premium access": "Premium-Zugang verwalten",
  "Manage subscription": "Abonnement verwalten",
  "Maximum category depth is 2 levels": "Die maximale Kategorietiefe beträgt 2 Ebenen",
  "Maximum category depth is 2 levels.": "Die maximale Kategorietiefe beträgt 2 Ebenen.",
  "Message": "Nachricht",
  "Missing Android subscription offer token for selected product.": "Für das ausgewählte Produkt fehlt das Token für das Android-Abonnementangebot.",
  "Missing account ID.": "Fehlende Konto-ID.",
  "Missing budgetId.": "Fehlende Budget-ID.",
  "Missing reset token.": "Fehlendes Reset-Token.",
  "MoneyDrive.me": "MoneyDrive.me",
  "Month": "Monat",
  "More": "Mehr",
  "More service sections": "Weitere Servicebereiche",
  "Most frequent": "Am häufigsten",
  "Name": "Name",
  "New account": "Neues Konto",
  "New balance": "Neuer Saldo",
  "New category": "Neue Kategorie",
  "New email awaiting verification: {{email}}": "Neue E-Mail wartet auf Bestätigung: {{email}}",
  "New password": "Neues Passwort",
  "New planned amount": "Neuer geplanter Betrag",
  "No App Store Sandbox account is connected on this device. Add a sandbox tester in Settings > App Store > Sandbox Account.": "Auf diesem Gerät ist kein App Store Sandbox-Konto verbunden. Fügen Sie unter Einstellungen > App Store > Sandbox-Konto einen Sandbox-Tester hinzu.",
  "No account": "Kein Konto",
  "No account data.": "Keine Kontodaten.",
  "No accounts.": "Keine Konten.",
  "No active purchases found.": "Keine aktiven Käufe gefunden.",
  "No active store source": "Keine aktive Store-Quelle",
  "No budget has been created for the selected month.": "Für den ausgewählten Monat wurde kein Budget erstellt.",
  "No budgets for the selected period.": "Keine Budgets für den ausgewählten Zeitraum.",
  "No budgets found yet.": "Noch keine Budgets gefunden.",
  "No categories available to add.": "Es sind keine Kategorien zum Hinzufügen verfügbar.",
  "No categories found for the selected type.": "Für den ausgewählten Typ wurden keine Kategorien gefunden.",
  "No categories found.": "Keine Kategorien gefunden.",
  "No categories.": "Keine Kategorien.",
  "No data for the selected period.": "Keine Daten für den ausgewählten Zeitraum.",
  "No data.": "Keine Daten.",
  "No external management action is available.": "Es ist keine externe Verwaltungsaktion verfügbar.",
  "No period selected": "Kein Zeitraum ausgewählt",
  "No transaction data.": "Keine Transaktionsdaten.",
  "No transactions yet.": "Noch keine Transaktionen.",
  "Not enough data to add the category.": "Nicht genügend Daten zum Hinzufügen der Kategorie.",
  "Not set": "Nicht festgelegt",
  "Note": "Notiz",
  "Open": "Öffnen",
  "Open App Store account settings and choose Subscriptions.": "Öffnen Sie die Kontoeinstellungen im App Store und wählen Sie Abonnements.",
  "Open the subscription provider account settings to manage this plan.": "Öffnen Sie die Kontoeinstellungen des Abonnementanbieters, um diesen Plan zu verwalten.",
  "Overspent by {{amount}}": "Zu viel ausgegeben um {{amount}}",
  "Parent: {{name}}": "Übergeordnetes Element: {{name}}",
  "Password": "Passwort",
  "Password changed.": "Passwort geändert.",
  "Password recovery": "Passwortwiederherstellung",
  "Password updated. You can now sign in.": "Passwort aktualisiert. Sie können sich jetzt anmelden.",
  "Passwords do not match.": "Passwörter stimmen nicht überein.",
  "Paste the verification token.": "Fügen Sie das Bestätigungstoken ein.",
  "Period: {{period}}": "Zeitraum: {{period}}",
  "Plan ({{currency}})": "Plan ({{currency}})",
  "Plan / actual / remaining by category": "Plan / Ist / Rest nach Kategorie",
  "Plan {{plan}} · Actual {{actual}}": "Plan {{plan}} · Istwert {{actual}}",
  "Plans and billing": "Pläne und Abrechnung",
  "Planned amount ({{currency}})": "Geplanter Betrag ({{currency}})",
  "Planned expense": "Geplante Ausgabe",
  "Planned income": "Geplante Einnahmen",
  "Popular categories": "Beliebte Kategorien",
  "Premium": "Premium",
  "Premium is active.": "Premium ist aktiv.",
  "Premium is active. The plan change will take effect on the next App Store renewal.": "Premium ist aktiv. Die Planänderung wird mit der nächsten Erneuerung des App Store wirksam.",
  "Processing...": "Verarbeitung...",
  "Product temporarily unavailable.": "Produkt vorübergehend nicht verfügbar.",
  "Product: {{product}}": "Produkt: {{product}}",
  "Products for {{platform}}": "Produkte für {{platform}}",
  "Profile": "Profil",
  "Profile and security": "Profil und Sicherheit",
  "Profile saved.": "Profil gespeichert.",
  "Profile, language, and security": "Profil, Sprache und Sicherheit",
  "Purchase not confirmed. Try again.": "Kauf nicht bestätigt. Versuchen Sie es erneut.",
  "Recent transactions": "Neueste Transaktionen",
  "Registration": "Anmeldung",
  "Remaining": "Verbleibend",
  "Renewal canceled": "Verlängerung abgebrochen",
  "Request failed (HTTP {{status}}).": "Anfrage fehlgeschlagen (HTTP {{status}}).",
  "Resend email": "E-Mail erneut senden",
  "Restore purchases": "Einkäufe wiederherstellen",
  "Restored purchases: {{count}}.": "Wiederhergestellte Käufe: {{count}}.",
  "Restoring...": "Wiederherstellung...",
  "Retry": "Wiederholen",
  "Root level": "Hauptebene",
  "Runtime category tree": "Laufzeit-Kategoriestruktur",
  "Save": "Speichern",
  "Save and continue": "Speichern und fortfahren",
  "Save balance": "Saldo speichern",
  "Save password": "Passwort speichern",
  "Saving...": "Speichern...",
  "Segments show amounts by category.": "Segmente zeigen Beträge nach Kategorie an.",
  "Select": "Wählen",
  "Select a base currency.": "Wählen Sie eine Basiswährung aus.",
  "Select a category": "Wählen Sie eine Kategorie aus",
  "Select a category and an account.": "Wählen Sie eine Kategorie und ein Konto aus.",
  "Select a category.": "Wählen Sie eine Kategorie aus.",
  "Select a currency": "Wählen Sie eine Währung aus",
  "Select a date": "Wählen Sie ein Datum aus",
  "Select a language": "Wählen Sie eine Sprache aus",
  "Select a subcategory. A parent category cannot be added.": "Wählen Sie eine Unterkategorie aus. Eine übergeordnete Kategorie kann nicht hinzugefügt werden.",
  "Select account": "Konto auswählen",
  "Select an account.": "Wählen Sie ein Konto aus.",
  "Select an icon from the shared catalog": "Wählen Sie ein Symbol aus dem freigegebenen Katalog aus",
  "Select an interface language.": "Wählen Sie eine Oberflächensprache aus.",
  "Select the interface language and analytics currency.": "Wählen Sie die Sprache der Benutzeroberfläche und die Analysewährung aus.",
  "Send a request": "Senden Sie eine Anfrage",
  "Send email": "E-Mail senden",
  "Send request": "Anfrage senden",
  "Sending...": "Senden...",
  "Show": "Zeigen",
  "Show password": "Passwort anzeigen",
  "Settings": "Einstellungen",
  "Sign in": "Anmelden",
  "Signing in with Google...": "Mit Google anmelden...",
  "Signing in...": "Anmelden...",
  "Some store products are not available yet: {{products}}.": "Einige Store-Produkte sind noch nicht verfügbar: {{products}}.",
  "Spending across all accounts": "Ausgaben auf allen Konten",
  "Start date": "Startdatum",
  "Step {{current}} of 2: {{screen}}": "Schritt {{current}} von 2: {{screen}}",
  "Store products are available only on iOS and Android.": "Store-Produkte sind nur für iOS und Android verfügbar.",
  "Store products are not available yet. Please check App Store or Google Play product setup.": "Store-Produkte sind noch nicht verfügbar. Bitte überprüfen Sie die Produkteinrichtung im App Store oder bei Google Play.",
  "Store purchases are available only on iOS and Android.": "Store-Käufe sind nur auf iOS und Android verfügbar.",
  "Store purchases require iOS or Android": "Für Einkäufe im Store ist iOS oder Android erforderlich",
  "Store transaction is missing orderId.": "In der Store-Transaktion fehlt orderId.",
  "Store transaction is missing originalTransactionId.": "In der Store-Transaktion fehlt originalTransactionId.",
  "Store transaction is missing packageName.": "In der Store-Transaktion fehlt packageName.",
  "Store transaction is missing purchaseToken.": "In der Store-Transaktion fehlt purchaseToken.",
  "Store transaction is missing signed payload.": "Bei der Store-Transaktion fehlt die signierte Nutzlast.",
  "Store transaction is missing transactionId.": "In der Store-Transaktion fehlt transactionId.",
  "Subcategories": "Unterkategorien",
  "Subject": "Betreff",
  "Subscribe": "Abonnieren",
  "Subscription": "Abonnement",
  "Subscription management": "Abonnementverwaltung",
  "Subscriptions": "Abonnements",
  "Support": "Support",
  "Tap the icon to select": "Tippen Sie zur Auswahl auf das Symbol",
  "Telegram username": "Telegram-Benutzername",
  "The account will be deleted.": "Das Konto wird gelöscht.",
  "The base currency cannot be changed because budgets or transactions already exist.": "Die Basiswährung kann nicht geändert werden, da bereits Budgets oder Transaktionen vorhanden sind.",
  "The budget category list for this month is empty.": "Die Budgetkategorieliste für diesen Monat ist leer.",
  "The category will be removed from this month's budget.": "Die Kategorie wird aus dem Budget dieses Monats entfernt.",
  "The payment is overdue. Premium access remains available through the grace-period date above.": "Die Zahlung ist überfällig. Der Premium-Zugang bleibt bis zum oben angegebenen Ende der Kulanzfrist verfügbar.",
  "The purchase was not confirmed by the store. Try again.": "Der Kauf wurde vom Shop nicht bestätigt. Versuchen Sie es erneut.",
  "The server did not respond in time. Try again.": "Der Server hat nicht rechtzeitig geantwortet. Versuchen Sie es erneut.",
  "The transaction will be permanently deleted.": "Die Transaktion wird dauerhaft gelöscht.",
  "The verified purchase is not active.": "Der verifizierte Kauf ist nicht aktiv.",
  "This account has no password. Password setup is handled separately.": "Dieses Konto hat kein Passwort. Die Passworteinrichtung wird separat behandelt.",
  "This purchase has already been received. Tap Restore purchases to restore the subscription.": "Dieser Kauf ist bereits eingegangen. Tippen Sie auf Käufe wiederherstellen, um das Abonnement wiederherzustellen.",
  "This purchase is linked to another MoneyDrive account. Sign in to the linked account or use a different App Store Sandbox account.": "Dieser Kauf ist mit einem anderen MoneyDrive-Konto verknüpft. Melden Sie sich beim verknüpften Konto an oder verwenden Sie ein anderes App Store Sandbox-Konto.",
  "This purchase period has already expired.": "Diese Kauffrist ist bereits abgelaufen.",
  "This purchase period has expired. Select a current subscription.": "Diese Kauffrist ist abgelaufen. Wählen Sie ein aktuelles Abonnement aus.",
  "This takes less than a minute.": "Dies dauert weniger als eine Minute.",
  "To goal: {{amount}}": "Zum Ziel: {{amount}}",
  "To renew with LiqPay, open the web version and complete a new checkout.": "Um mit LiqPay zu verlängern, öffnen Sie die Webversion und schließen Sie einen neuen Checkout ab.",
  "Top categories by spending ({{currency}})": "Top-Kategorien nach Ausgaben ({{currency}})",
  "Total": "Gesamt",
  "Total balance": "Gesamtsaldo",
  "Transactions": "Transaktionen",
  "Transfer": "Überweisung",
  "Type": "Typ",
  "Type: {{type}}": "Typ: {{type}}",
  "Unable to add the budget category (HTTP {{status}}).": "Die Budgetkategorie konnte nicht hinzugefügt werden (HTTP {{status}}).",
  "Unable to change password.": "Passwort kann nicht geändert werden.",
  "Unable to connect to the server.": "Es kann keine Verbindung zum Server hergestellt werden.",
  "Unable to create budget (HTTP {{status}}).": "Budget kann nicht erstellt werden (HTTP {{status}}).",
  "Unable to create the account.": "Das Konto kann nicht erstellt werden.",
  "Unable to create the category (HTTP {{status}}).": "Die Kategorie konnte nicht erstellt werden (HTTP {{status}}).",
  "Unable to delete the account.": "Das Konto kann nicht gelöscht werden.",
  "Unable to delete the category (HTTP {{status}}).": "Die Kategorie kann nicht gelöscht werden (HTTP {{status}}).",
  "Unable to delete the transaction.": "Die Transaktion kann nicht gelöscht werden.",
  "Unable to load accounts (HTTP {{status}}).": "Konten können nicht geladen werden (HTTP {{status}}).",
  "Unable to load accounts.": "Konten können nicht geladen werden.",
  "Unable to load budget (HTTP {{status}}).": "Budget kann nicht geladen werden (HTTP {{status}}).",
  "Unable to load budgets (HTTP {{status}}).": "Budgets können nicht geladen werden (HTTP {{status}}).",
  "Unable to load categories.": "Kategorien können nicht geladen werden.",
  "Unable to load category icons (HTTP {{status}}).": "Kategoriesymbole können nicht geladen werden (HTTP {{status}}).",
  "Unable to load category icons.": "Kategoriesymbole können nicht geladen werden.",
  "Unable to load dashboard (HTTP {{status}}).": "Dashboard kann nicht geladen werden (HTTP {{status}}).",
  "Unable to load frequent categories.": "Häufige Kategorien können nicht geladen werden.",
  "Unable to load settings.": "Einstellungen können nicht geladen werden.",
  "Unable to load subscription products.": "Abonnementprodukte können nicht geladen werden.",
  "Unable to load subscription status.": "Der Abonnementstatus konnte nicht geladen werden.",
  "Unable to load transactions.": "Transaktionen können nicht geladen werden.",
  "Unable to open onboarding.": "Onboarding kann nicht geöffnet werden.",
  "Unable to open the account.": "Das Konto kann nicht eröffnet werden.",
  "Unable to open the category for editing.": "Die Kategorie kann nicht zum Bearbeiten geöffnet werden.",
  "Unable to open the category.": "Die Kategorie kann nicht geöffnet werden.",
  "Unable to open the transaction.": "Die Transaktion kann nicht geöffnet werden.",
  "Unable to prepare the expense form.": "Das Ausgabenformular konnte nicht vorbereitet werden.",
  "Unable to remove the budget category (HTTP {{status}}).": "Die Budgetkategorie konnte nicht entfernt werden (HTTP {{status}}).",
  "Unable to resend the email.": "Die E-Mail kann nicht erneut gesendet werden.",
  "Unable to save the profile.": "Das Profil konnte nicht gespeichert werden.",
  "Unable to save the transaction.": "Die Transaktion konnte nicht gespeichert werden.",
  "Unable to send request.": "Anfrage konnte nicht gesendet werden.",
  "Unable to update balance.": "Der Kontostand kann nicht aktualisiert werden.",
  "Unable to update the account.": "Das Konto kann nicht aktualisiert werden.",
  "Unable to update the budget category (HTTP {{status}}).": "Die Budgetkategorie konnte nicht aktualisiert werden (HTTP {{status}}).",
  "Unable to update the category (HTTP {{status}}).": "Die Kategorie kann nicht aktualisiert werden (HTTP {{status}}).",
  "Uncategorized": "Nicht kategorisiert",
  "Until {{date}}": "Bis {{date}}",
  "Untitled": "Ohne Titel",
  "Unverified": "Nicht bestätigt",
  "Update": "Aktualisieren",
  "Verification": "Überprüfung",
  "Verification token": "Verifizierungstoken",
  "Verified": "Verifiziert",
  "Verify email": "E-Mail bestätigen",
  "Verify with token": "Mit Token verifizieren",
  "Verifying email...": "E-Mail wird überprüft...",
  "View all": "Alle anzeigen",
  "View budgets": "Budgets anzeigen",
  "We sent a verification email to {{email}}.": "Wir haben eine Bestätigungs-E-Mail an {{email}} gesendet.",
  "We usually respond within one business day.": "Wir antworten in der Regel innerhalb eines Werktages.",
  "Your account and data are safe. Buy a new subscription to restore business features.": "Ihr Konto und Ihre Daten sind sicher. Kaufen Sie ein neues Abonnement, um die Geschäftsfunktionen wiederherzustellen.",
  "Your email": "Ihre E-Mail",
  "Your request has been sent to our support team.": "Ihre Anfrage wurde an unser Support-Team gesendet.",
  "Your session has expired. Sign in again.": "Ihre Sitzung ist abgelaufen. Melden Sie sich erneut an.",
  "categories": "Kategorien",
  "the specified address": "die angegebene Adresse",
  "{{amount}} remaining": "{{amount}} übrig",
  "{{percent}}% of plan": "{{percent}} % des Plans",
  "‹ Back": "‹ Zurück",
  "Account \"{{name}}\" will be deleted.": "Das Konto „{{name}}“ wird gelöscht.",
  "Category \"{{name}}\" will be deleted.": "Kategorie „{{name}}“ wird gelöscht.",
  "Account deleted": "Konto gelöscht",
  "Accounts, categories, budgets, transactions, transfers, settings, and access tokens will be deleted.": "Konten, Kategorien, Budgets, Transaktionen, Überweisungen, Einstellungen und Zugriffstoken werden gelöscht.",
  "Apple did not return credentials required for account deletion.": "Apple hat die für die Kontolöschung erforderlichen Anmeldedaten nicht zurückgegeben.",
  "Confirm your identity": "Identität bestätigen",
  "Danger zone": "Gefahrenbereich",
  "Delete MoneyDrive account": "MoneyDrive-Konto löschen",
  "Delete MoneyDrive account permanently": "MoneyDrive-Konto dauerhaft löschen",
  "Deleting account...": "Konto wird gelöscht...",
  "Deleting your account permanently removes your profile and financial data. This action cannot be undone.": "Durch das dauerhafte Löschen Ihres Kontos werden Profil und Finanzdaten entfernt. Dies kann nicht rückgängig gemacht werden.",
  "Deleting MoneyDrive does not cancel App Store billing. Cancel the subscription in Apple settings if you no longer want it.": "Das Löschen von MoneyDrive beendet die Abrechnung im App Store nicht. Kündigen Sie das Abonnement in den Apple-Einstellungen.",
  "Google Sign-In": "Mit Google anmelden",
  "Manage Apple subscription": "Apple-Abonnement verwalten",
  "Sign in with Apple": "Mit Apple anmelden",
  "Type DELETE to confirm": "Zur Bestätigung DELETE eingeben",
  "Unable to open subscription management.": "Die Abonnementverwaltung konnte nicht geöffnet werden.",
} as const;

export default de;
