const es = {
  "+{{amount}} above plan 🚀": "+{{amount}} por encima del plan 🚀",
  "30 days": "30 días",
  "A subcategory cannot contain nested subcategories.": "Una subcategoría no puede contener subcategorías anidadas.",
  "Access denied.": "Acceso denegado.",
  "Access until: {{date}}": "Acceso hasta: {{date}}",
  Account: "Cuenta",
  "Account settings": "Configuración de la cuenta",
  "Account unavailable.": "Cuenta no disponible.",
  "Account: {{name}}": "Cuenta: {{name}}",
  Accounts: "Cuentas",
  "Across all accounts": "En todas las cuentas",
  Actual: "Real",
  "Actual expense": "Gasto real",
  "Actual income": "Ingreso real",
  Add: "Añadir",
  "Add account": "Añadir cuenta",
  "Add budget": "Añadir presupuesto",
  "Add category": "Añadir categoría",
  "Add details": "Añadir detalles",
  "Add subcategory": "Añadir subcategoría",
  "Add to budget": "Añadir al presupuesto",
  "Add transaction": "Añadir transacción",
  "Add your first expense": "Añade tu primer gasto",
  "Adding...": "Añadiendo...",
  "All accounts": "Todas las cuentas",
  "All categories": "Todas las categorías",
  "All recorded income categories": "Todas las categorías de ingresos registradas",
  "All steps completed": "Todos los pasos completados",
  "All time": "Todo el período",
  "All types": "Todos los tipos",
  Amount: "Importe",
  "Analytics period": "Período de análisis",
  "Another store purchase is already in progress.": "Ya hay otra compra en la tienda en curso.",
  "Apple did not return an identity token.": "Apple no devolvió un token de identidad.",
  "App Store saved {{actualProductId}} instead of {{requestedProductId}}. Check the current plan in App Store subscription settings.": "App Store guardó {{actualProductId}} en lugar de {{requestedProductId}}. Comprueba el plan actual en la configuración de suscripciones de App Store.",
  "Auto-renew off": "Renovación automática desactivada",
  "Auto-renewal is off. Premium access remains available through the date above.": "La renovación automática está desactivada. El acceso Premium seguirá disponible hasta la fecha indicada arriba.",
  "Available plans": "Planes disponibles",
  Back: "Atrás",
  "Back to sign in": "Volver al inicio de sesión",
  Balance: "Saldo",
  "Balance update timed out. Check that the backend API is available.": "Se agotó el tiempo para actualizar el saldo. Comprueba que la API del backend esté disponible.",
  "Base currency": "Moneda base",
  Budget: "Presupuesto",
  "Budget category": "Categoría del presupuesto",
  "Budget changes and category editing will be added after the backend API is extended.": "Los cambios de presupuesto y la edición de categorías se añadirán cuando se amplíe la API del backend.",
  "Budget details": "Detalles del presupuesto",
  "Budget not found.": "No se encontró el presupuesto.",
  "Budget progress": "Progreso del presupuesto",
  Budgets: "Presupuestos",
  C: "C",
  Cancel: "Cancelar",
  Categories: "Categorías",
  Category: "Categoría",
  "Category disabled": "Categoría desactivada",
  "Category enabled": "Categoría activada",
  "Category not found in the budget.": "No se encontró la categoría en el presupuesto.",
  "Category unavailable.": "Categoría no disponible.",
  'Category "{{name}}" will become a group. It can no longer be selected in new transactions and budgets. Existing records will remain unchanged.': 'La categoría "{{name}}" se convertirá en un grupo. Ya no podrá seleccionarse en nuevas transacciones y presupuestos. Los registros existentes no cambiarán.',
  "Category will become a group": "La categoría se convertirá en un grupo",
  "Change balance": "Cambiar saldo",
  "Change password": "Cambiar contraseña",
  "Check your email": "Revisa tu correo electrónico",
  "Checking authentication...": "Comprobando autenticación...",
  "Choose an App Store or Google Play product below.": "Elige abajo un producto de App Store o Google Play.",
  Comment: "Comentario",
  "Complete all password fields.": "Completa todos los campos de contraseña.",
  "Confirm new password": "Confirmar nueva contraseña",
  "Confirm password": "Confirmar contraseña",
  "Contact support": "Contactar con soporte",
  Continue: "Continuar",
  Create: "Crear",
  "Create account": "Crear cuenta",
  "Creating...": "Creando...",
  Currency: "Moneda",
  "Current password": "Contraseña actual",
  "Current plan": "Plan actual",
  Custom: "Personalizado",
  DONE: "HECHO",
  Dashboard: "Resumen",
  Date: "Fecha",
  "Date YYYY-MM-DD": "Fecha AAAA-MM-DD",
  Delete: "Eliminar",
  "Delete account?": "¿Eliminar la cuenta?",
  "Delete category": "Eliminar categoría",
  "Delete category?": "¿Eliminar la categoría?",
  "Delete transaction": "Eliminar transacción",
  "Delete transaction?": "¿Eliminar la transacción?",
  "Deleting...": "Eliminando...",
  Description: "Descripción",
  Disabled: "Desactivado",
  Edit: "Editar",
  "Edit account": "Editar cuenta",
  "Edit transaction": "Editar transacción",
  Editing: "Edición",
  Email: "Correo electrónico",
  "Email resent. Retry in {{seconds}} seconds.": "Correo reenviado. Inténtalo de nuevo en {{seconds}} segundos.",
  "Email sent. You can retry in about {{seconds}} seconds.": "Correo enviado. Puedes intentarlo de nuevo dentro de unos {{seconds}} segundos.",
  "Email verification": "Verificación del correo electrónico",
  "Email verified. You can now sign in.": "Correo verificado. Ya puedes iniciar sesión.",
  "Email was not sent. Try again in {{seconds}} seconds.": "No se envió el correo. Inténtalo de nuevo en {{seconds}} segundos.",
  "End date": "Fecha de finalización",
  "Enter a category name.": "Introduce un nombre de categoría.",
  "Enter a date.": "Introduce una fecha.",
  "Enter a message.": "Introduce un mensaje.",
  "Enter a new password.": "Introduce una nueva contraseña.",
  "Enter a subject.": "Introduce un asunto.",
  "Enter a valid amount.": "Introduce un importe válido.",
  "Enter a valid balance.": "Introduce un saldo válido.",
  "Enter a valid email address.": "Introduce una dirección de correo válida.",
  "Enter a valid planned amount greater than 0.": "Introduce un importe planificado válido mayor que 0.",
  "Enter an account name.": "Introduce un nombre de cuenta.",
  "Enter an amount greater than zero.": "Introduce un importe mayor que cero.",
  "Enter your email": "Introduce tu correo electrónico",
  "Enter your email, name, and password.": "Introduce tu correo electrónico, nombre y contraseña.",
  "Enter your email.": "Introduce tu correo electrónico.",
  "Enter your name": "Introduce tu nombre",
  Expense: "Gasto",
  "Expense categories": "Categorías de gastos",
  "Expense categories are not available yet.": "Las categorías de gastos aún no están disponibles.",
  "Expense not submitted: complete the required fields.": "No se guardó el gasto: completa los campos obligatorios.",
  Expenses: "Gastos",
  "Expenses and income": "Gastos e ingresos",
  "Expenses this period": "Gastos de este período",
  "Fill password": "Introducir contraseña",
  "Forgot password?": "¿Has olvidado la contraseña?",
  Free: "Gratis",
  "From {{date}}": "Desde {{date}}",
  "Go to sign in": "Ir al inicio de sesión",
  "Goal reached! 🎉": "¡Objetivo alcanzado! 🎉",
  "Google Sign-In is not configured for this build.": "El inicio de sesión con Google no está configurado para esta compilación.",
  "Google did not return an ID token.": "Google no devolvió un token de ID.",
  Group: "Grupo",
  Hide: "Ocultar",
  "Hide form": "Ocultar formulario",
  "Hide password": "Ocultar contraseña",
  Home: "Inicio",
  "I have a token": "Tengo un token",
  Icon: "Icono",
  "If the account exists, an email has been sent.": "Si la cuenta existe, se ha enviado un correo electrónico.",
  "If the account exists, an email has been sent. Retry in {{seconds}} seconds.": "Si la cuenta existe, se ha enviado un correo electrónico. Inténtalo de nuevo en {{seconds}} segundos.",
  "If the email contains a production link, paste the token manually for local testing.": "Si el correo contiene un enlace de producción, pega el token manualmente para las pruebas locales.",
  Income: "Ingreso",
  "Income categories": "Categorías de ingresos",
  "Income categories are not available yet.": "Las categorías de ingresos aún no están disponibles.",
  "Income this period": "Ingresos de este período",
  "Initial setup": "Configuración inicial",
  "Interface language": "Idioma de la interfaz",
  "Invalid accounts response format.": "Formato de respuesta de cuentas no válido.",
  "Invalid budget response format.": "Formato de respuesta del presupuesto no válido.",
  "Keep an eye on all of your balances.": "Controla todos tus saldos.",
  "Language and base currency": "Idioma y moneda base",
  "LiqPay subscription can be cancelled only in the web version of the app.": "La suscripción de LiqPay solo puede cancelarse en la versión web de la aplicación.",
  "Loading accounts...": "Cargando cuentas...",
  "Loading budget...": "Cargando presupuesto...",
  "Loading budgets...": "Cargando presupuestos...",
  "Loading categories...": "Cargando categorías...",
  "Loading dashboard...": "Cargando resumen...",
  "Loading icons...": "Cargando iconos...",
  "Loading onboarding...": "Cargando configuración inicial...",
  "Loading settings...": "Cargando configuración...",
  "Loading store products...": "Cargando productos de la tienda...",
  "Loading subscription status...": "Cargando estado de la suscripción...",
  "Loading...": "Cargando...",
  "Log in": "Iniciar sesión",
  "Login with Google": "Iniciar sesión con Google",
  Logout: "Cerrar sesión",
  "Manage on web": "Gestionar en la web",
  "Manage premium access": "Gestionar acceso Premium",
  "Manage subscription": "Gestionar suscripción",
  "Maximum category depth is 2 levels": "La profundidad máxima de categorías es de 2 niveles",
  "Maximum category depth is 2 levels.": "La profundidad máxima de categorías es de 2 niveles.",
  Message: "Mensaje",
  "Missing Android subscription offer token for selected product.": "Falta el token de oferta de suscripción de Android para el producto seleccionado.",
  "Missing account ID.": "Falta el ID de la cuenta.",
  "Missing budgetId.": "Falta budgetId.",
  "Missing reset token.": "Falta el token de restablecimiento.",
  "MoneyDrive.me": "MoneyDrive.me",
  Month: "Mes",
  More: "Más",
  "More service sections": "Más secciones del servicio",
  "Most frequent": "Más frecuentes",
  Name: "Nombre",
  "New account": "Nueva cuenta",
  "New balance": "Nuevo saldo",
  "New category": "Nueva categoría",
  "New email awaiting verification: {{email}}": "Nuevo correo pendiente de verificación: {{email}}",
  "New password": "Nueva contraseña",
  "New planned amount": "Nuevo importe planificado",
  "No App Store Sandbox account is connected on this device. Add a sandbox tester in Settings > App Store > Sandbox Account.": "No hay ninguna cuenta de App Store Sandbox conectada en este dispositivo. Añade un usuario de prueba en Ajustes > App Store > Cuenta Sandbox.",
  "No account": "Sin cuenta",
  "No account data.": "No hay datos de la cuenta.",
  "No accounts.": "No hay cuentas.",
  "No active purchases found.": "No se encontraron compras activas.",
  "No active store source": "Sin tienda activa",
  "No budget has been created for the selected month.": "No se ha creado ningún presupuesto para el mes seleccionado.",
  "No budgets for the selected period.": "No hay presupuestos para el período seleccionado.",
  "No budgets found yet.": "Aún no se encontraron presupuestos.",
  "No categories available to add.": "No hay categorías disponibles para añadir.",
  "No categories found for the selected type.": "No se encontraron categorías para el tipo seleccionado.",
  "No categories found.": "No se encontraron categorías.",
  "No categories.": "No hay categorías.",
  "No data for the selected period.": "No hay datos para el período seleccionado.",
  "No data.": "No hay datos.",
  "No external management action is available.": "No hay ninguna acción de gestión externa disponible.",
  "No period selected": "Ningún período seleccionado",
  "No transaction data.": "No hay datos de transacciones.",
  "No transactions yet.": "Aún no hay transacciones.",
  "Not enough data to add the category.": "No hay datos suficientes para añadir la categoría.",
  "Not set": "Sin establecer",
  Note: "Nota",
  Open: "Abrir",
  "Open App Store account settings and choose Subscriptions.": "Abre la configuración de la cuenta de App Store y selecciona Suscripciones.",
  "Open the subscription provider account settings to manage this plan.": "Abre la configuración de la cuenta del proveedor de la suscripción para gestionar este plan.",
  "Overspent by {{amount}}": "Exceso de gasto de {{amount}}",
  "Parent: {{name}}": "Principal: {{name}}",
  Password: "Contraseña",
  "Password changed.": "Contraseña cambiada.",
  "Password recovery": "Recuperación de contraseña",
  "Password updated. You can now sign in.": "Contraseña actualizada. Ya puedes iniciar sesión.",
  "Passwords do not match.": "Las contraseñas no coinciden.",
  "Paste the verification token.": "Pega el token de verificación.",
  "Period: {{period}}": "Período: {{period}}",
  "Plan ({{currency}})": "Plan ({{currency}})",
  "Plan / actual / remaining by category": "Plan / real / restante por categoría",
  "Plan {{plan}} · Actual {{actual}}": "Plan {{plan}} · Real {{actual}}",
  "Plans and billing": "Planes y facturación",
  "Planned amount ({{currency}})": "Importe planificado ({{currency}})",
  "Planned expense": "Gasto planificado",
  "Planned income": "Ingreso planificado",
  "Popular categories": "Categorías populares",
  Premium: "Premium",
  "Premium is active.": "Premium está activo.",
  "Premium is active. The plan change will take effect on the next App Store renewal.": "Premium está activo. El cambio de plan se aplicará en la próxima renovación de App Store.",
  "Processing...": "Procesando...",
  "Product temporarily unavailable.": "Producto temporalmente no disponible.",
  "Product: {{product}}": "Producto: {{product}}",
  "Products for {{platform}}": "Productos para {{platform}}",
  Profile: "Perfil",
  "Profile and security": "Perfil y seguridad",
  "Profile saved.": "Perfil guardado.",
  "Profile, language, and security": "Perfil, idioma y seguridad",
  "Purchase not confirmed. Try again.": "Compra no confirmada. Inténtalo de nuevo.",
  "Recent transactions": "Transacciones recientes",
  Registration: "Registro",
  Remaining: "Restante",
  "Renewal canceled": "Renovación cancelada",
  "Request failed (HTTP {{status}}).": "La solicitud falló (HTTP {{status}}).",
  "Resend email": "Reenviar correo",
  "Restore purchases": "Restaurar compras",
  "Restored purchases: {{count}}.": "Compras restauradas: {{count}}.",
  "Restoring...": "Restaurando...",
  Retry: "Reintentar",
  "Root level": "Nivel raíz",
  "Runtime category tree": "Árbol actual de categorías",
  Save: "Guardar",
  "Save and continue": "Guardar y continuar",
  "Save balance": "Guardar saldo",
  "Save password": "Guardar contraseña",
  "Saving...": "Guardando...",
  "Segments show amounts by category.": "Los segmentos muestran los importes por categoría.",
  Select: "Seleccionar",
  "Select a base currency.": "Selecciona una moneda base.",
  "Select a category": "Selecciona una categoría",
  "Select a category and an account.": "Selecciona una categoría y una cuenta.",
  "Select a category.": "Selecciona una categoría.",
  "Select a currency": "Selecciona una moneda",
  "Select a date": "Selecciona una fecha",
  "Select a language": "Selecciona un idioma",
  "Select a subcategory. A parent category cannot be added.": "Selecciona una subcategoría. No se puede añadir una categoría principal.",
  "Select account": "Selecciona una cuenta",
  "Select an account.": "Selecciona una cuenta.",
  "Select an icon from the shared catalog": "Selecciona un icono del catálogo compartido",
  "Select an interface language.": "Selecciona un idioma para la interfaz.",
  "Select the interface language and analytics currency.": "Selecciona el idioma de la interfaz y la moneda de análisis.",
  "Send a request": "Enviar una solicitud",
  "Send email": "Enviar correo",
  "Send request": "Enviar solicitud",
  "Sending...": "Enviando...",
  Show: "Mostrar",
  "Show password": "Mostrar contraseña",
  Settings: "Configuración",
  "Sign in": "Iniciar sesión",
  "Signing in with Google...": "Iniciando sesión con Google...",
  "Signing in...": "Iniciando sesión...",
  "Some store products are not available yet: {{products}}.": "Algunos productos de la tienda aún no están disponibles: {{products}}.",
  "Spending across all accounts": "Gastos en todas las cuentas",
  "Start date": "Fecha de inicio",
  "Step {{current}} of 2: {{screen}}": "Paso {{current}} de 2: {{screen}}",
  "Store products are available only on iOS and Android.": "Los productos de la tienda solo están disponibles en iOS y Android.",
  "Store products are not available yet. Please check App Store or Google Play product setup.": "Los productos de la tienda aún no están disponibles. Comprueba la configuración de productos de App Store o Google Play.",
  "Store purchases are available only on iOS and Android.": "Las compras de la tienda solo están disponibles en iOS y Android.",
  "Store purchases require iOS or Android": "Las compras de la tienda requieren iOS o Android",
  "Store transaction is missing orderId.": "Falta orderId en la transacción de la tienda.",
  "Store transaction is missing originalTransactionId.": "Falta originalTransactionId en la transacción de la tienda.",
  "Store transaction is missing packageName.": "Falta packageName en la transacción de la tienda.",
  "Store transaction is missing purchaseToken.": "Falta purchaseToken en la transacción de la tienda.",
  "Store transaction is missing signed payload.": "Faltan los datos firmados en la transacción de la tienda.",
  "Store transaction is missing transactionId.": "Falta transactionId en la transacción de la tienda.",
  Subcategories: "Subcategorías",
  Subject: "Asunto",
  Subscribe: "Suscribirse",
  Subscription: "Suscripción",
  "Subscription management": "Gestión de la suscripción",
  Subscriptions: "Suscripciones",
  Support: "Soporte",
  "Tap the icon to select": "Toca el icono para seleccionarlo",
  "Telegram username": "Nombre de usuario de Telegram",
  "The account will be deleted.": "La cuenta se eliminará.",
  "The base currency cannot be changed because budgets or transactions already exist.": "La moneda base no se puede cambiar porque ya existen presupuestos o transacciones.",
  "The budget category list for this month is empty.": "La lista de categorías del presupuesto de este mes está vacía.",
  "The category will be removed from this month's budget.": "La categoría se eliminará del presupuesto de este mes.",
  "The payment is overdue. Premium access remains available through the grace-period date above.": "El pago está vencido. El acceso Premium seguirá disponible hasta la fecha del período de gracia indicada arriba.",
  "The purchase was not confirmed by the store. Try again.": "La tienda no confirmó la compra. Inténtalo de nuevo.",
  "The server did not respond in time. Try again.": "El servidor no respondió a tiempo. Inténtalo de nuevo.",
  "The transaction will be permanently deleted.": "La transacción se eliminará permanentemente.",
  "The verified purchase is not active.": "La compra verificada no está activa.",
  "This account has no password. Password setup is handled separately.": "Esta cuenta no tiene contraseña. La configuración de la contraseña se realiza por separado.",
  "This purchase has already been received. Tap Restore purchases to restore the subscription.": "Esta compra ya se ha recibido. Toca Restaurar compras para recuperar la suscripción.",
  "This purchase is linked to another MoneyDrive account. Sign in to the linked account or use a different App Store Sandbox account.": "Esta compra está vinculada a otra cuenta de MoneyDrive. Inicia sesión en la cuenta vinculada o usa otra cuenta de App Store Sandbox.",
  "This purchase period has already expired.": "El período de esta compra ya ha vencido.",
  "This purchase period has expired. Select a current subscription.": "El período de esta compra ha vencido. Selecciona una suscripción vigente.",
  "This takes less than a minute.": "Esto tarda menos de un minuto.",
  "To goal: {{amount}}": "Para el objetivo: {{amount}}",
  "To renew with LiqPay, open the web version and complete a new checkout.": "Para renovar con LiqPay, abre la versión web y completa una nueva compra.",
  "Top categories by spending ({{currency}})": "Principales categorías por gasto ({{currency}})",
  Total: "Total",
  "Total balance": "Saldo total",
  Transactions: "Transacciones",
  Transfer: "Transferencia",
  Type: "Tipo",
  "Type: {{type}}": "Tipo: {{type}}",
  "Unable to add the budget category (HTTP {{status}}).": "No se pudo añadir la categoría al presupuesto (HTTP {{status}}).",
  "Unable to change password.": "No se pudo cambiar la contraseña.",
  "Unable to connect to the server.": "No se pudo conectar con el servidor.",
  "Unable to create budget (HTTP {{status}}).": "No se pudo crear el presupuesto (HTTP {{status}}).",
  "Unable to create the account.": "No se pudo crear la cuenta.",
  "Unable to create the category (HTTP {{status}}).": "No se pudo crear la categoría (HTTP {{status}}).",
  "Unable to delete the account.": "No se pudo eliminar la cuenta.",
  "Unable to delete the category (HTTP {{status}}).": "No se pudo eliminar la categoría (HTTP {{status}}).",
  "Unable to delete the transaction.": "No se pudo eliminar la transacción.",
  "Unable to load accounts (HTTP {{status}}).": "No se pudieron cargar las cuentas (HTTP {{status}}).",
  "Unable to load accounts.": "No se pudieron cargar las cuentas.",
  "Unable to load budget (HTTP {{status}}).": "No se pudo cargar el presupuesto (HTTP {{status}}).",
  "Unable to load budgets (HTTP {{status}}).": "No se pudieron cargar los presupuestos (HTTP {{status}}).",
  "Unable to load categories.": "No se pudieron cargar las categorías.",
  "Unable to load category icons (HTTP {{status}}).": "No se pudieron cargar los iconos de categorías (HTTP {{status}}).",
  "Unable to load category icons.": "No se pudieron cargar los iconos de categorías.",
  "Unable to load dashboard (HTTP {{status}}).": "No se pudo cargar el resumen (HTTP {{status}}).",
  "Unable to load frequent categories.": "No se pudieron cargar las categorías frecuentes.",
  "Unable to load settings.": "No se pudo cargar la configuración.",
  "Unable to load subscription products.": "No se pudieron cargar los productos de suscripción.",
  "Unable to load subscription status.": "No se pudo cargar el estado de la suscripción.",
  "Unable to load transactions.": "No se pudieron cargar las transacciones.",
  "Unable to open onboarding.": "No se pudo abrir la configuración inicial.",
  "Unable to open the account.": "No se pudo abrir la cuenta.",
  "Unable to open the category for editing.": "No se pudo abrir la categoría para editarla.",
  "Unable to open the category.": "No se pudo abrir la categoría.",
  "Unable to open the transaction.": "No se pudo abrir la transacción.",
  "Unable to prepare the expense form.": "No se pudo preparar el formulario de gastos.",
  "Unable to remove the budget category (HTTP {{status}}).": "No se pudo quitar la categoría del presupuesto (HTTP {{status}}).",
  "Unable to resend the email.": "No se pudo reenviar el correo electrónico.",
  "Unable to save the profile.": "No se pudo guardar el perfil.",
  "Unable to save the transaction.": "No se pudo guardar la transacción.",
  "Unable to send request.": "No se pudo enviar la solicitud.",
  "Unable to update balance.": "No se pudo actualizar el saldo.",
  "Unable to update the account.": "No se pudo actualizar la cuenta.",
  "Unable to update the budget category (HTTP {{status}}).": "No se pudo actualizar la categoría del presupuesto (HTTP {{status}}).",
  "Unable to update the category (HTTP {{status}}).": "No se pudo actualizar la categoría (HTTP {{status}}).",
  Uncategorized: "Sin categoría",
  "Until {{date}}": "Hasta {{date}}",
  Untitled: "Sin título",
  Unverified: "Sin verificar",
  Update: "Actualizar",
  Verification: "Verificación",
  "Verification token": "Token de verificación",
  Verified: "Verificado",
  "Verify email": "Verificar correo electrónico",
  "Verify with token": "Verificar con token",
  "Verifying email...": "Verificando correo electrónico...",
  "View all": "Ver todo",
  "View budgets": "Ver presupuestos",
  "We sent a verification email to {{email}}.": "Hemos enviado un correo de verificación a {{email}}.",
  "We usually respond within one business day.": "Normalmente respondemos en un día laborable.",
  "Your account and data are safe. Buy a new subscription to restore business features.": "Tu cuenta y tus datos están seguros. Compra una nueva suscripción para restaurar las funciones empresariales.",
  "Your email": "Tu correo electrónico",
  "Your request has been sent to our support team.": "Tu solicitud se ha enviado a nuestro equipo de soporte.",
  "Your session has expired. Sign in again.": "Tu sesión ha caducado. Vuelve a iniciar sesión.",
  categories: "categorías",
  "the specified address": "la dirección indicada",
  "{{amount}} remaining": "Quedan {{amount}}",
  "{{percent}}% of plan": "{{percent}} % del plan",
  "‹ Back": "‹ Atrás",
  'Account "{{name}}" will be deleted.': 'Se eliminará la cuenta "{{name}}".',
  'Category "{{name}}" will be deleted.': 'Se eliminará la categoría "{{name}}".',
} as const;

export default es;
