const fr = {
  "+{{amount}} above plan 🚀": "+{{amount}} au-dessus du montant prévu 🚀",
  "30 days": "30 jours",
  "A subcategory cannot contain nested subcategories.": "Une sous-catégorie ne peut pas contenir de sous-catégories imbriquées.",
  "Access denied.": "Accès refusé.",
  "Access until: {{date}}": "Accès jusqu'à : {{date}}",
  "Account": "Compte",
  "Account settings": "Paramètres du compte",
  "Account unavailable.": "Compte indisponible.",
  "Account: {{name}}": "Compte : {{name}}",
  "Accounts": "Comptes",
  "Across all accounts": "Sur tous les comptes",
  "Actual": "Réel",
  "Actual expense": "Dépense réelle",
  "Actual income": "Revenu réel",
  "Add": "Ajouter",
  "Add account": "Ajouter un compte",
  "Add budget": "Ajouter un budget",
  "Add category": "Ajouter une catégorie",
  "Add details": "Ajouter des détails",
  "Add subcategory": "Ajouter une sous-catégorie",
  "Add to budget": "Ajouter au budget",
  "Add transaction": "Ajouter une transaction",
  "Add your first expense": "Ajoutez votre première dépense",
  "Adding...": "Ajout...",
  "All accounts": "Tous les comptes",
  "All categories": "Toutes les catégories",
  "All recorded income categories": "Toutes les catégories de revenus enregistrées",
  "All steps completed": "Toutes les étapes terminées",
  "All time": "Toute la période",
  "All types": "Tous les types",
  "Amount": "Montant",
  "Analytics period": "Période d'analyse",
  "Another store purchase is already in progress.": "Un autre achat en magasin est déjà en cours.",
  "Apple did not return an identity token.": "Apple n'a pas renvoyé de jeton d'identité.",
  "App Store saved {{actualProductId}} instead of {{requestedProductId}}. Check the current plan in App Store subscription settings.": "L'App Store a enregistré {{actualProductId}} au lieu de {{requestedProductId}}. Vérifiez le forfait actuel dans les paramètres d'abonnement de l'App Store.",
  "Auto-renew off": "Renouvellement automatique désactivé",
  "Auto-renewal is off. Premium access remains available through the date above.": "Le renouvellement automatique est désactivé. L’accès Premium reste disponible jusqu’à la date ci-dessus.",
  "Available plans": "Forfaits disponibles",
  "Back": "Retour",
  "Back to sign in": "Retour à la connexion",
  "Balance": "Solde",
  "Balance update timed out. Check that the backend API is available.": "La mise à jour du solde a expiré. Vérifiez que l'API backend est disponible.",
  "Base currency": "Monnaie de base",
  "Budget": "Budget",
  "Budget category": "Catégorie budgétaire",
  "Budget changes and category editing will be added after the backend API is extended.": "Les modifications du budget et la modification des catégories seront ajoutées après l'extension de l'API backend.",
  "Budget details": "Détails du budget",
  "Budget not found.": "Budget introuvable.",
  "Budget progress": "Progression des budgets",
  "Budgets": "Budgets",
  "C": "C",
  "Cancel": "Annuler",
  "Categories": "Catégories",
  "Category": "Catégorie",
  "Category disabled": "Catégorie désactivée",
  "Category enabled": "Catégorie activée",
  "Category not found in the budget.": "Catégorie introuvable dans le budget.",
  "Category unavailable.": "Catégorie indisponible.",
  "Category \"{{name}}\" will become a group. It can no longer be selected in new transactions and budgets. Existing records will remain unchanged.": "La catégorie \"{{name}}\" deviendra un groupe. Elle ne pourra plus être sélectionnée pour de nouvelles transactions ni de nouveaux budgets. Les enregistrements existants resteront inchangés.",
  "Category will become a group": "La catégorie deviendra un groupe",
  "Change balance": "Modifier le solde",
  "Change password": "Changer le mot de passe",
  "Check your email": "Vérifiez votre e-mail",
  "Checking authentication...": "Vérification de l'authentification...",
  "Choose an App Store or Google Play product below.": "Choisissez un produit App Store ou Google Play ci-dessous.",
  "Comment": "Commentaire",
  "Complete all password fields.": "Remplissez tous les champs de mot de passe.",
  "Confirm new password": "Confirmer le nouveau mot de passe",
  "Confirm password": "Confirmer le mot de passe",
  "Contact support": "Contacter l'assistance",
  "Continue": "Continuer",
  "Create": "Créer",
  "Create account": "Créer un compte",
  "Creating...": "Création...",
  "Currency": "Devise",
  "Current password": "Mot de passe actuel",
  "Current plan": "Forfait actuel",
  "Custom": "Personnalisé",
  "DONE": "FAIT",
  "Dashboard": "Tableau de bord",
  "Date": "Date",
  "Date YYYY-MM-DD": "Date AAAA-MM-JJ",
  "Delete": "Supprimer",
  "Delete account?": "Supprimer le compte ?",
  "Delete category": "Supprimer la catégorie",
  "Delete category?": "Supprimer la catégorie ?",
  "Delete transaction": "Supprimer la transaction",
  "Delete transaction?": "Supprimer la transaction ?",
  "Deleting...": "Suppression...",
  "Description": "Description",
  "Disabled": "Désactivée",
  "Edit": "Modifier",
  "Edit account": "Modifier le compte",
  "Edit transaction": "Modifier la transaction",
  "Editing": "Modification",
  "Email": "E-mail",
  "Email resent. Retry in {{seconds}} seconds.": "E-mail renvoyé. Réessayez dans {{seconds}} secondes.",
  "Email sent. You can retry in about {{seconds}} seconds.": "E-mail envoyé. Vous pourrez réessayer dans environ {{seconds}} secondes.",
  "Email verification": "Vérification des e-mails",
  "Email verified. You can now sign in.": "E-mail vérifié. Vous pouvez maintenant vous connecter.",
  "Email was not sent. Try again in {{seconds}} seconds.": "L'e-mail n'a pas été envoyé. Réessayez dans {{seconds}} secondes.",
  "End date": "Date de fin",
  "Enter a category name.": "Entrez un nom de catégorie.",
  "Enter a date.": "Entrez une date.",
  "Enter a message.": "Saisissez un message.",
  "Enter a new password.": "Entrez un nouveau mot de passe.",
  "Enter a subject.": "Saisissez un objet.",
  "Enter a valid amount.": "Entrez un montant valide.",
  "Enter a valid balance.": "Entrez un solde valide.",
  "Enter a valid email address.": "Entrez une adresse e-mail valide.",
  "Enter a valid planned amount greater than 0.": "Saisissez un montant planifié valide supérieur à 0.",
  "Enter an account name.": "Saisissez un nom de compte.",
  "Enter an amount greater than zero.": "Entrez un montant supérieur à zéro.",
  "Enter your email": "Entrez votre email",
  "Enter your email, name, and password.": "Entrez votre e-mail, votre nom et votre mot de passe.",
  "Enter your email.": "Entrez votre email.",
  "Enter your name": "Entrez votre nom",
  "Expense": "Dépense",
  "Expense categories": "Catégories de dépenses",
  "Expense categories are not available yet.": "Les catégories de dépenses ne sont pas encore disponibles.",
  "Expense not submitted: complete the required fields.": "Dépense non soumise : complétez les champs obligatoires.",
  "Expenses": "Dépenses",
  "Expenses and income": "Dépenses et revenus",
  "Expenses this period": "Dépenses sur la période",
  "Fill password": "Remplir le mot de passe",
  "Forgot password?": "Mot de passe oublié ?",
  "Free": "Gratuit",
  "From {{date}}": "De {{date}}",
  "Go to sign in": "Aller à la connexion",
  "Goal reached! 🎉": "Objectif atteint ! 🎉",
  "Google Sign-In is not configured for this build.": "Google Sign-In n'est pas configuré pour cette version.",
  "Google did not return an ID token.": "Google n'a pas renvoyé de jeton d'identification.",
  "Group": "Groupe",
  "Hide": "Masquer",
  "Hide form": "Masquer le formulaire",
  "Hide password": "Masquer le mot de passe",
  "Home": "Accueil",
  "I have a token": "J'ai un jeton",
  "Icon": "Icône",
  "If the account exists, an email has been sent.": "Si le compte existe, un email a été envoyé.",
  "If the account exists, an email has been sent. Retry in {{seconds}} seconds.": "Si le compte existe, un email a été envoyé. Réessayez dans {{seconds}} secondes.",
  "If the email contains a production link, paste the token manually for local testing.": "Si l'e-mail contient un lien de production, collez le jeton manuellement pour des tests locaux.",
  "Income": "Revenus",
  "Income categories": "Catégories de revenus",
  "Income categories are not available yet.": "Les catégories de revenus ne sont pas encore disponibles.",
  "Income this period": "Revenus sur la période",
  "Initial setup": "Configuration initiale",
  "Interface language": "Langue de l'interface",
  "Invalid accounts response format.": "Format de réponse des comptes non valide.",
  "Invalid budget response format.": "Format de réponse budgétaire non valide.",
  "Keep an eye on all of your balances.": "Gardez un œil sur tous vos soldes.",
  "Language and base currency": "Langue et devise de base",
  "LiqPay subscription can be cancelled only in the web version of the app.": "L'abonnement LiqPay ne peut être annulé que dans la version Web de l'application.",
  "Loading accounts...": "Chargement des comptes...",
  "Loading budget...": "Chargement du budget...",
  "Loading budgets...": "Chargement des budgets...",
  "Loading categories...": "Chargement des catégories...",
  "Loading dashboard...": "Chargement du tableau de bord...",
  "Loading icons...": "Chargement des icônes...",
  "Loading onboarding...": "Chargement de la configuration initiale...",
  "Loading settings...": "Chargement des paramètres...",
  "Loading store products...": "Chargement des produits du magasin...",
  "Loading subscription status...": "Chargement du statut de l'abonnement...",
  "Loading...": "Chargement...",
  "Log in": "Se connecter",
  "Login with Google": "Se connecter avec Google",
  "Logout": "Se déconnecter",
  "Manage on web": "Gérer sur le Web",
  "Manage premium access": "Gérer l'accès premium",
  "Manage subscription": "Gérer l'abonnement",
  "Maximum category depth is 2 levels": "La profondeur maximale de la catégorie est de 2 niveaux",
  "Maximum category depth is 2 levels.": "La profondeur maximale des catégories est de 2 niveaux.",
  "Message": "Message",
  "Missing Android subscription offer token for selected product.": "Jeton d'offre d'abonnement Android manquant pour le produit sélectionné.",
  "Missing account ID.": "Identifiant de compte manquant.",
  "Missing budgetId.": "ID de budget manquant.",
  "Missing reset token.": "Jeton de réinitialisation manquant.",
  "MoneyDrive.me": "MoneyDrive.me",
  "Month": "Mois",
  "More": "Plus",
  "More service sections": "Plus de sections de services",
  "Most frequent": "Le plus fréquent",
  "Name": "Nom",
  "New account": "Nouveau compte",
  "New balance": "Nouveau solde",
  "New category": "Nouvelle catégorie",
  "New email awaiting verification: {{email}}": "Nouvel email en attente de vérification : {{email}}",
  "New password": "Nouveau mot de passe",
  "New planned amount": "Nouveau montant prévu",
  "No App Store Sandbox account is connected on this device. Add a sandbox tester in Settings > App Store > Sandbox Account.": "Aucun compte App Store Sandbox n'est connecté sur cet appareil. Ajoutez un testeur sandbox dans Paramètres > App Store > Compte Sandbox.",
  "No account": "Pas de compte",
  "No account data.": "Aucune donnée de compte.",
  "No accounts.": "Aucun compte.",
  "No active purchases found.": "Aucun achat actif trouvé.",
  "No active store source": "Aucune source de paiement active",
  "No budget has been created for the selected month.": "Aucun budget n'a été créé pour le mois sélectionné.",
  "No budgets for the selected period.": "Aucun budget pour la période sélectionnée.",
  "No budgets found yet.": "Aucun budget trouvé pour l'instant.",
  "No categories available to add.": "Aucune catégorie disponible à ajouter.",
  "No categories found for the selected type.": "Aucune catégorie trouvée pour le type sélectionné.",
  "No categories found.": "Aucune catégorie trouvée.",
  "No categories.": "Aucune catégorie.",
  "No data for the selected period.": "Aucune donnée pour la période sélectionnée.",
  "No data.": "Aucune donnée.",
  "No external management action is available.": "Aucune mesure de gestion externe n'est disponible.",
  "No period selected": "Aucune période sélectionnée",
  "No transaction data.": "Aucune donnée de transaction.",
  "No transactions yet.": "Aucune transaction pour l'instant.",
  "Not enough data to add the category.": "Pas assez de données pour ajouter la catégorie.",
  "Not set": "Non défini",
  "Note": "Note",
  "Open": "Ouvrir",
  "Open App Store account settings and choose Subscriptions.": "Ouvrez les paramètres du compte App Store et choisissez Abonnements.",
  "Open the subscription provider account settings to manage this plan.": "Ouvrez les paramètres du compte du fournisseur d'abonnement pour gérer ce plan.",
  "Overspent by {{amount}}": "Dépassé par {{amount}}",
  "Parent: {{name}}": "Parent : {{name}}",
  "Password": "Mot de passe",
  "Password changed.": "Mot de passe modifié.",
  "Password recovery": "Récupération de mot de passe",
  "Password updated. You can now sign in.": "Mot de passe mis à jour. Vous pouvez maintenant vous connecter.",
  "Passwords do not match.": "Les mots de passe ne correspondent pas.",
  "Paste the verification token.": "Collez le jeton de vérification.",
  "Period: {{period}}": "Période : {{period}}",
  "Plan ({{currency}})": "Plan ({{currency}})",
  "Plan / actual / remaining by category": "Prévu / réel / restant par catégorie",
  "Plan {{plan}} · Actual {{actual}}": "Plan {{plan}} · Réel {{actual}}",
  "Plans and billing": "Forfaits et facturation",
  "Planned amount ({{currency}})": "Montant prévu ({{currency}})",
  "Planned expense": "Dépense prévue",
  "Planned income": "Revenu prévu",
  "Popular categories": "Catégories populaires",
  "Premium": "Premium",
  "Premium is active.": "Premium est actif.",
  "Premium is active. The plan change will take effect on the next App Store renewal.": "Premium est actif. Le changement de forfait prendra effet lors du prochain renouvellement de l’App Store.",
  "Processing...": "Traitement...",
  "Product temporarily unavailable.": "Produit temporairement indisponible.",
  "Product: {{product}}": "Produit : {{product}}",
  "Products for {{platform}}": "Produits pour {{platform}}",
  "Profile": "Profil",
  "Profile and security": "Profil et sécurité",
  "Profile saved.": "Profil enregistré.",
  "Profile, language, and security": "Profil, langue et sécurité",
  "Purchase not confirmed. Try again.": "Achat non confirmé. Essayer à nouveau.",
  "Recent transactions": "Transactions récentes",
  "Registration": "Inscription",
  "Remaining": "Restant",
  "Renewal canceled": "Renouvellement annulé",
  "Request failed (HTTP {{status}}).": "Échec de la demande (HTTP {{status}}).",
  "Resend email": "Renvoyer l'e-mail",
  "Restore purchases": "Restaurer les achats",
  "Restored purchases: {{count}}.": "Achats restaurés : {{count}}.",
  "Restoring...": "Restauration...",
  "Retry": "Réessayer",
  "Root level": "Niveau racine",
  "Runtime category tree": "Arborescence des catégories d'exécution",
  "Save": "Enregistrer",
  "Save and continue": "Enregistrer et continuer",
  "Save balance": "Enregistrer le solde",
  "Save password": "Enregistrer le mot de passe",
  "Saving...": "Enregistrement...",
  "Segments show amounts by category.": "Les segments affichent les montants par catégorie.",
  "Select": "Sélectionner",
  "Select a base currency.": "Sélectionnez une devise de base.",
  "Select a category": "Sélectionnez une catégorie",
  "Select a category and an account.": "Sélectionnez une catégorie et un compte.",
  "Select a category.": "Sélectionnez une catégorie.",
  "Select a currency": "Sélectionnez une devise",
  "Select a date": "Sélectionnez une date",
  "Select a language": "Sélectionnez une langue",
  "Select a subcategory. A parent category cannot be added.": "Sélectionnez une sous-catégorie. Une catégorie parent ne peut pas être ajoutée.",
  "Select account": "Sélectionnez un compte",
  "Select an account.": "Sélectionnez un compte.",
  "Select an icon from the shared catalog": "Sélectionnez une icône dans le catalogue partagé",
  "Select an interface language.": "Sélectionnez une langue d'interface.",
  "Select the interface language and analytics currency.": "Sélectionnez la langue de l'interface et la devise d'analyse.",
  "Send a request": "Envoyer une demande",
  "Send email": "Envoyer un e-mail",
  "Send request": "Envoyer la demande",
  "Sending...": "Envoi...",
  "Show": "Afficher",
  "Show password": "Afficher le mot de passe",
  "Settings": "Paramètres",
  "Sign in": "Se connecter",
  "Signing in with Google...": "Connexion avec Google...",
  "Signing in...": "Connexion...",
  "Some store products are not available yet: {{products}}.": "Certains produits du magasin ne sont pas encore disponibles : {{products}}.",
  "Spending across all accounts": "Dépenses sur tous les comptes",
  "Start date": "Date de début",
  "Step {{current}} of 2: {{screen}}": "Étape {{current}} sur 2 : {{screen}}",
  "Store products are available only on iOS and Android.": "Les produits du magasin sont disponibles uniquement sur iOS et Android.",
  "Store products are not available yet. Please check App Store or Google Play product setup.": "Les produits du magasin ne sont pas encore disponibles. Veuillez vérifier la configuration du produit App Store ou Google Play.",
  "Store purchases are available only on iOS and Android.": "Les achats en magasin sont disponibles uniquement sur iOS et Android.",
  "Store purchases require iOS or Android": "Les achats en magasin nécessitent iOS ou Android",
  "Store transaction is missing orderId.": "La transaction en magasin ne contient pas d'ID de commande.",
  "Store transaction is missing originalTransactionId.": "La transaction du magasin ne contient pas l'originalTransactionId.",
  "Store transaction is missing packageName.": "Il manque packageName dans la transaction du magasin.",
  "Store transaction is missing purchaseToken.": "Il manque le jeton d'achat dans la transaction en magasin.",
  "Store transaction is missing signed payload.": "La transaction du magasin ne contient pas de charge utile signée.",
  "Store transaction is missing transactionId.": "La transaction du magasin ne contient pas d'ID de transaction.",
  "Subcategories": "Sous-catégories",
  "Subject": "Objet",
  "Subscribe": "S'abonner",
  "Subscription": "Abonnement",
  "Subscription management": "Gestion des abonnements",
  "Subscriptions": "Abonnements",
  "Support": "Assistance",
  "Tap the icon to select": "Appuyez sur l'icône pour sélectionner",
  "Telegram username": "Nom d'utilisateur Telegram",
  "The account will be deleted.": "Le compte sera supprimé.",
  "The base currency cannot be changed because budgets or transactions already exist.": "La devise de base ne peut pas être modifiée car des budgets ou des transactions existent déjà.",
  "The budget category list for this month is empty.": "La liste des catégories budgétaires pour ce mois est vide.",
  "The category will be removed from this month's budget.": "La catégorie sera supprimée du budget de ce mois-ci.",
  "The payment is overdue. Premium access remains available through the grace-period date above.": "Le paiement est en retard. L’accès Premium reste disponible jusqu’à la date de période de grâce ci-dessus.",
  "The purchase was not confirmed by the store. Try again.": "L'achat n'a pas été confirmé par le magasin. Essayer à nouveau.",
  "The server did not respond in time. Try again.": "Le serveur n'a pas répondu à temps. Essayer à nouveau.",
  "The transaction will be permanently deleted.": "La transaction sera définitivement supprimée.",
  "The verified purchase is not active.": "L'achat vérifié n'est pas actif.",
  "This account has no password. Password setup is handled separately.": "Ce compte n'a pas de mot de passe. La configuration du mot de passe est gérée séparément.",
  "This purchase has already been received. Tap Restore purchases to restore the subscription.": "Cet achat a déjà été reçu. Appuyez sur Restaurer les achats pour restaurer l'abonnement.",
  "This purchase is linked to another MoneyDrive account. Sign in to the linked account or use a different App Store Sandbox account.": "Cet achat est lié à un autre compte MoneyDrive. Connectez-vous au compte associé ou utilisez un autre compte App Store Sandbox.",
  "This purchase period has already expired.": "Cette période d'achat est déjà expirée.",
  "This purchase period has expired. Select a current subscription.": "Cette période d'achat est expirée. Sélectionnez un abonnement en cours.",
  "This takes less than a minute.": "Cela prend moins d'une minute.",
  "To goal: {{amount}}": "Pour atteindre l'objectif : {{amount}}",
  "To renew with LiqPay, open the web version and complete a new checkout.": "Pour renouveler avec LiqPay, ouvrez la version Web et effectuez une nouvelle commande.",
  "Top categories by spending ({{currency}})": "Principales catégories de dépenses ({{currency}})",
  "Total": "Total",
  "Total balance": "Solde total",
  "Transactions": "Transactions",
  "Transfer": "Transfert",
  "Type": "Type",
  "Type: {{type}}": "Type : {{type}}",
  "Unable to add the budget category (HTTP {{status}}).": "Impossible d'ajouter la catégorie budgétaire (HTTP {{status}}).",
  "Unable to change password.": "Impossible de changer le mot de passe.",
  "Unable to connect to the server.": "Impossible de se connecter au serveur.",
  "Unable to create budget (HTTP {{status}}).": "Impossible de créer le budget (HTTP {{status}}).",
  "Unable to create the account.": "Impossible de créer le compte.",
  "Unable to create the category (HTTP {{status}}).": "Impossible de créer la catégorie (HTTP {{status}}).",
  "Unable to delete the category (HTTP {{status}}).": "Impossible de supprimer la catégorie (HTTP {{status}}).",
  "Unable to delete the transaction.": "Impossible de supprimer la transaction.",
  "Unable to load accounts (HTTP {{status}}).": "Impossible de charger les comptes (HTTP {{status}}).",
  "Unable to load accounts.": "Impossible de charger les comptes.",
  "Unable to load budget (HTTP {{status}}).": "Impossible de charger le budget (HTTP {{status}}).",
  "Unable to load budgets (HTTP {{status}}).": "Impossible de charger les budgets (HTTP {{status}}).",
  "Unable to load categories.": "Impossible de charger les catégories.",
  "Unable to load category icons (HTTP {{status}}).": "Impossible de charger les icônes de catégorie (HTTP {{status}}).",
  "Unable to load category icons.": "Impossible de charger les icônes de catégorie.",
  "Unable to load dashboard (HTTP {{status}}).": "Impossible de charger le tableau de bord (HTTP {{status}}).",
  "Unable to load frequent categories.": "Impossible de charger les catégories fréquentes.",
  "Unable to load settings.": "Impossible de charger les paramètres.",
  "Unable to load subscription products.": "Impossible de charger les produits d'abonnement.",
  "Unable to load subscription status.": "Impossible de charger le statut de l'abonnement.",
  "Unable to load transactions.": "Impossible de charger les transactions.",
  "Unable to open onboarding.": "Impossible d'ouvrir la configuration initiale.",
  "Unable to open the account.": "Impossible d'ouvrir le compte.",
  "Unable to open the category for editing.": "Impossible d'ouvrir la catégorie pour la modifier.",
  "Unable to open the category.": "Impossible d'ouvrir la catégorie.",
  "Unable to open the transaction.": "Impossible d'ouvrir la transaction.",
  "Unable to prepare the expense form.": "Impossible de préparer le formulaire de dépenses.",
  "Unable to remove the budget category (HTTP {{status}}).": "Impossible de supprimer la catégorie budgétaire (HTTP {{status}}).",
  "Unable to resend the email.": "Impossible de renvoyer l'e-mail.",
  "Unable to save the profile.": "Impossible d'enregistrer le profil.",
  "Unable to save the transaction.": "Impossible d'enregistrer la transaction.",
  "Unable to send request.": "Impossible d'envoyer la demande.",
  "Unable to update balance.": "Impossible de mettre à jour le solde.",
  "Unable to update the account.": "Impossible de mettre à jour le compte.",
  "Unable to update the budget category (HTTP {{status}}).": "Impossible de mettre à jour la catégorie budgétaire (HTTP {{status}}).",
  "Unable to update the category (HTTP {{status}}).": "Impossible de mettre à jour la catégorie (HTTP {{status}}).",
  "Uncategorized": "Non classé",
  "Until {{date}}": "Jusqu'à {{date}}",
  "Untitled": "Sans titre",
  "Unverified": "Non vérifié",
  "Update": "Mise à jour",
  "Verification": "Vérification",
  "Verification token": "Jeton de vérification",
  "Verified": "Vérifié",
  "Verify email": "Vérifier l'e-mail",
  "Verify with token": "Vérifier avec un jeton",
  "Verifying email...": "Vérification de l'e-mail...",
  "View all": "Voir tout",
  "View budgets": "Voir les budgets",
  "We sent a verification email to {{email}}.": "Nous avons envoyé un e-mail de vérification à {{email}}.",
  "We usually respond within one business day.": "Nous répondons généralement dans un délai d'un jour ouvrable.",
  "Your account and data are safe. Buy a new subscription to restore business features.": "Votre compte et vos données sont en sécurité. Achetez un nouvel abonnement pour restaurer les fonctionnalités professionnelles.",
  "Your email": "Votre email",
  "Your request has been sent to our support team.": "Votre demande a été envoyée à notre équipe d'assistance.",
  "Your session has expired. Sign in again.": "Votre session a expiré. Connectez-vous à nouveau.",
  "categories": "catégories",
  "the specified address": "l'adresse indiquée",
  "{{amount}} remaining": "{{amount}} restant",
  "{{percent}}% of plan": "{{percent}} % du plan",
  "‹ Back": "‹ Retour",
  "Account \"{{name}}\" will be deleted.": "Le compte « {{name}} » sera supprimé.",
  "Category \"{{name}}\" will be deleted.": "La catégorie \"{{name}}\" sera supprimée.",
  "Account deleted": "Compte supprimé",
  "Accounts, categories, budgets, transactions, transfers, settings, and access tokens will be deleted.": "Les comptes, catégories, budgets, transactions, virements, réglages et jetons d’accès seront supprimés.",
  "Apple did not return credentials required for account deletion.": "Apple n’a pas renvoyé les identifiants requis pour supprimer le compte.",
  "Apple Sign-In is not available on this device.": "La connexion avec Apple n’est pas disponible sur cet appareil.",
  "Apple Sign-In was cancelled.": "La connexion avec Apple a été annulée.",
  "Choose a verification method. Sign-in will open after you press the final delete button.": "Choisissez une méthode de vérification. La connexion s’ouvrira après avoir appuyé sur le bouton final de suppression.",
  "Confirm your identity": "Confirmez votre identité",
  "Continue with Apple and delete account": "Continuer avec Apple et supprimer le compte",
  "Continue with Google and delete account": "Continuer avec Google et supprimer le compte",
  "Danger zone": "Zone dangereuse",
  "Delete MoneyDrive account": "Supprimer le compte MoneyDrive",
  "Delete MoneyDrive account permanently": "Supprimer définitivement le compte MoneyDrive",
  "Deleting account...": "Suppression du compte...",
  "Deleting your account permanently removes your profile and financial data. This action cannot be undone.": "La suppression définitive de votre compte efface votre profil et vos données financières. Cette action est irréversible.",
  "Deleting MoneyDrive does not cancel App Store billing. Cancel the subscription in Apple settings if you no longer want it.": "Supprimer MoneyDrive n’annule pas la facturation de l’App Store. Annulez l’abonnement dans les réglages Apple si vous n’en voulez plus.",
  "Google Sign-In": "Connexion avec Google",
  "Manage Apple subscription": "Gérer l’abonnement Apple",
  "Sign in with Apple": "Se connecter avec Apple",
  "Type DELETE to confirm": "Saisissez DELETE pour confirmer",
  "Unable to delete the account.": "Impossible de supprimer le compte.",
  "Unable to open subscription management.": "Impossible d’ouvrir la gestion des abonnements.",
  Legal: "Mentions légales",
  "Privacy Policy": "Politique de confidentialité",
  "Unable to open the Privacy Policy.": "Impossible d’ouvrir la Politique de confidentialité.",
} as const;

export default fr;
