const it = {
  "+{{amount}} above plan 🚀": "+{{amount}} sopra il piano 🚀",
  "30 days": "30 giorni",
  "A subcategory cannot contain nested subcategories.": "Una sottocategoria non può contenere sottocategorie nidificate.",
  "Access denied.": "Accesso negato.",
  "Access until: {{date}}": "Accesso fino al: {{date}}",
  "Account": "Conto",
  "Account settings": "Impostazioni del conto",
  "Account unavailable.": "Conto non disponibile.",
  "Account: {{name}}": "Conto: {{name}}",
  "Accounts": "Conti",
  "Across all accounts": "Su tutti i conti",
  "Actual": "Reale",
  "Actual expense": "Spesa effettiva",
  "Actual income": "Entrate effettive",
  "Add": "Aggiungi",
  "Add account": "Aggiungi conto",
  "Add budget": "Aggiungi budget",
  "Add category": "Aggiungi categoria",
  "Add details": "Aggiungi dettagli",
  "Add subcategory": "Aggiungi sottocategoria",
  "Add to budget": "Aggiungi al budget",
  "Add transaction": "Aggiungi transazione",
  "Add your first expense": "Aggiungi la tua prima spesa",
  "Adding...": "Aggiunta...",
  "All accounts": "Tutti i conti",
  "All categories": "Tutte le categorie",
  "All recorded income categories": "Tutte le categorie di entrate registrate",
  "All steps completed": "Tutti i passaggi sono stati completati",
  "All time": "Intero periodo",
  "All types": "Tutti i tipi",
  "Amount": "Importo",
  "Analytics period": "Periodo di analisi",
  "Another store purchase is already in progress.": "Un altro acquisto in negozio è già in corso.",
  "Apple did not return an identity token.": "Apple non ha restituito un token di identità.",
  "App Store saved {{actualProductId}} instead of {{requestedProductId}}. Check the current plan in App Store subscription settings.": "App Store ha salvato {{actualProductId}} invece di {{requestedProductId}}. Controlla il piano attuale nelle impostazioni di abbonamento dell'App Store.",
  "Auto-renew off": "Rinnovo automatico disattivato",
  "Auto-renewal is off. Premium access remains available through the date above.": "Il rinnovo automatico è disattivato. L'accesso Premium rimane disponibile fino alla data sopra indicata.",
  "Available plans": "Piani disponibili",
  "Back": "Indietro",
  "Back to sign in": "Torna all'accesso",
  "Balance": "Saldo",
  "Balance update timed out. Check that the backend API is available.": "L'aggiornamento del saldo è scaduto. Verifica che l'API di backend sia disponibile.",
  "Base currency": "Valuta di base",
  "Budget": "Budget",
  "Budget category": "Categoria di budget",
  "Budget changes and category editing will be added after the backend API is extended.": "Le modifiche al budget e la modifica delle categorie verranno aggiunte dopo l'estensione dell'API di backend.",
  "Budget details": "Dettagli del budget",
  "Budget not found.": "Budget non trovato.",
  "Budget progress": "Avanzamento del budget",
  "Budgets": "Budget",
  "C": "C",
  "Cancel": "Annulla",
  "Categories": "Categorie",
  "Category": "Categoria",
  "Category disabled": "Categoria disabilitata",
  "Category enabled": "Categoria abilitata",
  "Category not found in the budget.": "Categoria non trovata nel budget.",
  "Category unavailable.": "Categoria non disponibile.",
  "Category \"{{name}}\" will become a group. It can no longer be selected in new transactions and budgets. Existing records will remain unchanged.": "La categoria \"{{name}}\" diventerà un gruppo. Non potrà più essere selezionata nelle nuove transazioni e nei budget. I dati esistenti rimarranno invariati.",
  "Category will become a group": "La categoria diventerà un gruppo",
  "Change balance": "Modifica saldo",
  "Change password": "Modifica password",
  "Check your email": "Controlla la tua email",
  "Checking authentication...": "Verifica dell'autenticazione in corso...",
  "Choose an App Store or Google Play product below.": "Scegli un prodotto App Store o Google Play di seguito.",
  "Comment": "Commento",
  "Complete all password fields.": "Completa tutti i campi della password.",
  "Confirm new password": "Conferma la nuova password",
  "Confirm password": "Conferma password",
  "Contact support": "Contatta l'assistenza",
  "Continue": "Continua",
  "Create": "Crea",
  "Create account": "Crea un account",
  "Creating...": "Creazione...",
  "Currency": "Valuta",
  "Current password": "Password attuale",
  "Current plan": "Piano attuale",
  "Custom": "Personalizzato",
  "DONE": "FATTO",
  "Dashboard": "Pannello di controllo",
  "Date": "Data",
  "Date YYYY-MM-DD": "Data AAAA-MM-GG",
  "Delete": "Elimina",
  "Delete account?": "Eliminare il conto?",
  "Delete category": "Elimina categoria",
  "Delete category?": "Eliminare la categoria?",
  "Delete transaction": "Elimina transazione",
  "Delete transaction?": "Eliminare la transazione?",
  "Deleting...": "Eliminazione...",
  "Description": "Descrizione",
  "Disabled": "Disabilitato",
  "Edit": "Modifica",
  "Edit account": "Modifica conto",
  "Edit transaction": "Modifica transazione",
  "Editing": "Modifica",
  "Email": "E-mail",
  "Email resent. Retry in {{seconds}} seconds.": "E-mail inviata di nuovo. Riprova tra {{seconds}} secondi.",
  "Email sent. You can retry in about {{seconds}} seconds.": "E-mail inviata. Puoi riprovare tra circa {{seconds}} secondi.",
  "Email verification": "Verifica e-mail",
  "Email verified. You can now sign in.": "E-mail verificata. Ora puoi accedere.",
  "Email was not sent. Try again in {{seconds}} seconds.": "L'e-mail non è stata inviata. Riprova tra {{seconds}} secondi.",
  "End date": "Data di fine",
  "Enter a category name.": "Inserisci il nome di una categoria.",
  "Enter a date.": "Inserisci una data.",
  "Enter a message.": "Inserisci un messaggio.",
  "Enter a new password.": "Inserisci una nuova password.",
  "Enter a subject.": "Inserisci un oggetto.",
  "Enter a valid amount.": "Inserisci un importo valido.",
  "Enter a valid balance.": "Inserisci un saldo valido.",
  "Enter a valid email address.": "Inserisci un indirizzo email valido.",
  "Enter a valid planned amount greater than 0.": "Inserisci un importo pianificato valido maggiore di 0.",
  "Enter an account name.": "Inserisci il nome del conto.",
  "Enter an amount greater than zero.": "Inserisci un importo maggiore di zero.",
  "Enter your email": "Inserisci la tua email",
  "Enter your email, name, and password.": "Inserisci la tua email, nome e password.",
  "Enter your email.": "Inserisci la tua email.",
  "Enter your name": "Inserisci il tuo nome",
  "Expense": "Spesa",
  "Expense categories": "Categorie di spesa",
  "Expense categories are not available yet.": "Le categorie di spesa non sono ancora disponibili.",
  "Expense not submitted: complete the required fields.": "Spesa non inviata: completare i campi obbligatori.",
  "Expenses": "Spese",
  "Expenses and income": "Spese e entrate",
  "Expenses this period": "Spese nel periodo",
  "Fill password": "Compila la password",
  "Forgot password?": "Hai dimenticato la password?",
  "Free": "Gratuito",
  "From {{date}}": "Da {{date}}",
  "Go to sign in": "Vai ad accedere",
  "Goal reached! 🎉": "Obiettivo raggiunto! 🎉",
  "Google Sign-In is not configured for this build.": "L'accesso con Google non è configurato per questa build.",
  "Google did not return an ID token.": "Google non ha restituito un token ID.",
  "Group": "Gruppo",
  "Hide": "Nascondi",
  "Hide form": "Nascondi modulo",
  "Hide password": "Nascondi la password",
  "Home": "Home",
  "I have a token": "Ho un token",
  "Icon": "Icona",
  "If the account exists, an email has been sent.": "Se l'account esiste, è stata inviata un'e-mail.",
  "If the account exists, an email has been sent. Retry in {{seconds}} seconds.": "Se l'account esiste, è stata inviata un'e-mail. Riprova tra {{seconds}} secondi.",
  "If the email contains a production link, paste the token manually for local testing.": "Se l'e-mail contiene un collegamento di produzione, incolla manualmente il token per il test locale.",
  "Income": "Entrate",
  "Income categories": "Categorie di entrate",
  "Income categories are not available yet.": "Le categorie di entrate non sono ancora disponibili.",
  "Income this period": "Entrate nel periodo",
  "Initial setup": "Configurazione iniziale",
  "Interface language": "Lingua dell'interfaccia",
  "Invalid accounts response format.": "Formato di risposta dei conti non valido.",
  "Invalid budget response format.": "Formato della risposta al budget non valido.",
  "Keep an eye on all of your balances.": "Tieni d'occhio tutti i tuoi saldi.",
  "Language and base currency": "Lingua e valuta base",
  "LiqPay subscription can be cancelled only in the web version of the app.": "L'abbonamento LiqPay può essere annullato solo nella versione web dell'app.",
  "Loading accounts...": "Caricamento conti...",
  "Loading budget...": "Caricamento budget...",
  "Loading budgets...": "Caricamento budget...",
  "Loading categories...": "Caricamento categorie...",
  "Loading dashboard...": "Caricamento dashboard...",
  "Loading icons...": "Caricamento icone...",
  "Loading onboarding...": "Caricamento onboarding...",
  "Loading settings...": "Caricamento impostazioni...",
  "Loading store products...": "Caricamento dei prodotti del negozio...",
  "Loading subscription status...": "Caricamento stato abbonamento...",
  "Loading...": "Caricamento...",
  "Log in": "Accedi",
  "Login with Google": "Accedi con Google",
  "Logout": "Esci",
  "Manage on web": "Gestisci sul web",
  "Manage premium access": "Gestisci l'accesso premium",
  "Manage subscription": "Gestisci l'abbonamento",
  "Maximum category depth is 2 levels": "La profondità massima della categoria è di 2 livelli",
  "Maximum category depth is 2 levels.": "La profondità massima della categoria è di 2 livelli.",
  "Message": "Messaggio",
  "Missing Android subscription offer token for selected product.": "Token dell'offerta di abbonamento Android mancante per il prodotto selezionato.",
  "Missing account ID.": "ID del conto mancante.",
  "Missing budgetId.": "ID budget mancante.",
  "Missing reset token.": "Token di ripristino mancante.",
  "MoneyDrive.me": "MoneyDrive.me",
  "Month": "Mese",
  "More": "Di più",
  "More service sections": "Più sezioni di servizio",
  "Most frequent": "Più frequente",
  "Name": "Nome",
  "New account": "Nuovo conto",
  "New balance": "Nuovo saldo",
  "New category": "Nuova categoria",
  "New email awaiting verification: {{email}}": "Nuova email in attesa di verifica: {{email}}",
  "New password": "Nuova password",
  "New planned amount": "Nuovo importo previsto",
  "No App Store Sandbox account is connected on this device. Add a sandbox tester in Settings > App Store > Sandbox Account.": "Nessun account Sandbox dell'App Store è collegato a questo dispositivo. Aggiungi un tester sandbox in Impostazioni > App Store > Account Sandbox.",
  "No account": "Nessun conto",
  "No account data.": "Nessun dato del conto.",
  "No accounts.": "Nessun conto.",
  "No active purchases found.": "Nessun acquisto attivo trovato.",
  "No active store source": "Nessun provider dello store attivo",
  "No budget has been created for the selected month.": "Nessun budget è stato creato per il mese selezionato.",
  "No budgets for the selected period.": "Nessun budget per il periodo selezionato.",
  "No budgets found yet.": "Nessun budget ancora trovato.",
  "No categories available to add.": "Nessuna categoria disponibile da aggiungere.",
  "No categories found for the selected type.": "Nessuna categoria trovata per il tipo selezionato.",
  "No categories found.": "Nessuna categoria trovata.",
  "No categories.": "Nessuna categoria.",
  "No data for the selected period.": "Nessun dato per il periodo selezionato.",
  "No data.": "Nessun dato.",
  "No external management action is available.": "Non è disponibile alcuna azione di gestione esterna.",
  "No period selected": "Nessun periodo selezionato",
  "No transaction data.": "Nessun dato di transazione.",
  "No transactions yet.": "Nessuna transazione ancora.",
  "Not enough data to add the category.": "Dati insufficienti per aggiungere la categoria.",
  "Not set": "Non impostato",
  "Note": "Nota",
  "Open": "Apri",
  "Open App Store account settings and choose Subscriptions.": "Apri le impostazioni dell'account App Store e scegli Abbonamenti.",
  "Open the subscription provider account settings to manage this plan.": "Apri le impostazioni dell'account del fornitore dell'abbonamento per gestire questo piano.",
  "Overspent by {{amount}}": "Budget superato di {{amount}}",
  "Parent: {{name}}": "Categoria principale: {{name}}",
  "Password": "Password",
  "Password changed.": "La password è cambiata.",
  "Password recovery": "Recupero password",
  "Password updated. You can now sign in.": "Password aggiornata. Ora puoi accedere.",
  "Passwords do not match.": "Le password non corrispondono.",
  "Paste the verification token.": "Incolla il token di verifica.",
  "Period: {{period}}": "Periodo: {{period}}",
  "Plan ({{currency}})": "Piano ({{currency}})",
  "Plan / actual / remaining by category": "Piano/effettivo/rimanente per categoria",
  "Plan {{plan}} · Actual {{actual}}": "Piano {{plan}} · {{actual}} effettivo",
  "Plans and billing": "Piani e fatturazione",
  "Planned amount ({{currency}})": "Importo pianificato ({{currency}})",
  "Planned expense": "Spesa pianificata",
  "Planned income": "Entrate pianificate",
  "Popular categories": "Categorie popolari",
  "Premium": "Premium",
  "Premium is active.": "Premium è attivo.",
  "Premium is active. The plan change will take effect on the next App Store renewal.": "Premium è attivo. La modifica del piano entrerà in vigore al prossimo rinnovo dell'App Store.",
  "Processing...": "Elaborazione...",
  "Product temporarily unavailable.": "Prodotto momentaneamente non disponibile.",
  "Product: {{product}}": "Prodotto: {{product}}",
  "Products for {{platform}}": "Prodotti per {{platform}}",
  "Profile": "Profilo",
  "Profile and security": "Profilo e sicurezza",
  "Profile saved.": "Profilo salvato.",
  "Profile, language, and security": "Profilo, lingua e sicurezza",
  "Purchase not confirmed. Try again.": "Acquisto non confermato. Riprova.",
  "Recent transactions": "Transazioni recenti",
  "Registration": "Registrazione",
  "Remaining": "Rimanente",
  "Renewal canceled": "Rinnovo annullato",
  "Request failed (HTTP {{status}}).": "Richiesta non riuscita (HTTP {{status}}).",
  "Resend email": "Invia nuovamente l'e-mail",
  "Restore purchases": "Ripristina gli acquisti",
  "Restored purchases: {{count}}.": "Acquisti ripristinati: {{count}}.",
  "Restoring...": "Ripristino...",
  "Retry": "Riprova",
  "Root level": "Livello principale",
  "Runtime category tree": "Struttura delle categorie runtime",
  "Save": "Salva",
  "Save and continue": "Salva e continua",
  "Save balance": "Salva saldo",
  "Save password": "Salva password",
  "Saving...": "Salvataggio...",
  "Segments show amounts by category.": "I segmenti mostrano gli importi per categoria.",
  "Select": "Seleziona",
  "Select a base currency.": "Seleziona una valuta di base.",
  "Select a category": "Seleziona una categoria",
  "Select a category and an account.": "Seleziona una categoria e un conto.",
  "Select a category.": "Seleziona una categoria.",
  "Select a currency": "Seleziona una valuta",
  "Select a date": "Seleziona una data",
  "Select a language": "Seleziona una lingua",
  "Select a subcategory. A parent category cannot be added.": "Seleziona una sottocategoria. Non è possibile aggiungere una categoria principale.",
  "Select account": "Seleziona conto",
  "Select an account.": "Seleziona un conto.",
  "Select an icon from the shared catalog": "Seleziona un'icona dal catalogo condiviso",
  "Select an interface language.": "Seleziona una lingua di interfaccia.",
  "Select the interface language and analytics currency.": "Seleziona la lingua dell'interfaccia e la valuta dell'analisi.",
  "Send a request": "Invia una richiesta",
  "Send email": "Invia e-mail",
  "Send request": "Invia richiesta",
  "Sending...": "Invio...",
  "Show": "Mostra",
  "Show password": "Mostra password",
  "Settings": "Impostazioni",
  "Sign in": "Accedi",
  "Signing in with Google...": "Accesso con Google...",
  "Signing in...": "Accesso...",
  "Some store products are not available yet: {{products}}.": "Alcuni prodotti del negozio non sono ancora disponibili: {{products}}.",
  "Spending across all accounts": "Spese su tutti i conti",
  "Start date": "Data di inizio",
  "Step {{current}} of 2: {{screen}}": "Passaggio {{current}} di 2: {{screen}}",
  "Store products are available only on iOS and Android.": "I prodotti dello Store sono disponibili solo su iOS e Android.",
  "Store products are not available yet. Please check App Store or Google Play product setup.": "I prodotti del negozio non sono ancora disponibili. Controlla la configurazione del prodotto sull'App Store o su Google Play.",
  "Store purchases are available only on iOS and Android.": "Gli acquisti in negozio sono disponibili solo su iOS e Android.",
  "Store purchases require iOS or Android": "Gli acquisti in negozio richiedono iOS o Android",
  "Store transaction is missing orderId.": "Nella transazione del negozio manca l'ID ordine.",
  "Store transaction is missing originalTransactionId.": "Nella transazione del negozio manca l'originalTransactionId.",
  "Store transaction is missing packageName.": "Nella transazione del negozio manca packageName.",
  "Store transaction is missing purchaseToken.": "Nella transazione del negozio manca il token di acquisto.",
  "Store transaction is missing signed payload.": "Nella transazione del negozio manca il payload firmato.",
  "Store transaction is missing transactionId.": "Nella transazione del negozio manca l'ID transazione.",
  "Subcategories": "Sottocategorie",
  "Subject": "Oggetto",
  "Subscribe": "Abbonati",
  "Subscription": "Abbonamento",
  "Subscription management": "Gestione degli abbonamenti",
  "Subscriptions": "Abbonamenti",
  "Support": "Supporto",
  "Tap the icon to select": "Tocca l'icona per selezionare",
  "Telegram username": "Nome utente di Telegram",
  "The account will be deleted.": "Il conto verrà eliminato.",
  "The base currency cannot be changed because budgets or transactions already exist.": "La valuta di base non può essere modificata perché esistono già budget o transazioni.",
  "The budget category list for this month is empty.": "L'elenco delle categorie di budget per questo mese è vuoto.",
  "The category will be removed from this month's budget.": "La categoria verrà rimossa dal budget di questo mese.",
  "The payment is overdue. Premium access remains available through the grace-period date above.": "Il pagamento è in ritardo. L'accesso Premium rimane disponibile fino alla data del periodo di grazia sopra indicata.",
  "The purchase was not confirmed by the store. Try again.": "L'acquisto non è stato confermato dal negozio. Riprova.",
  "The server did not respond in time. Try again.": "Il server non ha risposto in tempo. Riprova.",
  "The transaction will be permanently deleted.": "La transazione verrà eliminata definitivamente.",
  "The verified purchase is not active.": "L'acquisto verificato non è attivo.",
  "This account has no password. Password setup is handled separately.": "Questo account non ha password. L'impostazione della password viene gestita separatamente.",
  "This purchase has already been received. Tap Restore purchases to restore the subscription.": "Questo acquisto è già stato ricevuto. Tocca Ripristina acquisti per ripristinare l'abbonamento.",
  "This purchase is linked to another MoneyDrive account. Sign in to the linked account or use a different App Store Sandbox account.": "Questo acquisto è collegato a un altro account MoneyDrive. Accedi all'account collegato o utilizza un altro account Sandbox dell'App Store.",
  "This purchase period has already expired.": "Questo periodo di acquisto è già scaduto.",
  "This purchase period has expired. Select a current subscription.": "Il periodo di acquisto è scaduto. Seleziona un abbonamento corrente.",
  "This takes less than a minute.": "L'operazione richiede meno di un minuto.",
  "To goal: {{amount}}": "All'obiettivo: {{amount}}",
  "To renew with LiqPay, open the web version and complete a new checkout.": "Per rinnovare con LiqPay, apri la versione web e completa un nuovo checkout.",
  "Top categories by spending ({{currency}})": "Principali categorie per spesa ({{currency}})",
  "Total": "Totale",
  "Total balance": "Saldo totale",
  "Transactions": "Transazioni",
  "Transfer": "Trasferimento",
  "Type": "Tipo",
  "Type: {{type}}": "Tipo: {{type}}",
  "Unable to add the budget category (HTTP {{status}}).": "Impossibile aggiungere la categoria budget (HTTP {{status}}).",
  "Unable to change password.": "Impossibile modificare la password.",
  "Unable to connect to the server.": "Impossibile connettersi al server.",
  "Unable to create budget (HTTP {{status}}).": "Impossibile creare il budget (HTTP {{status}}).",
  "Unable to create the account.": "Impossibile creare il conto.",
  "Unable to create the category (HTTP {{status}}).": "Impossibile creare la categoria (HTTP {{status}}).",
  "Unable to delete the account.": "Impossibile eliminare il conto.",
  "Unable to delete the category (HTTP {{status}}).": "Impossibile eliminare la categoria (HTTP {{status}}).",
  "Unable to delete the transaction.": "Impossibile eliminare la transazione.",
  "Unable to load accounts (HTTP {{status}}).": "Impossibile caricare i conti (HTTP {{status}}).",
  "Unable to load accounts.": "Impossibile caricare i conti.",
  "Unable to load budget (HTTP {{status}}).": "Impossibile caricare il budget (HTTP {{status}}).",
  "Unable to load budgets (HTTP {{status}}).": "Impossibile caricare i budget (HTTP {{status}}).",
  "Unable to load categories.": "Impossibile caricare le categorie.",
  "Unable to load category icons (HTTP {{status}}).": "Impossibile caricare le icone delle categorie (HTTP {{status}}).",
  "Unable to load category icons.": "Impossibile caricare le icone delle categorie.",
  "Unable to load dashboard (HTTP {{status}}).": "Impossibile caricare il dashboard (HTTP {{status}}).",
  "Unable to load frequent categories.": "Impossibile caricare le categorie frequenti.",
  "Unable to load settings.": "Impossibile caricare le impostazioni.",
  "Unable to load subscription products.": "Impossibile caricare i prodotti in abbonamento.",
  "Unable to load subscription status.": "Impossibile caricare lo stato dell'abbonamento.",
  "Unable to load transactions.": "Impossibile caricare le transazioni.",
  "Unable to open onboarding.": "Impossibile aprire l'onboarding.",
  "Unable to open the account.": "Impossibile aprire il conto.",
  "Unable to open the category for editing.": "Impossibile aprire la categoria per la modifica.",
  "Unable to open the category.": "Impossibile aprire la categoria.",
  "Unable to open the transaction.": "Impossibile aprire la transazione.",
  "Unable to prepare the expense form.": "Impossibile preparare il modulo delle spese.",
  "Unable to remove the budget category (HTTP {{status}}).": "Impossibile rimuovere la categoria budget (HTTP {{status}}).",
  "Unable to resend the email.": "Impossibile inviare nuovamente l'e-mail.",
  "Unable to save the profile.": "Impossibile salvare il profilo.",
  "Unable to save the transaction.": "Impossibile salvare la transazione.",
  "Unable to send request.": "Impossibile inviare la richiesta.",
  "Unable to update balance.": "Impossibile aggiornare il saldo.",
  "Unable to update the account.": "Impossibile aggiornare il conto.",
  "Unable to update the budget category (HTTP {{status}}).": "Impossibile aggiornare la categoria del budget (HTTP {{status}}).",
  "Unable to update the category (HTTP {{status}}).": "Impossibile aggiornare la categoria (HTTP {{status}}).",
  "Uncategorized": "Senza categoria",
  "Until {{date}}": "Fino a {{date}}",
  "Untitled": "Senza titolo",
  "Unverified": "Non verificato",
  "Update": "Aggiorna",
  "Verification": "Verifica",
  "Verification token": "Token di verifica",
  "Verified": "Verificato",
  "Verify email": "Verifica l'e-mail",
  "Verify with token": "Verifica con token",
  "Verifying email...": "Verifica e-mail...",
  "View all": "Visualizza tutto",
  "View budgets": "Visualizza i budget",
  "We sent a verification email to {{email}}.": "Abbiamo inviato un'e-mail di verifica a {{email}}.",
  "We usually respond within one business day.": "Di solito rispondiamo entro un giorno lavorativo.",
  "Your account and data are safe. Buy a new subscription to restore business features.": "Il tuo account e i tuoi dati sono al sicuro. Acquista un nuovo abbonamento per ripristinare le funzionalità aziendali.",
  "Your email": "La tua email",
  "Your request has been sent to our support team.": "La tua richiesta è stata inviata al nostro team di supporto.",
  "Your session has expired. Sign in again.": "La tua sessione è scaduta. Accedi di nuovo.",
  "categories": "categorie",
  "the specified address": "l'indirizzo specificato",
  "{{amount}} remaining": "{{amount}} rimanenti",
  "{{percent}}% of plan": "{{percent}}% del piano",
  "‹ Back": "‹ Indietro",
  "Account \"{{name}}\" will be deleted.": "Il conto \"{{name}}\" verrà eliminato.",
  "Category \"{{name}}\" will be deleted.": "La categoria \"{{name}}\" verrà eliminata.",
  "Account deleted": "Account eliminato",
  "Accounts, categories, budgets, transactions, transfers, settings, and access tokens will be deleted.": "Verranno eliminati conti, categorie, budget, transazioni, trasferimenti, impostazioni e token di accesso.",
  "Apple did not return credentials required for account deletion.": "Apple non ha restituito le credenziali necessarie per eliminare l’account.",
  "Apple Sign-In is not available on this device.": "L’accesso con Apple non è disponibile su questo dispositivo.",
  "Apple Sign-In was cancelled.": "L’accesso con Apple è stato annullato.",
  "Choose a verification method. Sign-in will open after you press the final delete button.": "Scegli un metodo di verifica. L’accesso si aprirà dopo aver premuto il pulsante finale di eliminazione.",
  "Confirm your identity": "Conferma la tua identità",
  "Continue with Apple and delete account": "Continua con Apple ed elimina l’account",
  "Continue with Google and delete account": "Continua con Google ed elimina l’account",
  "Danger zone": "Zona pericolosa",
  "Delete MoneyDrive account": "Elimina account MoneyDrive",
  "Delete MoneyDrive account permanently": "Elimina definitivamente l’account MoneyDrive",
  "Deleting account...": "Eliminazione account...",
  "Deleting your account permanently removes your profile and financial data. This action cannot be undone.": "L’eliminazione definitiva dell’account rimuove il profilo e i dati finanziari. Questa azione non può essere annullata.",
  "Deleting MoneyDrive does not cancel App Store billing. Cancel the subscription in Apple settings if you no longer want it.": "Eliminare MoneyDrive non annulla la fatturazione dell’App Store. Annulla l’abbonamento nelle impostazioni Apple se non lo desideri più.",
  "Google Sign-In": "Accedi con Google",
  "Manage Apple subscription": "Gestisci abbonamento Apple",
  "Sign in with Apple": "Accedi con Apple",
  "Type DELETE to confirm": "Digita DELETE per confermare",
  "Unable to open subscription management.": "Impossibile aprire la gestione degli abbonamenti.",
  Legal: "Note legali",
  "Privacy Policy": "Informativa sulla privacy",
  "Unable to open the Privacy Policy.": "Impossibile aprire l’Informativa sulla privacy.",
} as const;

export default it;
