const jaJP = {
  "+{{amount}} above plan 🚀": "予算を{{amount}}超過 🚀",
  "30 days": "30日",
  "A subcategory cannot contain nested subcategories.": "サブカテゴリには、ネストされたサブカテゴリを含めることはできません。",
  "Access denied.": "アクセスが拒否されました。",
  "Access until: {{date}}": "アクセス期限: {{date}}",
  "Account": "アカウント",
  "Account settings": "アカウント設定",
  "Account unavailable.": "アカウントが利用できません。",
  "Account: {{name}}": "アカウント: {{name}}",
  "Accounts": "アカウント",
  "Across all accounts": "すべてのアカウントにわたって",
  "Actual": "実際の",
  "Actual expense": "実費",
  "Actual income": "実際の収入",
  "Add": "追加",
  "Add account": "アカウントを追加",
  "Add budget": "予算を追加する",
  "Add category": "カテゴリを追加",
  "Add details": "詳細を追加",
  "Add subcategory": "サブカテゴリを追加",
  "Add to budget": "予算に追加",
  "Add transaction": "取引を追加",
  "Add your first expense": "最初の支出を追加",
  "Adding...": "追加中...",
  "All accounts": "すべてのアカウント",
  "All categories": "すべてのカテゴリー",
  "All recorded income categories": "記録されているすべての収入カテゴリー",
  "All steps completed": "すべての手順が完了しました",
  "All time": "ずっと",
  "All types": "全種類",
  "Amount": "金額",
  "Analytics period": "分析期間",
  "Another store purchase is already in progress.": "すでに別の店舗での購入が進行中です。",
  "Apple did not return an identity token.": "Apple は ID トークンを返却しませんでした。",
  "App Store saved {{actualProductId}} instead of {{requestedProductId}}. Check the current plan in App Store subscription settings.": "App Store では、{{requestedProductId}} ではなく {{actualProductId}} が保存されました。 App Store のサブスクリプション設定で現在のプランを確認してください。",
  "Auto-renew off": "自動更新オフ",
  "Auto-renewal is off. Premium access remains available through the date above.": "自動更新はオフになっています。プレミアム アクセスは、上記の日付まで引き続きご利用いただけます。",
  "Available plans": "利用可能なプラン",
  "Back": "戻る",
  "Back to sign in": "サインインに戻る",
  "Balance": "残高",
  "Balance update timed out. Check that the backend API is available.": "残高更新がタイムアウトしました。バックエンド API が利用可能であることを確認します。",
  "Base currency": "基本通貨",
  "Budget": "予算",
  "Budget category": "予算カテゴリー",
  "Budget changes and category editing will be added after the backend API is extended.": "予算の変更とカテゴリの編集は、バックエンド API の拡張後に追加されます。",
  "Budget details": "予算の詳細",
  "Budget not found.": "予算が見つかりません。",
  "Budget progress": "予算の進捗状況",
  "Budgets": "予算",
  "C": "C",
  "Cancel": "キャンセル",
  "Categories": "カテゴリー",
  "Category": "カテゴリ",
  "Category disabled": "カテゴリが無効になっています",
  "Category enabled": "カテゴリが有効になっています",
  "Category not found in the budget.": "カテゴリが予算内に見つかりません。",
  "Category unavailable.": "カテゴリが利用できません。",
  "Category \"{{name}}\" will become a group. It can no longer be selected in new transactions and budgets. Existing records will remain unchanged.": "カテゴリ「{{name}}」がグループとなります。新しいトランザクションや予算では選択できなくなります。既存のレコードは変更されません。",
  "Category will become a group": "カテゴリがグループになります",
  "Change balance": "残高変更",
  "Change password": "パスワードを変更する",
  "Check your email": "メールを確認してください",
  "Checking authentication...": "認証を確認しています...",
  "Choose an App Store or Google Play product below.": "以下から App Store または Google Play 製品を選択してください。",
  "Comment": "コメント",
  "Complete all password fields.": "すべてのパスワードフィールドに入力します。",
  "Confirm new password": "新しいパスワードを確認します",
  "Confirm password": "パスワードを確認",
  "Contact support": "サポートに連絡",
  "Continue": "続ける",
  "Create": "作成",
  "Create account": "アカウントを作成する",
  "Creating...": "作成...",
  "Currency": "通貨",
  "Current password": "現在のパスワード",
  "Current plan": "現在のプラン",
  "Custom": "カスタム",
  "DONE": "終わり",
  "Dashboard": "ダッシュボード",
  "Date": "日付",
  "Date YYYY-MM-DD": "日付 YYYY-MM-DD",
  "Delete": "削除",
  "Delete account?": "アカウントを削除しますか?",
  "Delete category": "カテゴリの削除",
  "Delete category?": "カテゴリを削除しますか?",
  "Delete transaction": "取引を削除",
  "Delete transaction?": "取引を削除しますか?",
  "Deleting...": "削除中...",
  "Description": "説明",
  "Disabled": "無効",
  "Edit": "編集",
  "Edit account": "アカウントの編集",
  "Edit transaction": "取引を編集",
  "Editing": "編集",
  "Email": "メールアドレス",
  "Email resent. Retry in {{seconds}} seconds.": "メールを再送信しました。 {{seconds}} 秒後に再試行してください。",
  "Email sent. You can retry in about {{seconds}} seconds.": "メールが送信されました。約 {{seconds}} 秒後に再試行できます。",
  "Email verification": "メール認証",
  "Email verified. You can now sign in.": "メールアドレスが確認されました。これでサインインできるようになりました。",
  "Email was not sent. Try again in {{seconds}} seconds.": "電子メールは送信されませんでした。 {{seconds}} 秒後にもう一度お試しください。",
  "End date": "終了日",
  "Enter a category name.": "カテゴリ名を入力します。",
  "Enter a date.": "日付を入力します。",
  "Enter a message.": "メッセージを入力してください。",
  "Enter a new password.": "新しいパスワードを入力してください。",
  "Enter a subject.": "件名を入力します。",
  "Enter a valid amount.": "有効な金額を入力してください。",
  "Enter a valid balance.": "有効な残高を入力してください。",
  "Enter a valid email address.": "有効な電子メール アドレスを入力してください。",
  "Enter a valid planned amount greater than 0.": "0 より大きい有効な計画金額を入力します。",
  "Enter an account name.": "アカウント名を入力します。",
  "Enter an amount greater than zero.": "ゼロより大きい金額を入力してください。",
  "Enter your email": "メールアドレスを入力してください",
  "Enter your email, name, and password.": "メールアドレス、名前、パスワードを入力します。",
  "Enter your email.": "メールアドレスを入力してください。",
  "Enter your name": "あなたの名前を入力してください",
  "Expense": "支出",
  "Expense categories": "支出カテゴリ",
  "Expense categories are not available yet.": "支出カテゴリはまだ利用できません。",
  "Expense not submitted: complete the required fields.": "支出は送信されていません: 必須項目を入力してください。",
  "Expenses": "支出",
  "Expenses and income": "支出と収入",
  "Expenses this period": "今期の出費",
  "Fill password": "パスワードを入力してください",
  "Forgot password?": "パスワードをお忘れですか？",
  "Free": "無料",
  "From {{date}}": "{{date}}から",
  "Go to sign in": "サインインに移動",
  "Goal reached! 🎉": "目標達成！ 🎉",
  "Google Sign-In is not configured for this build.": "このビルドでは Google サインインが構成されていません。",
  "Google did not return an ID token.": "Google は ID トークンを返しませんでした。",
  "Group": "グループ",
  "Hide": "隠す",
  "Hide form": "フォームを隠す",
  "Hide password": "パスワードを隠す",
  "Home": "ホーム",
  "I have a token": "トークンを持っています",
  "Icon": "アイコン",
  "If the account exists, an email has been sent.": "アカウントが存在する場合は、電子メールが送信されています。",
  "If the account exists, an email has been sent. Retry in {{seconds}} seconds.": "アカウントが存在する場合は、電子メールが送信されています。 {{seconds}} 秒後に再試行してください。",
  "If the email contains a production link, paste the token manually for local testing.": "電子メールに運用リンクが含まれている場合は、ローカル テストのためにトークンを手動で貼り付けます。",
  "Income": "収入",
  "Income categories": "収入カテゴリ",
  "Income categories are not available yet.": "収入カテゴリはまだ利用できません。",
  "Income this period": "今期の収入",
  "Initial setup": "初期設定",
  "Interface language": "インターフェース言語",
  "Invalid accounts response format.": "アカウントの応答形式が無効です。",
  "Invalid budget response format.": "無効な予算応答形式です。",
  "Keep an eye on all of your balances.": "すべての残高に注目してください。",
  "Language and base currency": "言語と基本通貨",
  "LiqPay subscription can be cancelled only in the web version of the app.": "LiqPay のサブスクリプションは、Web バージョンのアプリでのみキャンセルできます。",
  "Loading accounts...": "アカウントを読み込んでいます...",
  "Loading budget...": "予算を読み込んでいます...",
  "Loading budgets...": "予算を読み込んでいます...",
  "Loading categories...": "カテゴリを読み込んでいます...",
  "Loading dashboard...": "ダッシュボードを読み込んでいます...",
  "Loading icons...": "アイコンを読み込んでいます...",
  "Loading onboarding...": "オンボーディングを読み込んでいます...",
  "Loading settings...": "設定を読み込んでいます...",
  "Loading store products...": "ストア商品を読み込み中...",
  "Loading subscription status...": "サブスクリプション ステータスを読み込んでいます...",
  "Loading...": "読み込み中...",
  "Log in": "ログイン",
  "Login with Google": "Googleでログイン",
  "Logout": "ログアウト",
  "Manage on web": "ウェブ上で管理する",
  "Manage premium access": "プレミアムアクセスを管理する",
  "Manage subscription": "サブスクリプションの管理",
  "Maximum category depth is 2 levels": "カテゴリの最大深さは 2 レベルです",
  "Maximum category depth is 2 levels.": "カテゴリの最大深さは 2 レベルです。",
  "Message": "メッセージ",
  "Missing Android subscription offer token for selected product.": "選択した製品の Android サブスクリプション オファー トークンがありません。",
  "Missing account ID.": "アカウントIDがありません。",
  "Missing budgetId.": "予算IDがありません。",
  "Missing reset token.": "リセットトークンがありません。",
  "MoneyDrive.me": "MoneyDrive.me",
  "Month": "月",
  "More": "もっと",
  "More service sections": "その他のサービスセクション",
  "Most frequent": "最も頻繁に発生する",
  "Name": "名前",
  "New account": "新しいアカウント",
  "New balance": "新しい残高",
  "New category": "新しいカテゴリー",
  "New email awaiting verification: {{email}}": "検証待ちの新しいメール: {{email}}",
  "New password": "新しいパスワード",
  "New planned amount": "新規予定額",
  "No App Store Sandbox account is connected on this device. Add a sandbox tester in Settings > App Store > Sandbox Account.": "このデバイスには App Store サンドボックス アカウントが接続されていません。 [設定] > [App Store] > [サンドボックス アカウント] でサンドボックス テスターを追加します。",
  "No account": "アカウントがありません",
  "No account data.": "アカウントデータがありません。",
  "No accounts.": "アカウントがありません。",
  "No active purchases found.": "アクティブな購入は見つかりませんでした。",
  "No active store source": "アクティブなストア ソースがありません",
  "No budget has been created for the selected month.": "選択した月には予算が作成されていません。",
  "No budgets for the selected period.": "選択した期間には予算がありません。",
  "No budgets found yet.": "予算はまだ見つかりません。",
  "No categories available to add.": "追加できるカテゴリはありません。",
  "No categories found for the selected type.": "選択したタイプのカテゴリが見つかりませんでした。",
  "No categories found.": "カテゴリが見つかりませんでした。",
  "No categories.": "カテゴリはありません。",
  "No data for the selected period.": "選択した期間にはデータがありません。",
  "No data.": "データがありません。",
  "No external management action is available.": "使用できる外部管理アクションはありません。",
  "No period selected": "期間が選択されていません",
  "No transaction data.": "取引データがありません。",
  "No transactions yet.": "まだ取引はありません。",
  "Not enough data to add the category.": "カテゴリを追加するにはデータが不足しています。",
  "Not set": "未設定",
  "Note": "注記",
  "Open": "開く",
  "Open App Store account settings and choose Subscriptions.": "App Store アカウント設定を開き、[サブスクリプション] を選択します。",
  "Open the subscription provider account settings to manage this plan.": "このプランを管理するには、サブスクリプション プロバイダーのアカウント設定を開いてください。",
  "Overspent by {{amount}}": "予算を{{amount}}超過",
  "Parent: {{name}}": "親: {{name}}",
  "Password": "パスワード",
  "Password changed.": "パスワードが変更されました。",
  "Password recovery": "パスワードの回復",
  "Password updated. You can now sign in.": "パスワードが更新されました。これでサインインできるようになりました。",
  "Passwords do not match.": "パスワードが一致しません。",
  "Paste the verification token.": "検証トークンを貼り付けます。",
  "Period: {{period}}": "期間: {{period}}",
  "Plan ({{currency}})": "プラン ({{currency}})",
  "Plan / actual / remaining by category": "カテゴリー別計画/実績/残",
  "Plan {{plan}} · Actual {{actual}}": "計画 {{plan}} · 実績 {{actual}}",
  "Plans and billing": "プランと請求",
  "Planned amount ({{currency}})": "計画金額 ({{currency}})",
  "Planned expense": "予定支出",
  "Planned income": "予定収入",
  "Popular categories": "人気のあるカテゴリー",
  "Premium": "プレミアム",
  "Premium is active.": "プレミアムはアクティブです。",
  "Premium is active. The plan change will take effect on the next App Store renewal.": "プレミアムはアクティブです。プランの変更は次回の App Store 更新時に有効になります。",
  "Processing...": "処理...",
  "Product temporarily unavailable.": "製品が一時的に利用できなくなりました。",
  "Product: {{product}}": "製品: {{product}}",
  "Products for {{platform}}": "{{platform}}の製品",
  "Profile": "プロフィール",
  "Profile and security": "プロフィールとセキュリティ",
  "Profile saved.": "プロフィールが保存されました。",
  "Profile, language, and security": "プロフィール、言語、セキュリティ",
  "Purchase not confirmed. Try again.": "購入は未確認です。もう一度やり直してください。",
  "Recent transactions": "最近の取引",
  "Registration": "登録",
  "Remaining": "残り",
  "Renewal canceled": "更新がキャンセルされました",
  "Request failed (HTTP {{status}}).": "リクエストが失敗しました (HTTP {{status}})。",
  "Resend email": "メールを再送信する",
  "Restore purchases": "購入したものを復元する",
  "Restored purchases: {{count}}.": "復元された購入品: {{count}}。",
  "Restoring...": "復元中...",
  "Retry": "リトライ",
  "Root level": "ルートレベル",
  "Runtime category tree": "ランタイムカテゴリツリー",
  "Save": "保存",
  "Save and continue": "保存して続行",
  "Save balance": "残高を保存する",
  "Save password": "パスワードを保存する",
  "Saving...": "保存中...",
  "Segments show amounts by category.": "セグメントにはカテゴリごとの金額が表示されます。",
  "Select": "選択",
  "Select a base currency.": "基本通貨を選択します。",
  "Select a category": "カテゴリを選択してください",
  "Select a category and an account.": "カテゴリとアカウントを選択します。",
  "Select a category.": "カテゴリを選択します。",
  "Select a currency": "通貨を選択してください",
  "Select a date": "日付を選択してください",
  "Select a language": "言語を選択してください",
  "Select a subcategory. A parent category cannot be added.": "サブカテゴリを選択します。親カテゴリを追加することはできません。",
  "Select account": "アカウントの選択",
  "Select an account.": "アカウントを選択します。",
  "Select an icon from the shared catalog": "共有カタログからアイコンを選択します",
  "Select an interface language.": "インターフェース言語を選択します。",
  "Select the interface language and analytics currency.": "インターフェース言語と分析通貨を選択します。",
  "Send a request": "リクエストを送信する",
  "Send email": "電子メールを送信する",
  "Send request": "リクエストを送信",
  "Sending...": "送信中...",
  "Show": "表示",
  "Show password": "パスワードを表示",
  "Settings": "設定",
  "Sign in": "サインイン",
  "Signing in with Google...": "Google でサインインしています...",
  "Signing in...": "サインイン中...",
  "Some store products are not available yet: {{products}}.": "一部のストア製品はまだ利用できません: {{products}}。",
  "Spending across all accounts": "すべてのアカウントにわたる支出",
  "Start date": "開始日",
  "Step {{current}} of 2: {{screen}}": "ステップ {{current}}/2: {{screen}}",
  "Store products are available only on iOS and Android.": "ストア製品はiOSとAndroidのみでご利用いただけます。",
  "Store products are not available yet. Please check App Store or Google Play product setup.": "ストア製品はまだ入手できません。 App Store または Google Play 製品の設定を確認してください。",
  "Store purchases are available only on iOS and Android.": "ストアでの購入は iOS と Android でのみご利用いただけます。",
  "Store purchases require iOS or Android": "ストアでの購入には iOS または Android が必要です",
  "Store transaction is missing orderId.": "ストア トランザクションに orderId がありません。",
  "Store transaction is missing originalTransactionId.": "ストア トランザクションにoriginalTransactionIdがありません。",
  "Store transaction is missing packageName.": "ストア トランザクションに packageName がありません。",
  "Store transaction is missing purchaseToken.": "ストア取引に purchaseToken がありません。",
  "Store transaction is missing signed payload.": "ストア トランザクションに署名されたペイロードがありません。",
  "Store transaction is missing transactionId.": "ストア取引に transactionId がありません。",
  "Subcategories": "サブカテゴリー",
  "Subject": "件名",
  "Subscribe": "申し込む",
  "Subscription": "サブスクリプション",
  "Subscription management": "サブスクリプション管理",
  "Subscriptions": "定期購入",
  "Support": "サポート",
  "Tap the icon to select": "アイコンをタップして選択します",
  "Telegram username": "テレグラムのユーザー名",
  "The account will be deleted.": "アカウントは削除されます。",
  "The base currency cannot be changed because budgets or transactions already exist.": "予算またはトランザクションがすでに存在するため、基本通貨は変更できません。",
  "The budget category list for this month is empty.": "今月の予算カテゴリのリストは空です。",
  "The category will be removed from this month's budget.": "このカテゴリは今月の予算から削除されます。",
  "The payment is overdue. Premium access remains available through the grace-period date above.": "支払いが滞っています。プレミアムアクセスは、上記の猶予期間終了日まで引き続きご利用いただけます。",
  "The purchase was not confirmed by the store. Try again.": "購入はストアによって確認されていません。もう一度やり直してください。",
  "The server did not respond in time. Try again.": "サーバーが時間内に応答しませんでした。もう一度やり直してください。",
  "The transaction will be permanently deleted.": "トランザクションは完全に削除されます。",
  "The verified purchase is not active.": "確認済みの購入はアクティブではありません。",
  "This account has no password. Password setup is handled separately.": "このアカウントにはパスワードがありません。パスワードの設定は個別に処理されます。",
  "This purchase has already been received. Tap Restore purchases to restore the subscription.": "この購入はすでに受け付けられています。サブスクリプションを復元するには、「購入を復元」をタップします。",
  "This purchase is linked to another MoneyDrive account. Sign in to the linked account or use a different App Store Sandbox account.": "この購入は別の MoneyDrive アカウントにリンクされています。リンクされたアカウントにサインインするか、別の App Store サンドボックス アカウントを使用します。",
  "This purchase period has already expired.": "この購入期間はすでに終了しています。",
  "This purchase period has expired. Select a current subscription.": "この購入期間は終了しました。現在のサブスクリプションを選択します。",
  "This takes less than a minute.": "これには 1 分もかかりません。",
  "To goal: {{amount}}": "ゴールまで: {{amount}}",
  "To renew with LiqPay, open the web version and complete a new checkout.": "LiqPay で更新するには、Web バージョンを開いて新しいチェックアウトを完了します。",
  "Top categories by spending ({{currency}})": "支出別の上位カテゴリ ({{currency}})",
  "Total": "合計",
  "Total balance": "合計残高",
  "Transactions": "取引",
  "Transfer": "振替",
  "Type": "タイプ",
  "Type: {{type}}": "タイプ: {{type}}",
  "Unable to add the budget category (HTTP {{status}}).": "予算カテゴリ (HTTP {{status}}) を追加できません。",
  "Unable to change password.": "パスワードを変更できません。",
  "Unable to connect to the server.": "サーバーに接続できません。",
  "Unable to create budget (HTTP {{status}}).": "予算を作成できません (HTTP {{status}})。",
  "Unable to create the account.": "アカウントを作成できません。",
  "Unable to create the category (HTTP {{status}}).": "カテゴリ (HTTP {{status}}) を作成できません。",
  "Unable to delete the account.": "アカウントを削除できません。",
  "Unable to delete the category (HTTP {{status}}).": "カテゴリ (HTTP {{status}}) を削除できません。",
  "Unable to delete the transaction.": "トランザクションを削除できません。",
  "Unable to load accounts (HTTP {{status}}).": "アカウントをロードできません (HTTP {{status}})。",
  "Unable to load accounts.": "アカウントをロードできません。",
  "Unable to load budget (HTTP {{status}}).": "予算を読み込めません (HTTP {{status}})。",
  "Unable to load budgets (HTTP {{status}}).": "予算をロードできません (HTTP {{status}})。",
  "Unable to load categories.": "カテゴリを読み込めません。",
  "Unable to load category icons (HTTP {{status}}).": "カテゴリアイコンをロードできません (HTTP {{status}})。",
  "Unable to load category icons.": "カテゴリアイコンを読み込めません。",
  "Unable to load dashboard (HTTP {{status}}).": "ダッシュボードをロードできません (HTTP {{status}})。",
  "Unable to load frequent categories.": "頻繁に使用されるカテゴリを読み込めません。",
  "Unable to load settings.": "設定をロードできません。",
  "Unable to load subscription products.": "サブスクリプション製品をロードできません。",
  "Unable to load subscription status.": "サブスクリプション ステータスを読み込めません。",
  "Unable to load transactions.": "トランザクションをロードできません。",
  "Unable to open onboarding.": "オンボーディングを開けません。",
  "Unable to open the account.": "口座を開設できません。",
  "Unable to open the category for editing.": "カテゴリを開いて編集できません。",
  "Unable to open the category.": "カテゴリを開けません。",
  "Unable to open the transaction.": "トランザクションを開けません。",
  "Unable to prepare the expense form.": "経費フォームを準備できません。",
  "Unable to remove the budget category (HTTP {{status}}).": "予算カテゴリ (HTTP {{status}}) を削除できません。",
  "Unable to resend the email.": "メールを再送信できません。",
  "Unable to save the profile.": "プロファイルを保存できません。",
  "Unable to save the transaction.": "トランザクションを保存できません。",
  "Unable to send request.": "リクエストを送信できません。",
  "Unable to update balance.": "残高を更新できません。",
  "Unable to update the account.": "アカウントを更新できません。",
  "Unable to update the budget category (HTTP {{status}}).": "予算カテゴリ (HTTP {{status}}) を更新できません。",
  "Unable to update the category (HTTP {{status}}).": "カテゴリを更新できません (HTTP {{status}})。",
  "Uncategorized": "未分類",
  "Until {{date}}": "{{date}}まで",
  "Untitled": "無題",
  "Unverified": "未検証",
  "Update": "更新",
  "Verification": "検証",
  "Verification token": "検証トークン",
  "Verified": "確認済み",
  "Verify email": "メールの確認",
  "Verify with token": "トークンで検証する",
  "Verifying email...": "メールを確認しています...",
  "View all": "すべて見る",
  "View budgets": "予算を表示する",
  "We sent a verification email to {{email}}.": "{{email}} に確認メールを送信しました。",
  "We usually respond within one business day.": "通常、1 営業日以内に返信させていただきます。",
  "Your account and data are safe. Buy a new subscription to restore business features.": "あなたのアカウントとデータは安全です。ビジネス機能を復元するには、新しいサブスクリプションを購入してください。",
  "Your email": "あなたのメールアドレス",
  "Your request has been sent to our support team.": "あなたのリクエストはサポートチームに送信されました。",
  "Your session has expired. Sign in again.": "セッションの有効期限が切れました。再度サインインします。",
  "categories": "カテゴリ",
  "the specified address": "指定されたアドレス",
  "{{amount}} remaining": "残り {{amount}}",
  "{{percent}}% of plan": "計画の {{percent}}%",
  "‹ Back": "‹ 戻る",
  "Account \"{{name}}\" will be deleted.": "アカウント「{{name}}」は削除されます。",
  "Category \"{{name}}\" will be deleted.": "カテゴリ「{{name}}」は削除されます。",
} as const;

export default jaJP;
