const koKR = {
  "+{{amount}} above plan 🚀": "예산보다 {{amount}} 초과 🚀",
  "30 days": "30일",
  "A subcategory cannot contain nested subcategories.": "하위 카테고리에는 중첩된 하위 카테고리가 포함될 수 없습니다.",
  "Access denied.": "접근 불가.",
  "Access until: {{date}}": "액세스 기한: {{date}}",
  "Account": "계좌",
  "Account settings": "계좌 설정",
  "Account unavailable.": "계좌를 사용할 수 없습니다.",
  "Account: {{name}}": "계좌: {{name}}",
  "Accounts": "계좌",
  "Across all accounts": "모든 계좌에서",
  "Actual": "실제",
  "Actual expense": "실제 지출",
  "Actual income": "실제 수입",
  "Add": "추가",
  "Add account": "계좌 추가",
  "Add budget": "예산 추가",
  "Add category": "카테고리 추가",
  "Add details": "세부정보 추가",
  "Add subcategory": "하위 카테고리 추가",
  "Add to budget": "예산에 추가",
  "Add transaction": "거래 추가",
  "Add your first expense": "첫 번째 지출 추가",
  "Adding...": "첨가...",
  "All accounts": "모든 계좌",
  "All categories": "모든 카테고리",
  "All recorded income categories": "모든 기록된 소득 항목",
  "All steps completed": "모든 단계가 완료되었습니다.",
  "All time": "모든 시간",
  "All types": "모든 유형",
  "Amount": "금액",
  "Analytics period": "분석기간",
  "Another store purchase is already in progress.": "이미 다른 매장 구매가 진행 중입니다.",
  "Apple did not return an identity token.": "Apple은 ID 토큰을 반환하지 않았습니다.",
  "App Store saved {{actualProductId}} instead of {{requestedProductId}}. Check the current plan in App Store subscription settings.": "App Store는 {{requestedProductId}} 대신 {{actualProductId}}를 저장했습니다. App Store 구독 설정에서 현재 요금제를 확인하세요.",
  "Auto-renew off": "자동 갱신 꺼짐",
  "Auto-renewal is off. Premium access remains available through the date above.": "자동 갱신이 꺼져 있습니다. 위 날짜까지 프리미엄 액세스가 계속 제공됩니다.",
  "Available plans": "이용 가능한 요금제",
  "Back": "뒤로",
  "Back to sign in": "로그인으로 돌아가기",
  "Balance": "잔액",
  "Balance update timed out. Check that the backend API is available.": "잔액 업데이트 시간이 초과되었습니다. 백엔드 API를 사용할 수 있는지 확인하세요.",
  "Base currency": "기본 통화",
  "Budget": "예산",
  "Budget category": "예산 카테고리",
  "Budget changes and category editing will be added after the backend API is extended.": "백엔드 API 확장 후 예산 변경 및 카테고리 수정 기능이 추가될 예정입니다.",
  "Budget details": "예산 세부정보",
  "Budget not found.": "예산을 찾을 수 없습니다.",
  "Budget progress": "예산 진행",
  "Budgets": "예산",
  "C": "기음",
  "Cancel": "취소",
  "Categories": "카테고리",
  "Category": "카테고리",
  "Category disabled": "카테고리가 비활성화되었습니다.",
  "Category enabled": "카테고리 활성화됨",
  "Category not found in the budget.": "예산에서 카테고리를 찾을 수 없습니다.",
  "Category unavailable.": "카테고리를 사용할 수 없습니다.",
  "Category \"{{name}}\" will become a group. It can no longer be selected in new transactions and budgets. Existing records will remain unchanged.": "카테고리 \"{{name}}\"가 그룹이 됩니다. 더 이상 새로운 거래 및 예산에서 선택할 수 없습니다. 기존 기록은 변경되지 않습니다.",
  "Category will become a group": "카테고리가 그룹이 됩니다.",
  "Change balance": "잔액 변경",
  "Change password": "비밀번호 변경",
  "Check your email": "이메일을 확인하세요",
  "Checking authentication...": "인증 확인 중...",
  "Choose an App Store or Google Play product below.": "아래에서 App Store 또는 Google Play 제품을 선택하세요.",
  "Comment": "논평",
  "Complete all password fields.": "모든 비밀번호 필드를 완성하세요.",
  "Confirm new password": "새 비밀번호 확인",
  "Confirm password": "비밀번호 확인",
  "Contact support": "지원팀에 문의",
  "Continue": "계속",
  "Create": "만들기",
  "Create account": "계정 만들기",
  "Creating...": "만드는 중...",
  "Currency": "통화",
  "Current password": "현재 비밀번호",
  "Current plan": "현재 요금제",
  "Custom": "사용자 지정",
  "DONE": "완료",
  "Dashboard": "대시보드",
  "Date": "날짜",
  "Date YYYY-MM-DD": "날짜 YYYY-MM-DD",
  "Delete": "삭제",
  "Delete account?": "계좌를 삭제하시겠습니까?",
  "Delete category": "카테고리 삭제",
  "Delete category?": "카테고리를 삭제하시겠습니까?",
  "Delete transaction": "거래 삭제",
  "Delete transaction?": "거래를 삭제하시겠습니까?",
  "Deleting...": "삭제 중...",
  "Description": "설명",
  "Disabled": "비활성화",
  "Edit": "수정",
  "Edit account": "계좌 수정",
  "Edit transaction": "거래 수정",
  "Editing": "편집",
  "Email": "이메일",
  "Email resent. Retry in {{seconds}} seconds.": "이메일을 다시 보냈습니다. {{seconds}}초 후에 다시 시도하세요.",
  "Email sent. You can retry in about {{seconds}} seconds.": "이메일이 전송되었습니다. 약 {{seconds}}초 후에 다시 시도할 수 있습니다.",
  "Email verification": "이메일 인증",
  "Email verified. You can now sign in.": "이메일이 확인되었습니다. 이제 로그인할 수 있습니다.",
  "Email was not sent. Try again in {{seconds}} seconds.": "이메일이 전송되지 않았습니다. {{seconds}}초 후에 다시 시도하세요.",
  "End date": "종료일",
  "Enter a category name.": "카테고리 이름을 입력하세요.",
  "Enter a date.": "날짜를 입력하세요.",
  "Enter a message.": "메시지를 입력하세요.",
  "Enter a new password.": "새 비밀번호를 입력하세요.",
  "Enter a subject.": "제목을 입력하세요.",
  "Enter a valid amount.": "유효한 금액을 입력하세요.",
  "Enter a valid balance.": "유효한 잔액을 입력하세요.",
  "Enter a valid email address.": "유효한 이메일 주소를 입력하세요.",
  "Enter a valid planned amount greater than 0.": "0보다 큰 유효한 계획 금액을 입력하세요.",
  "Enter an account name.": "계좌 이름을 입력하세요.",
  "Enter an amount greater than zero.": "0보다 큰 금액을 입력하세요.",
  "Enter your email": "이메일을 입력하세요",
  "Enter your email, name, and password.": "이메일, 이름, 비밀번호를 입력하세요.",
  "Enter your email.": "이메일을 입력하세요.",
  "Enter your name": "이름을 입력하세요",
  "Expense": "지출",
  "Expense categories": "지출 카테고리",
  "Expense categories are not available yet.": "지출 카테고리는 아직 사용할 수 없습니다.",
  "Expense not submitted: complete the required fields.": "지출이 제출되지 않았습니다. 필수 항목을 작성하세요.",
  "Expenses": "지출",
  "Expenses and income": "지출 및 수입",
  "Expenses this period": "이번 기간의 지출",
  "Fill password": "비밀번호 입력",
  "Forgot password?": "비밀번호를 잊으셨나요?",
  "Free": "무료",
  "From {{date}}": "{{date}}에서",
  "Go to sign in": "로그인으로 이동",
  "Goal reached! 🎉": "목표 달성! 🎉",
  "Google Sign-In is not configured for this build.": "이 빌드에는 Google 로그인이 구성되어 있지 않습니다.",
  "Google did not return an ID token.": "Google이 ID 토큰을 반환하지 않았습니다.",
  "Group": "그룹",
  "Hide": "숨기기",
  "Hide form": "양식 숨기기",
  "Hide password": "비밀번호 숨기기",
  "Home": "홈",
  "I have a token": "토큰이 있어요",
  "Icon": "아이콘",
  "If the account exists, an email has been sent.": "계정이 존재하는 경우 이메일이 전송되었습니다.",
  "If the account exists, an email has been sent. Retry in {{seconds}} seconds.": "계정이 존재하는 경우 이메일이 전송되었습니다. {{seconds}}초 후에 다시 시도하세요.",
  "If the email contains a production link, paste the token manually for local testing.": "이메일에 프로덕션 링크가 포함된 경우 로컬 테스트를 위해 토큰을 수동으로 붙여넣습니다.",
  "Income": "수입",
  "Income categories": "수입 카테고리",
  "Income categories are not available yet.": "소득 항목은 아직 제공되지 않습니다.",
  "Income this period": "이번 기간 소득",
  "Initial setup": "초기 설정",
  "Interface language": "인터페이스 언어",
  "Invalid accounts response format.": "계좌 응답 형식이 잘못되었습니다.",
  "Invalid budget response format.": "예산 응답 형식이 잘못되었습니다.",
  "Keep an eye on all of your balances.": "모든 잔액을 주의 깊게 살펴보세요.",
  "Language and base currency": "언어 및 기본 통화",
  "LiqPay subscription can be cancelled only in the web version of the app.": "LiqPay 구독 취소는 웹 버전의 앱에서만 가능합니다.",
  "Loading accounts...": "계좌 로드 중...",
  "Loading budget...": "예산 로드 중...",
  "Loading budgets...": "예산 로드 중...",
  "Loading categories...": "카테고리 로드 중...",
  "Loading dashboard...": "대시보드 로드 중...",
  "Loading icons...": "아이콘 로드 중...",
  "Loading onboarding...": "온보딩 로드 중...",
  "Loading settings...": "설정 로드 중...",
  "Loading store products...": "매장 제품 로드 중...",
  "Loading subscription status...": "구독 상태 로드 중...",
  "Loading...": "로드 중...",
  "Log in": "로그인",
  "Login with Google": "구글로 로그인",
  "Logout": "로그아웃",
  "Manage on web": "웹에서 관리",
  "Manage premium access": "프리미엄 액세스 관리",
  "Manage subscription": "구독 관리",
  "Maximum category depth is 2 levels": "최대 카테고리 깊이는 2레벨입니다.",
  "Maximum category depth is 2 levels.": "최대 카테고리 깊이는 2레벨입니다.",
  "Message": "메시지",
  "Missing Android subscription offer token for selected product.": "선택한 제품에 대한 Android 구독 제안 토큰이 누락되었습니다.",
  "Missing account ID.": "계좌 ID가 누락되었습니다.",
  "Missing budgetId.": "예산 ID가 누락되었습니다.",
  "Missing reset token.": "재설정 토큰이 누락되었습니다.",
  "MoneyDrive.me": "MoneyDrive.me",
  "Month": "월",
  "More": "더",
  "More service sections": "더 많은 서비스 섹션",
  "Most frequent": "가장 자주",
  "Name": "이름",
  "New account": "새 계좌",
  "New balance": "뉴발란스",
  "New category": "새로운 카테고리",
  "New email awaiting verification: {{email}}": "확인 대기 중인 새 이메일: {{email}}",
  "New password": "새 비밀번호",
  "New planned amount": "새로운 계획 금액",
  "No App Store Sandbox account is connected on this device. Add a sandbox tester in Settings > App Store > Sandbox Account.": "이 기기에는 App Store Sandbox 계정이 연결되어 있지 않습니다. 설정 > App Store > 샌드박스 계정에서 샌드박스 테스터를 추가하세요.",
  "No account": "계좌 없음",
  "No account data.": "계좌 데이터가 없습니다.",
  "No accounts.": "계좌가 없습니다.",
  "No active purchases found.": "활성 구매가 없습니다.",
  "No active store source": "활성 스토어 소스가 없습니다.",
  "No budget has been created for the selected month.": "선택한 달에는 예산이 생성되지 않았습니다.",
  "No budgets for the selected period.": "선택한 기간에는 예산이 없습니다.",
  "No budgets found yet.": "아직 예산을 찾을 수 없습니다.",
  "No categories available to add.": "추가할 수 있는 카테고리가 없습니다.",
  "No categories found for the selected type.": "선택한 유형에 해당하는 카테고리를 찾을 수 없습니다.",
  "No categories found.": "카테고리를 찾을 수 없습니다.",
  "No categories.": "카테고리가 없습니다.",
  "No data for the selected period.": "선택한 기간에 대한 데이터가 없습니다.",
  "No data.": "데이터가 없습니다.",
  "No external management action is available.": "외부 관리 작업을 사용할 수 없습니다.",
  "No period selected": "기간을 선택하지 않았습니다.",
  "No transaction data.": "거래 데이터가 없습니다.",
  "No transactions yet.": "아직 거래가 없습니다.",
  "Not enough data to add the category.": "카테고리를 추가할 데이터가 충분하지 않습니다.",
  "Not set": "설정되지 않음",
  "Note": "메모",
  "Open": "열기",
  "Open App Store account settings and choose Subscriptions.": "App Store 계정 설정을 열고 구독을 선택하세요.",
  "Open the subscription provider account settings to manage this plan.": "이 요금제를 관리하려면 구독 공급자 계정 설정을 여세요.",
  "Overspent by {{amount}}": "예산 {{amount}} 초과",
  "Parent: {{name}}": "상위: {{name}}",
  "Password": "비밀번호",
  "Password changed.": "비밀번호가 변경되었습니다.",
  "Password recovery": "비밀번호 복구",
  "Password updated. You can now sign in.": "비밀번호가 업데이트되었습니다. 이제 로그인할 수 있습니다.",
  "Passwords do not match.": "비밀번호가 일치하지 않습니다.",
  "Paste the verification token.": "인증 토큰을 붙여넣으세요.",
  "Period: {{period}}": "기간: {{period}}",
  "Plan ({{currency}})": "계획({{currency}})",
  "Plan / actual / remaining by category": "카테고리별 계획/실제/남음",
  "Plan {{plan}} · Actual {{actual}}": "계획 {{plan}} · 실제 {{actual}}",
  "Plans and billing": "요금제 및 결제",
  "Planned amount ({{currency}})": "예정금액({{currency}})",
  "Planned expense": "계획된 지출",
  "Planned income": "계획소득",
  "Popular categories": "인기 카테고리",
  "Premium": "프리미엄",
  "Premium is active.": "프리미엄이 활성화되어 있습니다.",
  "Premium is active. The plan change will take effect on the next App Store renewal.": "프리미엄이 활성화되어 있습니다. 요금제 변경은 다음 App Store 갱신 시 적용됩니다.",
  "Processing...": "처리 중...",
  "Product temporarily unavailable.": "일시적으로 제품을 사용할 수 없습니다.",
  "Product: {{product}}": "제품: {{product}}",
  "Products for {{platform}}": "{{platform}}용 제품",
  "Profile": "윤곽",
  "Profile and security": "프로필 및 보안",
  "Profile saved.": "프로필이 저장되었습니다.",
  "Profile, language, and security": "프로필, 언어 및 보안",
  "Purchase not confirmed. Try again.": "구매가 확인되지 않았습니다. 다시 시도해 보세요.",
  "Recent transactions": "최근 거래",
  "Registration": "등록",
  "Remaining": "남은",
  "Renewal canceled": "갱신이 취소되었습니다.",
  "Request failed (HTTP {{status}}).": "요청이 실패했습니다(HTTP {{status}}).",
  "Resend email": "이메일 재전송",
  "Restore purchases": "구매 복원",
  "Restored purchases: {{count}}.": "복원된 구매: {{count}}.",
  "Restoring...": "복원 중...",
  "Retry": "다시 해 보다",
  "Root level": "루트 수준",
  "Runtime category tree": "런타임 카테고리 트리",
  "Save": "저장",
  "Save and continue": "저장하고 계속하세요",
  "Save balance": "잔액 저장",
  "Save password": "비밀번호 저장",
  "Saving...": "저장 중...",
  "Segments show amounts by category.": "세그먼트에는 카테고리별로 금액이 표시됩니다.",
  "Select": "선택",
  "Select a base currency.": "기본 통화를 선택하세요.",
  "Select a category": "카테고리를 선택하세요",
  "Select a category and an account.": "카테고리와 계좌를 선택하세요.",
  "Select a category.": "카테고리를 선택하세요.",
  "Select a currency": "통화를 선택하세요",
  "Select a date": "날짜를 선택하세요",
  "Select a language": "언어를 선택하세요",
  "Select a subcategory. A parent category cannot be added.": "하위 카테고리를 선택하세요. 상위 카테고리를 추가할 수 없습니다.",
  "Select account": "계좌 선택",
  "Select an account.": "계좌를 선택하세요.",
  "Select an icon from the shared catalog": "공유 카탈로그에서 아이콘을 선택하세요",
  "Select an interface language.": "인터페이스 언어를 선택하세요.",
  "Select the interface language and analytics currency.": "인터페이스 언어와 분석 통화를 선택하세요.",
  "Send a request": "요청 보내기",
  "Send email": "이메일 보내기",
  "Send request": "요청 보내기",
  "Sending...": "배상...",
  "Show": "표시",
  "Show password": "비밀번호 표시",
  "Settings": "설정",
  "Sign in": "로그인",
  "Signing in with Google...": "Google로 로그인 중...",
  "Signing in...": "로그인 중...",
  "Some store products are not available yet: {{products}}.": "일부 매장 제품은 아직 사용할 수 없습니다: {{products}}.",
  "Spending across all accounts": "모든 계좌의 지출",
  "Start date": "시작일",
  "Step {{current}} of 2: {{screen}}": "2단계의 {{current}}: {{screen}}",
  "Store products are available only on iOS and Android.": "스토어 상품은 iOS, Android에서만 이용 가능합니다.",
  "Store products are not available yet. Please check App Store or Google Play product setup.": "아직 매장상품은 나오지 않습니다. App Store 또는 Google Play 제품 설정을 확인하세요.",
  "Store purchases are available only on iOS and Android.": "스토어 구매는 iOS와 Android에서만 가능합니다.",
  "Store purchases require iOS or Android": "매장 구매에는 iOS 또는 Android가 필요합니다.",
  "Store transaction is missing orderId.": "상점 거래에 orderId가 누락되었습니다.",
  "Store transaction is missing originalTransactionId.": "상점 거래에 originalTransactionId가 누락되었습니다.",
  "Store transaction is missing packageName.": "상점 거래에 packageName이 누락되었습니다.",
  "Store transaction is missing purchaseToken.": "상점 거래에 purchaseToken이 없습니다.",
  "Store transaction is missing signed payload.": "상점 거래에 서명된 페이로드가 없습니다.",
  "Store transaction is missing transactionId.": "상점 거래에 transactionId가 누락되었습니다.",
  "Subcategories": "하위 카테고리",
  "Subject": "제목",
  "Subscribe": "구독하기",
  "Subscription": "구독",
  "Subscription management": "구독 관리",
  "Subscriptions": "구독",
  "Support": "지원",
  "Tap the icon to select": "아이콘을 탭하여 선택하세요.",
  "Telegram username": "텔레그램 사용자 이름",
  "The account will be deleted.": "계좌가 삭제됩니다.",
  "The base currency cannot be changed because budgets or transactions already exist.": "예산이나 거래가 이미 존재하므로 기본 통화를 변경할 수 없습니다.",
  "The budget category list for this month is empty.": "이번 달 예산 범주 목록이 비어 있습니다.",
  "The category will be removed from this month's budget.": "해당 카테고리가 이번 달 예산에서 삭제됩니다.",
  "The payment is overdue. Premium access remains available through the grace-period date above.": "결제가 연체되었습니다. 프리미엄 이용 권한은 위에 표시된 유예 기간 종료일까지 유지됩니다.",
  "The purchase was not confirmed by the store. Try again.": "매장에서 구매가 확인되지 않았습니다. 다시 시도해 보세요.",
  "The server did not respond in time. Try again.": "서버가 제 시간에 응답하지 않았습니다. 다시 시도해 보세요.",
  "The transaction will be permanently deleted.": "거래가 영구적으로 삭제됩니다.",
  "The verified purchase is not active.": "확인된 구매가 ​​활성화되어 있지 않습니다.",
  "This account has no password. Password setup is handled separately.": "이 계정에는 비밀번호가 없습니다. 비밀번호 설정은 별도로 처리됩니다.",
  "This purchase has already been received. Tap Restore purchases to restore the subscription.": "이 구매는 이미 접수되었습니다. 구독을 복원하려면 구매 복원을 탭하세요.",
  "This purchase is linked to another MoneyDrive account. Sign in to the linked account or use a different App Store Sandbox account.": "이 구매는 다른 MoneyDrive 계정에 연결되어 있습니다. 연결된 계정으로 로그인하거나 다른 App Store Sandbox 계정을 사용하세요.",
  "This purchase period has already expired.": "이 구매 기간은 이미 만료되었습니다.",
  "This purchase period has expired. Select a current subscription.": "구매 기간이 만료되었습니다. 현재 구독을 선택하세요.",
  "This takes less than a minute.": "이 작업은 1분도 채 걸리지 않습니다.",
  "To goal: {{amount}}": "목표로 : {{amount}}",
  "To renew with LiqPay, open the web version and complete a new checkout.": "LiqPay로 갱신하려면 웹 버전을 열고 새로 결제를 완료하세요.",
  "Top categories by spending ({{currency}})": "지출별 상위 카테고리({{currency}})",
  "Total": "합계",
  "Total balance": "총 잔액",
  "Transactions": "거래",
  "Transfer": "이체",
  "Type": "유형",
  "Type: {{type}}": "유형: {{type}}",
  "Unable to add the budget category (HTTP {{status}}).": "예산 카테고리(HTTP {{status}})를 추가할 수 없습니다.",
  "Unable to change password.": "비밀번호를 변경할 수 없습니다.",
  "Unable to connect to the server.": "서버에 연결할 수 없습니다.",
  "Unable to create budget (HTTP {{status}}).": "예산을 생성할 수 없습니다(HTTP {{status}}).",
  "Unable to create the account.": "계좌를 생성할 수 없습니다.",
  "Unable to create the category (HTTP {{status}}).": "카테고리(HTTP {{status}})를 생성할 수 없습니다.",
  "Unable to delete the account.": "계좌를 삭제할 수 없습니다.",
  "Unable to delete the category (HTTP {{status}}).": "카테고리(HTTP {{status}})를 삭제할 수 없습니다.",
  "Unable to delete the transaction.": "거래를 삭제할 수 없습니다.",
  "Unable to load accounts (HTTP {{status}}).": "계좌를 로드할 수 없습니다(HTTP {{status}}).",
  "Unable to load accounts.": "계좌를 로드할 수 없습니다.",
  "Unable to load budget (HTTP {{status}}).": "예산을 로드할 수 없습니다(HTTP {{status}}).",
  "Unable to load budgets (HTTP {{status}}).": "예산을 로드할 수 없습니다(HTTP {{status}}).",
  "Unable to load categories.": "카테고리를 로드할 수 없습니다.",
  "Unable to load category icons (HTTP {{status}}).": "카테고리 아이콘(HTTP {{status}})을 로드할 수 없습니다.",
  "Unable to load category icons.": "카테고리 아이콘을 로드할 수 없습니다.",
  "Unable to load dashboard (HTTP {{status}}).": "대시보드를 로드할 수 없습니다(HTTP {{status}}).",
  "Unable to load frequent categories.": "자주 사용하는 카테고리를 로드할 수 없습니다.",
  "Unable to load settings.": "설정을 로드할 수 없습니다.",
  "Unable to load subscription products.": "구독 제품을 로드할 수 없습니다.",
  "Unable to load subscription status.": "구독 상태를 로드할 수 없습니다.",
  "Unable to load transactions.": "거래를 로드할 수 없습니다.",
  "Unable to open onboarding.": "온보딩을 열 수 없습니다.",
  "Unable to open the account.": "계좌를 열 수 없습니다.",
  "Unable to open the category for editing.": "편집할 카테고리를 열 수 없습니다.",
  "Unable to open the category.": "카테고리를 열 수 없습니다.",
  "Unable to open the transaction.": "거래를 열 수 없습니다.",
  "Unable to prepare the expense form.": "지출양식을 작성할 수 없습니다.",
  "Unable to remove the budget category (HTTP {{status}}).": "예산 카테고리(HTTP {{status}})를 제거할 수 없습니다.",
  "Unable to resend the email.": "이메일을 다시 보낼 수 없습니다.",
  "Unable to save the profile.": "프로필을 저장할 수 없습니다.",
  "Unable to save the transaction.": "거래를 저장할 수 없습니다.",
  "Unable to send request.": "요청을 보낼 수 없습니다.",
  "Unable to update balance.": "잔액을 업데이트할 수 없습니다.",
  "Unable to update the account.": "계좌를 업데이트할 수 없습니다.",
  "Unable to update the budget category (HTTP {{status}}).": "예산 카테고리(HTTP {{status}})를 업데이트할 수 없습니다.",
  "Unable to update the category (HTTP {{status}}).": "카테고리(HTTP {{status}})를 업데이트할 수 없습니다.",
  "Uncategorized": "분류되지 않음",
  "Until {{date}}": "{{date}}까지",
  "Untitled": "제목 없음",
  "Unverified": "확인되지 않음",
  "Update": "업데이트",
  "Verification": "확인",
  "Verification token": "인증 토큰",
  "Verified": "확인됨",
  "Verify email": "이메일 확인",
  "Verify with token": "토큰으로 확인",
  "Verifying email...": "이메일 확인 중...",
  "View all": "모두 보기",
  "View budgets": "예산 보기",
  "We sent a verification email to {{email}}.": "{{email}}로 확인 이메일을 보냈습니다.",
  "We usually respond within one business day.": "우리는 일반적으로 영업일 기준 1일 이내에 응답합니다.",
  "Your account and data are safe. Buy a new subscription to restore business features.": "귀하의 계정과 데이터는 안전합니다. 비즈니스 기능을 복원하려면 새 구독을 구입하세요.",
  "Your email": "귀하의 이메일",
  "Your request has been sent to our support team.": "귀하의 요청이 지원팀으로 전송되었습니다.",
  "Your session has expired. Sign in again.": "세션이 만료되었습니다. 다시 로그인하세요.",
  "categories": "카테고리",
  "the specified address": "지정된 주소",
  "{{amount}} remaining": "{{amount}} 남음",
  "{{percent}}% of plan": "계획의 {{percent}}%",
  "‹ Back": "‹ 뒤로",
  "Account \"{{name}}\" will be deleted.": "\"{{name}}\" 계좌가 삭제됩니다.",
  "Category \"{{name}}\" will be deleted.": "'{{name}}' 카테고리가 삭제됩니다.",
} as const;

export default koKR;
