const nlNL = {
  "+{{amount}} above plan 🚀": "+{{amount}} boven plan 🚀",
  "30 days": "30 dagen",
  "A subcategory cannot contain nested subcategories.": "Een subcategorie kan geen geneste subcategorieën bevatten.",
  "Access denied.": "Toegang geweigerd.",
  "Access until: {{date}}": "Toegang tot: {{date}}",
  "Account": "Rekening",
  "Account settings": "Rekeninginstellingen",
  "Account unavailable.": "Rekening niet beschikbaar.",
  "Account: {{name}}": "Rekening: {{name}}",
  "Accounts": "Rekeningen",
  "Across all accounts": "Over alle rekeningen",
  "Actual": "Werkelijk",
  "Actual expense": "Werkelijke kosten",
  "Actual income": "Werkelijk inkomen",
  "Add": "Toevoegen",
  "Add account": "Rekening toevoegen",
  "Add budget": "Voeg budget toe",
  "Add category": "Categorie toevoegen",
  "Add details": "Voeg details toe",
  "Add subcategory": "Subcategorie toevoegen",
  "Add to budget": "Voeg toe aan de begroting",
  "Add transaction": "Transactie toevoegen",
  "Add your first expense": "Voeg uw eerste uitgave toe",
  "Adding...": "Toevoegen...",
  "All accounts": "Alle rekeningen",
  "All categories": "Alle categorieën",
  "All recorded income categories": "Alle geregistreerde inkomenscategorieën",
  "All steps completed": "Alle stappen voltooid",
  "All time": "Altijd",
  "All types": "Alle soorten",
  "Amount": "Bedrag",
  "Analytics period": "Analytics-periode",
  "Another store purchase is already in progress.": "Een andere winkelaankoop is al aan de gang.",
  "Apple did not return an identity token.": "Apple heeft geen identiteitstoken geretourneerd.",
  "App Store saved {{actualProductId}} instead of {{requestedProductId}}. Check the current plan in App Store subscription settings.": "App Store heeft {{actualProductId}} opgeslagen in plaats van {{requestedProductId}}. Controleer het huidige abonnement in de abonnementsinstellingen van de App Store.",
  "Auto-renew off": "Automatische verlenging uitgeschakeld",
  "Auto-renewal is off. Premium access remains available through the date above.": "Automatische verlenging staat uit. Premium-toegang blijft beschikbaar tot en met de bovenstaande datum.",
  "Available plans": "Beschikbare plannen",
  "Back": "Terug",
  "Back to sign in": "Terug naar inloggen",
  "Balance": "Saldo",
  "Balance update timed out. Check that the backend API is available.": "Er is een time-out opgetreden bij het bijwerken van het saldo. Controleer of de backend-API beschikbaar is.",
  "Base currency": "Basisvaluta",
  "Budget": "Budget",
  "Budget category": "Budgetcategorie",
  "Budget changes and category editing will be added after the backend API is extended.": "Budgetwijzigingen en categoriebewerking worden toegevoegd nadat de backend API is uitgebreid.",
  "Budget details": "Budgetdetails",
  "Budget not found.": "Budget niet gevonden.",
  "Budget progress": "Budgetvoortgang",
  "Budgets": "Budgetten",
  "C": "C",
  "Cancel": "Annuleren",
  "Categories": "Categorieën",
  "Category": "Categorie",
  "Category disabled": "Categorie uitgeschakeld",
  "Category enabled": "Categorie ingeschakeld",
  "Category not found in the budget.": "Categorie niet gevonden in de begroting.",
  "Category unavailable.": "Categorie niet beschikbaar.",
  "Category \"{{name}}\" will become a group. It can no longer be selected in new transactions and budgets. Existing records will remain unchanged.": "Categorie \"{{name}}\" wordt een groep. Deze kan niet langer worden geselecteerd voor nieuwe transacties en budgetten. Bestaande records blijven ongewijzigd.",
  "Category will become a group": "Categorie wordt een groep",
  "Change balance": "Saldo wijzigen",
  "Change password": "Wachtwoord wijzigen",
  "Check your email": "Controleer uw e-mail",
  "Checking authentication...": "Verificatie controleren...",
  "Choose an App Store or Google Play product below.": "Kies hieronder een App Store- of Google Play-product.",
  "Comment": "Opmerking",
  "Complete all password fields.": "Vul alle wachtwoordvelden in.",
  "Confirm new password": "Bevestig nieuw wachtwoord",
  "Confirm password": "Bevestig wachtwoord",
  "Contact support": "Neem contact op met de ondersteuning",
  "Continue": "Doorgaan",
  "Create": "Creëren",
  "Create account": "Account aanmaken",
  "Creating...": "Creëren...",
  "Currency": "Munteenheid",
  "Current password": "Huidig ​​wachtwoord",
  "Current plan": "Huidig ​​abonnement",
  "Custom": "Aangepast",
  "DONE": "KLAAR",
  "Dashboard": "Dashboard",
  "Date": "Datum",
  "Date YYYY-MM-DD": "Datum JJJJ-MM-DD",
  "Delete": "Verwijderen",
  "Delete account?": "Rekening verwijderen?",
  "Delete category": "Categorie verwijderen",
  "Delete category?": "Categorie verwijderen?",
  "Delete transaction": "Transactie verwijderen",
  "Delete transaction?": "Transactie verwijderen?",
  "Deleting...": "Verwijderen...",
  "Description": "Beschrijving",
  "Disabled": "Uitgeschakeld",
  "Edit": "Bewerken",
  "Edit account": "Rekening bewerken",
  "Edit transaction": "Transactie bewerken",
  "Editing": "Bewerken",
  "Email": "E-mail",
  "Email resent. Retry in {{seconds}} seconds.": "E-mail opnieuw verzonden. Probeer het over {{seconds}} seconden opnieuw.",
  "Email sent. You can retry in about {{seconds}} seconds.": "E-mail verzonden. U kunt het over ongeveer {{seconds}} seconden opnieuw proberen.",
  "Email verification": "E-mailverificatie",
  "Email verified. You can now sign in.": "E-mail geverifieerd. U kunt nu inloggen.",
  "Email was not sent. Try again in {{seconds}} seconds.": "E-mail is niet verzonden. Probeer het over {{seconds}} seconden opnieuw.",
  "End date": "Einddatum",
  "Enter a category name.": "Voer een categorienaam in.",
  "Enter a date.": "Voer een datum in.",
  "Enter a message.": "Voer een bericht in.",
  "Enter a new password.": "Voer een nieuw wachtwoord in.",
  "Enter a subject.": "Voer een onderwerp in.",
  "Enter a valid amount.": "Vul een geldig bedrag in.",
  "Enter a valid balance.": "Voer een geldig saldo in.",
  "Enter a valid email address.": "Voer een geldig e-mailadres in.",
  "Enter a valid planned amount greater than 0.": "Voer een geldig gepland bedrag in dat groter is dan 0.",
  "Enter an account name.": "Voer een rekeningnaam in.",
  "Enter an amount greater than zero.": "Voer een bedrag in dat groter is dan nul.",
  "Enter your email": "Voer uw e-mailadres in",
  "Enter your email, name, and password.": "Voer uw e-mailadres, naam en wachtwoord in.",
  "Enter your email.": "Voer uw e-mailadres in.",
  "Enter your name": "Voer uw naam in",
  "Expense": "Uitgave",
  "Expense categories": "Uitgavencategorieën",
  "Expense categories are not available yet.": "Onkostencategorieën zijn nog niet beschikbaar.",
  "Expense not submitted: complete the required fields.": "Onkosten niet ingediend: vul de verplichte velden in.",
  "Expenses": "Uitgaven",
  "Expenses and income": "Uitgaven en inkomsten",
  "Expenses this period": "Uitgaven in deze periode",
  "Fill password": "Wachtwoord invullen",
  "Forgot password?": "Wachtwoord vergeten?",
  "Free": "Gratis",
  "From {{date}}": "Van {{date}}",
  "Go to sign in": "Ga naar inloggen",
  "Goal reached! 🎉": "Doel bereikt! 🎉",
  "Google Sign-In is not configured for this build.": "Inloggen bij Google is niet geconfigureerd voor deze build.",
  "Google did not return an ID token.": "Google heeft geen ID-token geretourneerd.",
  "Group": "Groep",
  "Hide": "Verbergen",
  "Hide form": "Formulier verbergen",
  "Hide password": "Wachtwoord verbergen",
  "Home": "Start",
  "I have a token": "Ik heb een teken",
  "Icon": "Icon",
  "If the account exists, an email has been sent.": "Als het account bestaat, is er een e-mail verzonden.",
  "If the account exists, an email has been sent. Retry in {{seconds}} seconds.": "Als het account bestaat, is er een e-mail verzonden. Probeer het over {{seconds}} seconden opnieuw.",
  "If the email contains a production link, paste the token manually for local testing.": "Als de e-mail een productielink bevat, plakt u het token handmatig voor lokale tests.",
  "Income": "Inkomen",
  "Income categories": "Inkomenscategorieën",
  "Income categories are not available yet.": "Inkomenscategorieën zijn nog niet beschikbaar.",
  "Income this period": "Inkomen deze periode",
  "Initial setup": "Initiële installatie",
  "Interface language": "Interfacetaal",
  "Invalid accounts response format.": "Ongeldig antwoordformaat voor rekeningen.",
  "Invalid budget response format.": "Ongeldig formaat voor budgetreactie.",
  "Keep an eye on all of your balances.": "Houd al uw saldi in de gaten.",
  "Language and base currency": "Taal en basisvaluta",
  "LiqPay subscription can be cancelled only in the web version of the app.": "Het LiqPay-abonnement kan alleen worden opgezegd in de webversie van de app.",
  "Loading accounts...": "Rekeningen laden...",
  "Loading budget...": "Budget laden...",
  "Loading budgets...": "Budgetten laden...",
  "Loading categories...": "Categorieën laden...",
  "Loading dashboard...": "Dashboard laden...",
  "Loading icons...": "Pictogrammen laden...",
  "Loading onboarding...": "Onboarding laden...",
  "Loading settings...": "Instellingen laden...",
  "Loading store products...": "Winkelproducten laden...",
  "Loading subscription status...": "Abonnementstatus laden...",
  "Loading...": "Laden...",
  "Log in": "Inloggen",
  "Login with Google": "Inloggen met Google",
  "Logout": "Uitloggen",
  "Manage on web": "Beheer op internet",
  "Manage premium access": "Beheer premiumtoegang",
  "Manage subscription": "Beheer abonnement",
  "Maximum category depth is 2 levels": "De maximale categoriediepte is 2 niveaus",
  "Maximum category depth is 2 levels.": "De maximale categoriediepte is 2 niveaus.",
  "Message": "Bericht",
  "Missing Android subscription offer token for selected product.": "Ontbrekende token voor Android-abonnementsaanbieding voor geselecteerd product.",
  "Missing account ID.": "Ontbrekende rekening-ID.",
  "Missing budgetId.": "Ontbrekende budgetID.",
  "Missing reset token.": "Ontbrekende reset-token.",
  "MoneyDrive.me": "MoneyDrive.me",
  "Month": "Maand",
  "More": "Meer",
  "More service sections": "Meer servicesecties",
  "Most frequent": "Meest voorkomende",
  "Name": "Naam",
  "New account": "Nieuwe rekening",
  "New balance": "Nieuw saldo",
  "New category": "Nieuwe categorie",
  "New email awaiting verification: {{email}}": "Nieuw e-mailadres in afwachting van verificatie: {{email}}",
  "New password": "Nieuw wachtwoord",
  "New planned amount": "Nieuw gepland bedrag",
  "No App Store Sandbox account is connected on this device. Add a sandbox tester in Settings > App Store > Sandbox Account.": "Er is geen App Store Sandbox-account verbonden op dit apparaat. Voeg een sandboxtester toe via Instellingen > App Store > Sandbox-account.",
  "No account": "Geen rekening",
  "No account data.": "Geen rekeninggegevens.",
  "No accounts.": "Geen rekeningen.",
  "No active purchases found.": "Geen actieve aankopen gevonden.",
  "No active store source": "Geen actieve winkelbron",
  "No budget has been created for the selected month.": "Er is geen budget aangemaakt voor de geselecteerde maand.",
  "No budgets for the selected period.": "Geen budgetten voor de geselecteerde periode.",
  "No budgets found yet.": "Er zijn nog geen budgetten gevonden.",
  "No categories available to add.": "Er zijn geen categorieën beschikbaar om toe te voegen.",
  "No categories found for the selected type.": "Er zijn geen categorieën gevonden voor het geselecteerde type.",
  "No categories found.": "Geen categorieën gevonden.",
  "No categories.": "Geen categorieën.",
  "No data for the selected period.": "Geen gegevens voor de geselecteerde periode.",
  "No data.": "Geen gegevens.",
  "No external management action is available.": "Er is geen externe beheeractie beschikbaar.",
  "No period selected": "Geen periode geselecteerd",
  "No transaction data.": "Geen transactiegegevens.",
  "No transactions yet.": "Nog geen transacties.",
  "Not enough data to add the category.": "Onvoldoende gegevens om de categorie toe te voegen.",
  "Not set": "Niet ingesteld",
  "Note": "Opmerking",
  "Open": "Open",
  "Open App Store account settings and choose Subscriptions.": "Open App Store-accountinstellingen en kies Abonnementen.",
  "Open the subscription provider account settings to manage this plan.": "Open de accountinstellingen van de abonnementsprovider om dit abonnement te beheren.",
  "Overspent by {{amount}}": "{{amount}} te veel uitgegeven",
  "Parent: {{name}}": "Ouder: {{name}}",
  "Password": "Wachtwoord",
  "Password changed.": "Wachtwoord gewijzigd.",
  "Password recovery": "Wachtwoordherstel",
  "Password updated. You can now sign in.": "Wachtwoord bijgewerkt. U kunt nu inloggen.",
  "Passwords do not match.": "Wachtwoorden komen niet overeen.",
  "Paste the verification token.": "Plak het verificatietoken.",
  "Period: {{period}}": "Periode: {{period}}",
  "Plan ({{currency}})": "Plan ({{currency}})",
  "Plan / actual / remaining by category": "Plan / actueel / resterend per categorie",
  "Plan {{plan}} · Actual {{actual}}": "Plan {{plan}} · Werkelijk {{actual}}",
  "Plans and billing": "Plannen en facturering",
  "Planned amount ({{currency}})": "Gepland bedrag ({{currency}})",
  "Planned expense": "Geplande kosten",
  "Planned income": "Gepland inkomen",
  "Popular categories": "Populaire categorieën",
  "Premium": "Premium",
  "Premium is active.": "Premium is actief.",
  "Premium is active. The plan change will take effect on the next App Store renewal.": "Premium is actief. De abonnementswijziging wordt van kracht bij de volgende verlenging in de App Store.",
  "Processing...": "Verwerken...",
  "Product temporarily unavailable.": "Product tijdelijk niet leverbaar.",
  "Product: {{product}}": "Product: {{product}}",
  "Products for {{platform}}": "Producten voor {{platform}}",
  "Profile": "Profiel",
  "Profile and security": "Profiel en beveiliging",
  "Profile saved.": "Profiel opgeslagen.",
  "Profile, language, and security": "Profiel, taal en beveiliging",
  "Purchase not confirmed. Try again.": "Aankoop niet bevestigd. Probeer het opnieuw.",
  "Recent transactions": "Recente transacties",
  "Registration": "Registratie",
  "Remaining": "Resterend",
  "Renewal canceled": "Verlenging geannuleerd",
  "Request failed (HTTP {{status}}).": "Verzoek mislukt (HTTP {{status}}).",
  "Resend email": "E-mail opnieuw verzenden",
  "Restore purchases": "Aankopen herstellen",
  "Restored purchases: {{count}}.": "Herstelde aankopen: {{count}}.",
  "Restoring...": "Herstellen...",
  "Retry": "Opnieuw proberen",
  "Root level": "Hoofdniveau",
  "Runtime category tree": "Runtime-categoriestructuur",
  "Save": "Opslaan",
  "Save and continue": "Opslaan en doorgaan",
  "Save balance": "Saldo opslaan",
  "Save password": "Wachtwoord opslaan",
  "Saving...": "Opslaan...",
  "Segments show amounts by category.": "Segmenten tonen bedragen per categorie.",
  "Select": "Selecteer",
  "Select a base currency.": "Selecteer een basisvaluta.",
  "Select a category": "Selecteer een categorie",
  "Select a category and an account.": "Selecteer een categorie en een rekening.",
  "Select a category.": "Selecteer een categorie.",
  "Select a currency": "Selecteer een valuta",
  "Select a date": "Selecteer een datum",
  "Select a language": "Selecteer een taal",
  "Select a subcategory. A parent category cannot be added.": "Selecteer een subcategorie. Er kan geen bovenliggende categorie worden toegevoegd.",
  "Select account": "Selecteer rekening",
  "Select an account.": "Selecteer een rekening.",
  "Select an icon from the shared catalog": "Selecteer een pictogram uit de gedeelde catalogus",
  "Select an interface language.": "Selecteer een interfacetaal.",
  "Select the interface language and analytics currency.": "Selecteer de interfacetaal en de analysevaluta.",
  "Send a request": "Stuur een verzoek",
  "Send email": "E-mail verzenden",
  "Send request": "Verzoek verzenden",
  "Sending...": "Verzenden...",
  "Show": "Tonen",
  "Show password": "Wachtwoord tonen",
  "Settings": "Instellingen",
  "Sign in": "Log in",
  "Signing in with Google...": "Aanmelden met Google...",
  "Signing in...": "Aanmelden...",
  "Some store products are not available yet: {{products}}.": "Sommige winkelproducten zijn nog niet verkrijgbaar: {{products}}.",
  "Spending across all accounts": "Uitgaven over alle rekeningen",
  "Start date": "Startdatum",
  "Step {{current}} of 2: {{screen}}": "Stap {{current}} van 2: {{screen}}",
  "Store products are available only on iOS and Android.": "Winkelproducten zijn alleen beschikbaar op iOS en Android.",
  "Store products are not available yet. Please check App Store or Google Play product setup.": "Winkelproducten zijn nog niet beschikbaar. Controleer de productinstellingen in de App Store of Google Play.",
  "Store purchases are available only on iOS and Android.": "Winkelaankopen zijn alleen beschikbaar op iOS en Android.",
  "Store purchases require iOS or Android": "Voor winkelaankopen is iOS of Android vereist",
  "Store transaction is missing orderId.": "Winkeltransactie mist orderId.",
  "Store transaction is missing originalTransactionId.": "Winkeltransactie mist originalTransactionId.",
  "Store transaction is missing packageName.": "Bij de winkeltransactie ontbreekt packageName.",
  "Store transaction is missing purchaseToken.": "Bij de winkeltransactie ontbreekt purchaseToken.",
  "Store transaction is missing signed payload.": "Bij winkeltransactie ontbreekt de ondertekende payload.",
  "Store transaction is missing transactionId.": "Winkeltransactie mist transactionId.",
  "Subcategories": "Subcategorieën",
  "Subject": "Onderwerp",
  "Subscribe": "Abonneren",
  "Subscription": "Abonnement",
  "Subscription management": "Abonnementsbeheer",
  "Subscriptions": "Abonnementen",
  "Support": "Ondersteuning",
  "Tap the icon to select": "Tik op het pictogram om te selecteren",
  "Telegram username": "Telegram-gebruikersnaam",
  "The account will be deleted.": "De rekening wordt verwijderd.",
  "The base currency cannot be changed because budgets or transactions already exist.": "De basisvaluta kan niet worden gewijzigd omdat er al budgetten of transacties bestaan.",
  "The budget category list for this month is empty.": "De lijst met budgetcategorieën voor deze maand is leeg.",
  "The category will be removed from this month's budget.": "De categorie wordt verwijderd uit het budget van deze maand.",
  "The payment is overdue. Premium access remains available through the grace-period date above.": "De betaling is te laat. Premium-toegang blijft beschikbaar tot en met de bovenstaande respijtperiodedatum.",
  "The purchase was not confirmed by the store. Try again.": "De aankoop werd niet bevestigd door de winkel. Probeer het opnieuw.",
  "The server did not respond in time. Try again.": "De server reageerde niet op tijd. Probeer het opnieuw.",
  "The transaction will be permanently deleted.": "De transactie wordt definitief verwijderd.",
  "The verified purchase is not active.": "De geverifieerde aankoop is niet actief.",
  "This account has no password. Password setup is handled separately.": "Dit account heeft geen wachtwoord. Het instellen van het wachtwoord wordt afzonderlijk afgehandeld.",
  "This purchase has already been received. Tap Restore purchases to restore the subscription.": "Deze aankoop is al ontvangen. Tik op Aankopen herstellen om het abonnement te herstellen.",
  "This purchase is linked to another MoneyDrive account. Sign in to the linked account or use a different App Store Sandbox account.": "Deze aankoop is gekoppeld aan een ander MoneyDrive-account. Meld u aan bij het gekoppelde account of gebruik een ander App Store Sandbox-account.",
  "This purchase period has already expired.": "Deze aankooptermijn is al verstreken.",
  "This purchase period has expired. Select a current subscription.": "Deze aankooptermijn is verstreken. Selecteer een huidig ​​abonnement.",
  "This takes less than a minute.": "Dit duurt minder dan een minuut.",
  "To goal: {{amount}}": "Naar doel: {{amount}}",
  "To renew with LiqPay, open the web version and complete a new checkout.": "Om te verlengen bij LiqPay, opent u de webversie en voltooit u een nieuwe betaling.",
  "Top categories by spending ({{currency}})": "Topcategorieën op basis van uitgaven ({{currency}})",
  "Total": "Totaal",
  "Total balance": "Totaal saldo",
  "Transactions": "Transacties",
  "Transfer": "Overdracht",
  "Type": "Type",
  "Type: {{type}}": "Type: {{type}}",
  "Unable to add the budget category (HTTP {{status}}).": "Kan de budgetcategorie (HTTP {{status}}) niet toevoegen.",
  "Unable to change password.": "Kan wachtwoord niet wijzigen.",
  "Unable to connect to the server.": "Kan geen verbinding maken met de server.",
  "Unable to create budget (HTTP {{status}}).": "Kan budget niet maken (HTTP {{status}}).",
  "Unable to create the account.": "Kan de rekening niet aanmaken.",
  "Unable to create the category (HTTP {{status}}).": "Kan de categorie (HTTP {{status}}) niet maken.",
  "Unable to delete the account.": "Kan de rekening niet verwijderen.",
  "Unable to delete the category (HTTP {{status}}).": "Kan de categorie (HTTP {{status}}) niet verwijderen.",
  "Unable to delete the transaction.": "Kan de transactie niet verwijderen.",
  "Unable to load accounts (HTTP {{status}}).": "Kan rekeningen niet laden (HTTP {{status}}).",
  "Unable to load accounts.": "Kan rekeningen niet laden.",
  "Unable to load budget (HTTP {{status}}).": "Kan budget niet laden (HTTP {{status}}).",
  "Unable to load budgets (HTTP {{status}}).": "Kan budgetten niet laden (HTTP {{status}}).",
  "Unable to load categories.": "Kan categorieën niet laden.",
  "Unable to load category icons (HTTP {{status}}).": "Kan categoriepictogrammen niet laden (HTTP {{status}}).",
  "Unable to load category icons.": "Kan categoriepictogrammen niet laden.",
  "Unable to load dashboard (HTTP {{status}}).": "Kan dashboard niet laden (HTTP {{status}}).",
  "Unable to load frequent categories.": "Kan frequente categorieën niet laden.",
  "Unable to load settings.": "Kan instellingen niet laden.",
  "Unable to load subscription products.": "Kan abonnementsproducten niet laden.",
  "Unable to load subscription status.": "Kan de abonnementsstatus niet laden.",
  "Unable to load transactions.": "Kan transacties niet laden.",
  "Unable to open onboarding.": "Kan onboarding niet openen.",
  "Unable to open the account.": "Kan de rekening niet openen.",
  "Unable to open the category for editing.": "Kan de categorie niet openen om te bewerken.",
  "Unable to open the category.": "Kan de categorie niet openen.",
  "Unable to open the transaction.": "Kan de transactie niet openen.",
  "Unable to prepare the expense form.": "Kan het onkostenformulier niet voorbereiden.",
  "Unable to remove the budget category (HTTP {{status}}).": "Kan de budgetcategorie (HTTP {{status}}) niet verwijderen.",
  "Unable to resend the email.": "Kan de e-mail niet opnieuw verzenden.",
  "Unable to save the profile.": "Kan het profiel niet opslaan.",
  "Unable to save the transaction.": "Kan de transactie niet opslaan.",
  "Unable to send request.": "Kan verzoek niet verzenden.",
  "Unable to update balance.": "Kan het saldo niet bijwerken.",
  "Unable to update the account.": "Kan de rekening niet bijwerken.",
  "Unable to update the budget category (HTTP {{status}}).": "Kan de budgetcategorie (HTTP {{status}}) niet bijwerken.",
  "Unable to update the category (HTTP {{status}}).": "Kan de categorie (HTTP {{status}}) niet bijwerken.",
  "Uncategorized": "Niet gecategoriseerd",
  "Until {{date}}": "Tot {{date}}",
  "Untitled": "Zonder titel",
  "Unverified": "Niet geverifieerd",
  "Update": "Bijwerken",
  "Verification": "Verificatie",
  "Verification token": "Verificatietoken",
  "Verified": "Geverifieerd",
  "Verify email": "E-mail verifiëren",
  "Verify with token": "Verifieer met een token",
  "Verifying email...": "E-mail verifiëren...",
  "View all": "Bekijk alles",
  "View budgets": "Bekijk budgetten",
  "We sent a verification email to {{email}}.": "We hebben een verificatie-e-mail gestuurd naar {{email}}.",
  "We usually respond within one business day.": "Wij reageren doorgaans binnen één werkdag.",
  "Your account and data are safe. Buy a new subscription to restore business features.": "Uw account en gegevens zijn veilig. Koop een nieuw abonnement om de zakelijke functies te herstellen.",
  "Your email": "Uw e-mail",
  "Your request has been sent to our support team.": "Uw verzoek is verzonden naar ons ondersteuningsteam.",
  "Your session has expired. Sign in again.": "Uw sessie is verlopen. Meld u opnieuw aan.",
  "categories": "categorieën",
  "the specified address": "het opgegeven adres",
  "{{amount}} remaining": "{{amount}} resterend",
  "{{percent}}% of plan": "{{percent}}% van het plan",
  "‹ Back": "‹ Terug",
  "Account \"{{name}}\" will be deleted.": "Rekening \"{{name}}\" wordt verwijderd.",
  "Category \"{{name}}\" will be deleted.": "Categorie \"{{name}}\" wordt verwijderd.",
  "Account deleted": "Account verwijderd",
  "Accounts, categories, budgets, transactions, transfers, settings, and access tokens will be deleted.": "Rekeningen, categorieën, budgetten, transacties, overboekingen, instellingen en toegangstokens worden verwijderd.",
  "Apple did not return credentials required for account deletion.": "Apple heeft de vereiste gegevens voor accountverwijdering niet teruggestuurd.",
  "Confirm your identity": "Bevestig je identiteit",
  "Danger zone": "Gevarenzone",
  "Delete MoneyDrive account": "MoneyDrive-account verwijderen",
  "Delete MoneyDrive account permanently": "MoneyDrive-account permanent verwijderen",
  "Deleting account...": "Account verwijderen...",
  "Deleting your account permanently removes your profile and financial data. This action cannot be undone.": "Als je je account permanent verwijdert, worden je profiel en financiële gegevens gewist. Dit kan niet ongedaan worden gemaakt.",
  "Deleting MoneyDrive does not cancel App Store billing. Cancel the subscription in Apple settings if you no longer want it.": "Het verwijderen van MoneyDrive stopt de facturering via de App Store niet. Zeg het abonnement op in de Apple-instellingen als je het niet meer wilt.",
  "Google Sign-In": "Inloggen met Google",
  "Manage Apple subscription": "Apple-abonnement beheren",
  "Sign in with Apple": "Log in met Apple",
  "Type DELETE to confirm": "Typ DELETE om te bevestigen",
  "Unable to open subscription management.": "Abonnementbeheer kon niet worden geopend.",
} as const;

export default nlNL;
