const pl = {
  "+{{amount}} above plan 🚀": "+{{amount}} powyżej planu 🚀",
  "30 days": "30 dni",
  "A subcategory cannot contain nested subcategories.": "Podkategoria nie może zawierać zagnieżdżonych podkategorii.",
  "Access denied.": "Odmowa dostępu.",
  "Access until: {{date}}": "Dostęp do: {{date}}",
  "Account": "Konto",
  "Account settings": "Ustawienia konta",
  "Account unavailable.": "Konto niedostępne.",
  "Account: {{name}}": "Konto: {{name}}",
  "Accounts": "Konta",
  "Across all accounts": "Na wszystkich kontach",
  "Actual": "Rzeczywisty",
  "Actual expense": "Rzeczywisty wydatek",
  "Actual income": "Rzeczywiste przychody",
  "Add": "Dodaj",
  "Add account": "Dodaj konto",
  "Add budget": "Dodaj budżet",
  "Add category": "Dodaj kategorię",
  "Add details": "Dodaj szczegóły",
  "Add subcategory": "Dodaj podkategorię",
  "Add to budget": "Dodaj do budżetu",
  "Add transaction": "Dodaj transakcję",
  "Add your first expense": "Dodaj swój pierwszy wydatek",
  "Adding...": "Dodawanie...",
  "All accounts": "Wszystkie konta",
  "All categories": "Wszystkie kategorie",
  "All recorded income categories": "Wszystkie zarejestrowane kategorie przychodów",
  "All steps completed": "Wszystkie kroki zakończone",
  "All time": "Cały czas",
  "All types": "Wszystkie typy",
  "Amount": "Kwota",
  "Analytics period": "Okres analityczny",
  "Another store purchase is already in progress.": "Kolejny zakup w sklepie już trwa.",
  "Apple did not return an identity token.": "Firma Apple nie zwróciła tokenu tożsamości.",
  "App Store saved {{actualProductId}} instead of {{requestedProductId}}. Check the current plan in App Store subscription settings.": "App Store zapisał {{actualProductId}} zamiast {{requestedProductId}}. Sprawdź aktualny plan w ustawieniach subskrypcji App Store.",
  "Auto-renew off": "Automatyczne odnawianie wyłączone",
  "Auto-renewal is off. Premium access remains available through the date above.": "Automatyczne odnawianie jest wyłączone. Dostęp premium pozostaje dostępny przez powyższy termin.",
  "Available plans": "Dostępne plany",
  "Back": "Wstecz",
  "Back to sign in": "Wróć do logowania",
  "Balance": "Saldo",
  "Balance update timed out. Check that the backend API is available.": "Upłynął limit czasu aktualizacji salda. Sprawdź, czy interfejs API zaplecza jest dostępny.",
  "Base currency": "Waluta bazowa",
  "Budget": "Budżet",
  "Budget category": "Kategoria budżetowa",
  "Budget changes and category editing will be added after the backend API is extended.": "Zmiany budżetu i edycja kategorii zostaną dodane po rozszerzeniu backendowego API.",
  "Budget details": "Szczegóły budżetu",
  "Budget not found.": "Nie znaleziono budżetu.",
  "Budget progress": "Postęp budżetów",
  "Budgets": "Budżety",
  "C": "C",
  "Cancel": "Anuluj",
  "Categories": "Kategorie",
  "Category": "Kategoria",
  "Category disabled": "Kategoria wyłączona",
  "Category enabled": "Kategoria włączona",
  "Category not found in the budget.": "Nie znaleziono kategorii w budżecie.",
  "Category unavailable.": "Kategoria niedostępna.",
  "Category \"{{name}}\" will become a group. It can no longer be selected in new transactions and budgets. Existing records will remain unchanged.": "Kategoria „{{name}}” stanie się grupą. Nie będzie już można jej wybierać w nowych transakcjach ani budżetach. Istniejące zapisy pozostaną niezmienione.",
  "Category will become a group": "Kategoria stanie się grupą",
  "Change balance": "Zmień saldo",
  "Change password": "Zmień hasło",
  "Check your email": "Sprawdź swój e-mail",
  "Checking authentication...": "Sprawdzam uwierzytelnianie...",
  "Choose an App Store or Google Play product below.": "Wybierz poniżej produkt App Store lub Google Play.",
  "Comment": "Komentarz",
  "Complete all password fields.": "Wypełnij wszystkie pola hasła.",
  "Confirm new password": "Potwierdź nowe hasło",
  "Confirm password": "Potwierdź hasło",
  "Contact support": "Skontaktuj się ze wsparciem",
  "Continue": "Kontynuuj",
  "Create": "Utwórz",
  "Create account": "Utwórz konto",
  "Creating...": "Tworzenie...",
  "Currency": "Waluta",
  "Current password": "Aktualne hasło",
  "Current plan": "Aktualny plan",
  "Custom": "Niestandardowy",
  "DONE": "ZROBIONE",
  "Dashboard": "Panel",
  "Date": "Data",
  "Date YYYY-MM-DD": "Data RRRR-MM-DD",
  "Delete": "Usuń",
  "Delete account?": "Usunąć konto?",
  "Delete category": "Usuń kategorię",
  "Delete category?": "Usunąć kategorię?",
  "Delete transaction": "Usuń transakcję",
  "Delete transaction?": "Usunąć transakcję?",
  "Deleting...": "Usuwanie...",
  "Description": "Opis",
  "Disabled": "Wyłączony",
  "Edit": "Edytuj",
  "Edit account": "Edytuj konto",
  "Edit transaction": "Edytuj transakcję",
  "Editing": "Redagowanie",
  "Email": "E-mail",
  "Email resent. Retry in {{seconds}} seconds.": "E-mail wysłany ponownie. Spróbuj ponownie za {{seconds}} sekund.",
  "Email sent. You can retry in about {{seconds}} seconds.": "E-mail wysłany. Możesz ponowić próbę za około {{seconds}} sekund.",
  "Email verification": "Weryfikacja e-mailowa",
  "Email verified. You can now sign in.": "Adres e-mail zweryfikowany. Możesz się teraz zalogować.",
  "Email was not sent. Try again in {{seconds}} seconds.": "E-mail nie został wysłany. Spróbuj ponownie za {{seconds}} sekund.",
  "End date": "Data końcowa",
  "Enter a category name.": "Wprowadź nazwę kategorii.",
  "Enter a date.": "Wpisz datę.",
  "Enter a message.": "Wpisz wiadomość.",
  "Enter a new password.": "Wprowadź nowe hasło.",
  "Enter a subject.": "Wpisz temat.",
  "Enter a valid amount.": "Wprowadź prawidłową kwotę.",
  "Enter a valid balance.": "Wprowadź prawidłowe saldo.",
  "Enter a valid email address.": "Wpisz prawidłowy adres e-mail.",
  "Enter a valid planned amount greater than 0.": "Wprowadź prawidłową planowaną kwotę większą niż 0.",
  "Enter an account name.": "Wprowadź nazwę konta.",
  "Enter an amount greater than zero.": "Wprowadź kwotę większą od zera.",
  "Enter your email": "Wpisz swój adres e-mail",
  "Enter your email, name, and password.": "Wpisz swój adres e-mail, imię i nazwisko oraz hasło.",
  "Enter your email.": "Wpisz swój adres e-mail.",
  "Enter your name": "Wpisz swoje imię i nazwisko",
  "Expense": "Wydatek",
  "Expense categories": "Kategorie wydatków",
  "Expense categories are not available yet.": "Kategorie wydatków nie są jeszcze dostępne.",
  "Expense not submitted: complete the required fields.": "Wydatek nie został przesłany: wypełnij wymagane pola.",
  "Expenses": "Wydatki",
  "Expenses and income": "Wydatki i przychody",
  "Expenses this period": "Wydatki w tym okresie",
  "Fill password": "Wypełnij hasło",
  "Forgot password?": "Zapomniałeś hasła?",
  "Free": "Bezpłatny",
  "From {{date}}": "Od {{date}}",
  "Go to sign in": "Przejdź do logowania",
  "Goal reached! 🎉": "Cel osiągnięty! 🎉",
  "Google Sign-In is not configured for this build.": "Logowanie Google nie jest skonfigurowane dla tej kompilacji.",
  "Google did not return an ID token.": "Google nie zwrócił tokenu identyfikacyjnego.",
  "Group": "Grupa",
  "Hide": "Ukrywać",
  "Hide form": "Ukryj formularz",
  "Hide password": "Ukryj hasło",
  "Home": "Start",
  "I have a token": "Mam token",
  "Icon": "Ikona",
  "If the account exists, an email has been sent.": "Jeśli konto istnieje, wiadomość e-mail została wysłana.",
  "If the account exists, an email has been sent. Retry in {{seconds}} seconds.": "Jeśli konto istnieje, wiadomość e-mail została wysłana. Spróbuj ponownie za {{seconds}} sekund.",
  "If the email contains a production link, paste the token manually for local testing.": "Jeśli wiadomość e-mail zawiera link produkcyjny, wklej token ręcznie w celu przeprowadzenia lokalnych testów.",
  "Income": "Przychody",
  "Income categories": "Kategorie przychodów",
  "Income categories are not available yet.": "Kategorie przychodów nie są jeszcze dostępne.",
  "Income this period": "Przychody w okresie",
  "Initial setup": "Konfiguracja wstępna",
  "Interface language": "Język interfejsu",
  "Invalid accounts response format.": "Nieprawidłowy format odpowiedzi kont.",
  "Invalid budget response format.": "Nieprawidłowy format odpowiedzi budżetowej.",
  "Keep an eye on all of your balances.": "Miej oko na wszystkie swoje salda.",
  "Language and base currency": "Język i waluta bazowa",
  "LiqPay subscription can be cancelled only in the web version of the app.": "Abonament LiqPay można anulować wyłącznie w internetowej wersji aplikacji.",
  "Loading accounts...": "Ładowanie kont...",
  "Loading budget...": "Ładowanie budżetu...",
  "Loading budgets...": "Ładowanie budżetów...",
  "Loading categories...": "Ładowanie kategorii...",
  "Loading dashboard...": "Ładowanie panelu...",
  "Loading icons...": "Ładowanie ikon...",
  "Loading onboarding...": "Ładowanie wprowadzenia...",
  "Loading settings...": "Ładowanie ustawień...",
  "Loading store products...": "Ładowanie produktów w sklepie...",
  "Loading subscription status...": "Ładowanie stanu subskrypcji...",
  "Loading...": "Załadunek...",
  "Log in": "Zaloguj się",
  "Login with Google": "Zaloguj się przez Google",
  "Logout": "Wyloguj się",
  "Manage on web": "Zarządzaj w internecie",
  "Manage premium access": "Zarządzaj dostępem premium",
  "Manage subscription": "Zarządzaj subskrypcją",
  "Maximum category depth is 2 levels": "Maksymalna głębokość kategorii wynosi 2 poziomy",
  "Maximum category depth is 2 levels.": "Maksymalna głębokość kategorii wynosi 2 poziomy.",
  "Message": "Wiadomość",
  "Missing Android subscription offer token for selected product.": "Brak tokena oferty subskrypcji Androida dla wybranego produktu.",
  "Missing account ID.": "Brak identyfikatora konta.",
  "Missing budgetId.": "Brak identyfikatora budżetu.",
  "Missing reset token.": "Brak tokena resetowania.",
  "MoneyDrive.me": "MoneyDrive.me",
  "Month": "Miesiąc",
  "More": "Więcej",
  "More service sections": "Więcej sekcji usług",
  "Most frequent": "Najczęściej",
  "Name": "Nazwa",
  "New account": "Nowe konto",
  "New balance": "Nowe saldo",
  "New category": "Nowa kategoria",
  "New email awaiting verification: {{email}}": "Nowy e-mail oczekujący na weryfikację: {{email}}",
  "New password": "Nowe hasło",
  "New planned amount": "Nowa planowana kwota",
  "No App Store Sandbox account is connected on this device. Add a sandbox tester in Settings > App Store > Sandbox Account.": "Na tym urządzeniu nie jest połączone żadne konto App Store Sandbox. Dodaj testera piaskownicy w Ustawieniach > App Store > Konto piaskownicy.",
  "No account": "Brak konta",
  "No account data.": "Brak danych konta.",
  "No accounts.": "Brak kont.",
  "No active purchases found.": "Nie znaleziono aktywnych zakupów.",
  "No active store source": "Brak aktywnego źródła sklepu",
  "No budget has been created for the selected month.": "Na wybrany miesiąc nie utworzono budżetu.",
  "No budgets for the selected period.": "Brak budżetów na wybrany okres.",
  "No budgets found yet.": "Nie znaleziono jeszcze żadnych budżetów.",
  "No categories available to add.": "Brak kategorii do dodania.",
  "No categories found for the selected type.": "Nie znaleziono kategorii dla wybranego typu.",
  "No categories found.": "Nie znaleziono żadnych kategorii.",
  "No categories.": "Brak kategorii.",
  "No data for the selected period.": "Brak danych dla wybranego okresu.",
  "No data.": "Brak danych.",
  "No external management action is available.": "Nie są dostępne żadne zewnętrzne działania zarządcze.",
  "No period selected": "Nie wybrano okresu",
  "No transaction data.": "Brak danych transakcji.",
  "No transactions yet.": "Nie ma jeszcze żadnych transakcji.",
  "Not enough data to add the category.": "Za mało danych, aby dodać kategorię.",
  "Not set": "Nie ustawiono",
  "Note": "Notatka",
  "Open": "Otwórz",
  "Open App Store account settings and choose Subscriptions.": "Otwórz ustawienia konta App Store i wybierz Subskrypcje.",
  "Open the subscription provider account settings to manage this plan.": "Otwórz ustawienia konta dostawcy subskrypcji, aby zarządzać tym planem.",
  "Overspent by {{amount}}": "Przekroczenie kwoty {{amount}}",
  "Parent: {{name}}": "Rodzic: {{name}}",
  "Password": "Hasło",
  "Password changed.": "Hasło zmienione.",
  "Password recovery": "Odzyskiwanie hasła",
  "Password updated. You can now sign in.": "Hasło zaktualizowane. Możesz się teraz zalogować.",
  "Passwords do not match.": "Hasła nie pasują.",
  "Paste the verification token.": "Wklej token weryfikacyjny.",
  "Period: {{period}}": "Okres: {{period}}",
  "Plan ({{currency}})": "Plan ({{currency}})",
  "Plan / actual / remaining by category": "Plan / stan faktyczny / pozostały według kategorii",
  "Plan {{plan}} · Actual {{actual}}": "Plan {{plan}} · Rzeczywisty {{actual}}",
  "Plans and billing": "Plany i rozliczenia",
  "Planned amount ({{currency}})": "Planowana kwota ({{currency}})",
  "Planned expense": "Planowany wydatek",
  "Planned income": "Planowane przychody",
  "Popular categories": "Popularne kategorie",
  "Premium": "Premium",
  "Premium is active.": "Premium jest aktywne.",
  "Premium is active. The plan change will take effect on the next App Store renewal.": "Premium jest aktywne. Zmiana planu zacznie obowiązywać przy następnym odnowieniu w App Store.",
  "Processing...": "Przetwarzanie...",
  "Product temporarily unavailable.": "Produkt chwilowo niedostępny.",
  "Product: {{product}}": "Produkt: {{product}}",
  "Products for {{platform}}": "Produkty dla {{platform}}",
  "Profile": "Profil",
  "Profile and security": "Profil i bezpieczeństwo",
  "Profile saved.": "Profil został zapisany.",
  "Profile, language, and security": "Profil, język i bezpieczeństwo",
  "Purchase not confirmed. Try again.": "Zakup niepotwierdzony. Spróbuj ponownie.",
  "Recent transactions": "Ostatnie transakcje",
  "Registration": "Rejestracja",
  "Remaining": "Pozostało",
  "Renewal canceled": "Odnowienie anulowane",
  "Request failed (HTTP {{status}}).": "Żądanie nie powiodło się (HTTP {{status}}).",
  "Resend email": "Wyślij ponownie e-mail",
  "Restore purchases": "Przywróć zakupy",
  "Restored purchases: {{count}}.": "Przywrócone zakupy: {{count}}.",
  "Restoring...": "Przywracam...",
  "Retry": "Spróbuj ponownie",
  "Root level": "Poziom główny",
  "Runtime category tree": "Drzewo kategorii runtime",
  "Save": "Zapisz",
  "Save and continue": "Zapisz i kontynuuj",
  "Save balance": "Zapisz saldo",
  "Save password": "Zapisz hasło",
  "Saving...": "Zapisywanie...",
  "Segments show amounts by category.": "Segmenty pokazują kwoty według kategorii.",
  "Select": "Wybierz",
  "Select a base currency.": "Wybierz walutę bazową.",
  "Select a category": "Wybierz kategorię",
  "Select a category and an account.": "Wybierz kategorię i konto.",
  "Select a category.": "Wybierz kategorię.",
  "Select a currency": "Wybierz walutę",
  "Select a date": "Wybierz datę",
  "Select a language": "Wybierz język",
  "Select a subcategory. A parent category cannot be added.": "Wybierz podkategorię. Nie można dodać kategorii nadrzędnej.",
  "Select account": "Wybierz konto",
  "Select an account.": "Wybierz konto.",
  "Select an icon from the shared catalog": "Wybierz ikonę z udostępnionego katalogu",
  "Select an interface language.": "Wybierz język interfejsu.",
  "Select the interface language and analytics currency.": "Wybierz język interfejsu i walutę analityczną.",
  "Send a request": "Wyślij zapytanie",
  "Send email": "Wyślij e-mail",
  "Send request": "Wyślij zgłoszenie",
  "Sending...": "Wysyłanie...",
  "Show": "Pokaż",
  "Show password": "Pokaż hasło",
  "Settings": "Ustawienia",
  "Sign in": "Zaloguj się",
  "Signing in with Google...": "Logowanie się w Google...",
  "Signing in...": "Logowanie...",
  "Some store products are not available yet: {{products}}.": "Niektóre produkty sklepu nie są jeszcze dostępne: {{products}}.",
  "Spending across all accounts": "Wydatki na wszystkich kontach",
  "Start date": "Data rozpoczęcia",
  "Step {{current}} of 2: {{screen}}": "Krok {{current}} z 2: {{screen}}",
  "Store products are available only on iOS and Android.": "Produkty Sklepu dostępne są wyłącznie na systemach iOS i Android.",
  "Store products are not available yet. Please check App Store or Google Play product setup.": "Produkty sklepu nie są jeszcze dostępne. Sprawdź konfigurację produktu w App Store lub Google Play.",
  "Store purchases are available only on iOS and Android.": "Zakupy w sklepie są dostępne wyłącznie na urządzeniach z systemem iOS i Android.",
  "Store purchases require iOS or Android": "Zakupy w sklepie wymagają systemu iOS lub Android",
  "Store transaction is missing orderId.": "W transakcji sklepu brakuje orderId.",
  "Store transaction is missing originalTransactionId.": "W transakcji sklepu brakuje originalTransactionId.",
  "Store transaction is missing packageName.": "W transakcji sklepu brakuje packageName.",
  "Store transaction is missing purchaseToken.": "W transakcji sklepu brakuje purchaseToken.",
  "Store transaction is missing signed payload.": "W transakcji sklepu brakuje podpisanego ładunku.",
  "Store transaction is missing transactionId.": "W transakcji sklepu brakuje transactionId.",
  "Subcategories": "Podkategorie",
  "Subject": "Temat",
  "Subscribe": "Subskrybuj",
  "Subscription": "Subskrypcja",
  "Subscription management": "Zarządzanie subskrypcjami",
  "Subscriptions": "Subskrypcje",
  "Support": "Wsparcie",
  "Tap the icon to select": "Naciśnij ikonę, aby wybrać",
  "Telegram username": "Nazwa użytkownika Telegram",
  "The account will be deleted.": "Konto zostanie usunięte.",
  "The base currency cannot be changed because budgets or transactions already exist.": "Waluty bazowej nie można zmienić, ponieważ istnieją już budżety lub transakcje.",
  "The budget category list for this month is empty.": "Lista kategorii budżetu na ten miesiąc jest pusta.",
  "The category will be removed from this month's budget.": "Kategoria zostanie usunięta z budżetu na ten miesiąc.",
  "The payment is overdue. Premium access remains available through the grace-period date above.": "Płatność jest zaległa. Dostęp Premium pozostanie aktywny do wskazanej powyżej daty zakończenia okresu karencji.",
  "The purchase was not confirmed by the store. Try again.": "Zakup nie został potwierdzony przez sklep. Spróbuj ponownie.",
  "The server did not respond in time. Try again.": "Serwer nie odpowiedział na czas. Spróbuj ponownie.",
  "The transaction will be permanently deleted.": "Transakcja zostanie trwale usunięta.",
  "The verified purchase is not active.": "Zweryfikowany zakup nie jest aktywny.",
  "This account has no password. Password setup is handled separately.": "To konto nie ma hasła. Konfiguracja hasła odbywa się osobno.",
  "This purchase has already been received. Tap Restore purchases to restore the subscription.": "Ten zakup został już otrzymany. Kliknij Przywróć zakupy, aby przywrócić subskrypcję.",
  "This purchase is linked to another MoneyDrive account. Sign in to the linked account or use a different App Store Sandbox account.": "Ten zakup jest powiązany z innym kontem MoneyDrive. Zaloguj się na połączone konto lub użyj innego konta App Store Sandbox.",
  "This purchase period has already expired.": "Ten okres zakupu już minął.",
  "This purchase period has expired. Select a current subscription.": "Ten okres zakupu minął. Wybierz bieżącą subskrypcję.",
  "This takes less than a minute.": "Zajmuje to mniej niż minutę.",
  "To goal: {{amount}}": "Do celu: {{amount}}",
  "To renew with LiqPay, open the web version and complete a new checkout.": "Aby odnowić za pomocą LiqPay, otwórz wersję internetową i dokończ nową transakcję.",
  "Top categories by spending ({{currency}})": "Najpopularniejsze kategorie według wydatków ({{currency}})",
  "Total": "Razem",
  "Total balance": "Łączne saldo",
  "Transactions": "Transakcje",
  "Transfer": "Przelew",
  "Type": "Typ",
  "Type: {{type}}": "Typ: {{type}}",
  "Unable to add the budget category (HTTP {{status}}).": "Nie można dodać kategorii budżetu (HTTP {{status}}).",
  "Unable to change password.": "Nie można zmienić hasła.",
  "Unable to connect to the server.": "Nie można połączyć się z serwerem.",
  "Unable to create budget (HTTP {{status}}).": "Nie można utworzyć budżetu (HTTP {{status}}).",
  "Unable to create the account.": "Nie można utworzyć konta.",
  "Unable to create the category (HTTP {{status}}).": "Nie można utworzyć kategorii (HTTP {{status}}).",
  "Unable to delete the account.": "Nie można usunąć konta.",
  "Unable to delete the category (HTTP {{status}}).": "Nie można usunąć kategorii (HTTP {{status}}).",
  "Unable to delete the transaction.": "Nie można usunąć transakcji.",
  "Unable to load accounts (HTTP {{status}}).": "Nie można załadować kont (HTTP {{status}}).",
  "Unable to load accounts.": "Nie można wczytać kont.",
  "Unable to load budget (HTTP {{status}}).": "Nie można załadować budżetu (HTTP {{status}}).",
  "Unable to load budgets (HTTP {{status}}).": "Nie można załadować budżetów (HTTP {{status}}).",
  "Unable to load categories.": "Nie można wczytać kategorii.",
  "Unable to load category icons (HTTP {{status}}).": "Nie można załadować ikon kategorii (HTTP {{status}}).",
  "Unable to load category icons.": "Nie można załadować ikon kategorii.",
  "Unable to load dashboard (HTTP {{status}}).": "Nie można załadować pulpitu nawigacyjnego (HTTP {{status}}).",
  "Unable to load frequent categories.": "Nie można załadować częstych kategorii.",
  "Unable to load settings.": "Nie można wczytać ustawień.",
  "Unable to load subscription products.": "Nie można załadować produktów objętych subskrypcją.",
  "Unable to load subscription status.": "Nie można wczytać stanu subskrypcji.",
  "Unable to load transactions.": "Nie można wczytać transakcji.",
  "Unable to open onboarding.": "Nie można otworzyć wprowadzenia.",
  "Unable to open the account.": "Nie można otworzyć konta.",
  "Unable to open the category for editing.": "Nie można otworzyć kategorii do edycji.",
  "Unable to open the category.": "Nie można otworzyć kategorii.",
  "Unable to open the transaction.": "Nie można otworzyć transakcji.",
  "Unable to prepare the expense form.": "Nie można przygotować formularza wydatku.",
  "Unable to remove the budget category (HTTP {{status}}).": "Nie można usunąć kategorii budżetu (HTTP {{status}}).",
  "Unable to resend the email.": "Nie można ponownie wysłać e-maila.",
  "Unable to save the profile.": "Nie można zapisać profilu.",
  "Unable to save the transaction.": "Nie można zapisać transakcji.",
  "Unable to send request.": "Nie można wysłać żądania.",
  "Unable to update balance.": "Nie można zaktualizować salda.",
  "Unable to update the account.": "Nie można zaktualizować konta.",
  "Unable to update the budget category (HTTP {{status}}).": "Nie można zaktualizować kategorii budżetu (HTTP {{status}}).",
  "Unable to update the category (HTTP {{status}}).": "Nie można zaktualizować kategorii (HTTP {{status}}).",
  "Uncategorized": "Bez kategorii",
  "Until {{date}}": "Aż do {{date}}",
  "Untitled": "Bez nazwy",
  "Unverified": "Niesprawdzony",
  "Update": "Aktualizuj",
  "Verification": "Weryfikacja",
  "Verification token": "Token weryfikacyjny",
  "Verified": "Zweryfikowano",
  "Verify email": "Zweryfikuj adres e-mail",
  "Verify with token": "Zweryfikuj za pomocą tokena",
  "Verifying email...": "Weryfikuję adres e-mail...",
  "View all": "Zobacz wszystkie",
  "View budgets": "Zobacz budżety",
  "We sent a verification email to {{email}}.": "Wysłaliśmy e-mail weryfikacyjny na adres {{email}}.",
  "We usually respond within one business day.": "Zwykle odpowiadamy w ciągu jednego dnia roboczego.",
  "Your account and data are safe. Buy a new subscription to restore business features.": "Twoje konto i dane są bezpieczne. Kup nową subskrypcję, aby przywrócić funkcje biznesowe.",
  "Your email": "Twój e-mail",
  "Your request has been sent to our support team.": "Twoje zgłoszenie zostało wysłane do naszego zespołu wsparcia.",
  "Your session has expired. Sign in again.": "Twoja sesja wygasła. Zaloguj się ponownie.",
  "categories": "kategorie",
  "the specified address": "podany adres",
  "{{amount}} remaining": "Pozostało {{amount}}",
  "{{percent}}% of plan": "{{percent}}% planu",
  "‹ Back": "‹ Wstecz",
  "Account \"{{name}}\" will be deleted.": "Konto „{{name}}” zostanie usunięte.",
  "Category \"{{name}}\" will be deleted.": "Kategoria „{{name}}” zostanie usunięta.",
} as const;

export default pl;
