const ptBR = {
  "+{{amount}} above plan 🚀": "+{{amount}} acima do plano 🚀",
  "30 days": "30 dias",
  "A subcategory cannot contain nested subcategories.": "Uma subcategoria não pode conter subcategorias aninhadas.",
  "Access denied.": "Acesso negado.",
  "Access until: {{date}}": "Acesso até: {{date}}",
  "Account": "Conta",
  "Account settings": "Configurações de Conta",
  "Account unavailable.": "Conta indisponível.",
  "Account: {{name}}": "Conta: {{name}}",
  "Accounts": "Contas",
  "Across all accounts": "Em todas as contas",
  "Actual": "Real",
  "Actual expense": "Despesa real",
  "Actual income": "Receita real",
  "Add": "Adicionar",
  "Add account": "Adicionar conta",
  "Add budget": "Adicionar orçamento",
  "Add category": "Adicionar categoria",
  "Add details": "Adicionar detalhes",
  "Add subcategory": "Adicionar subcategoria",
  "Add to budget": "Adicionar ao orçamento",
  "Add transaction": "Adicionar transação",
  "Add your first expense": "Adicione sua primeira despesa",
  "Adding...": "Adicionando...",
  "All accounts": "Todas as contas",
  "All categories": "Todas as categorias",
  "All recorded income categories": "Todas as categorias de receitas registradas",
  "All steps completed": "Todas as etapas concluídas",
  "All time": "Todo o tempo",
  "All types": "Todos os tipos",
  "Amount": "Valor",
  "Analytics period": "Período de análise",
  "Another store purchase is already in progress.": "Outra compra na loja já está em andamento.",
  "Apple did not return an identity token.": "A Apple não retornou um token de identidade.",
  "App Store saved {{actualProductId}} instead of {{requestedProductId}}. Check the current plan in App Store subscription settings.": "A App Store salvou {{actualProductId}} em vez de {{requestedProductId}}. Verifique o plano atual nas configurações de assinatura da App Store.",
  "Auto-renew off": "Renovação automática desativada",
  "Auto-renewal is off. Premium access remains available through the date above.": "A renovação automática está desativada. O acesso premium permanece disponível até a data acima.",
  "Available plans": "Planos disponíveis",
  "Back": "Voltar",
  "Back to sign in": "Voltar para fazer login",
  "Balance": "Saldo",
  "Balance update timed out. Check that the backend API is available.": "A atualização do saldo expirou. Verifique se a API de back-end está disponível.",
  "Base currency": "Moeda base",
  "Budget": "Orçamento",
  "Budget category": "Categoria de orçamento",
  "Budget changes and category editing will be added after the backend API is extended.": "Alterações no orçamento e edição de categorias serão adicionadas após a extensão da API de back-end.",
  "Budget details": "Detalhes do orçamento",
  "Budget not found.": "Orçamento não encontrado.",
  "Budget progress": "Progresso do orçamento",
  "Budgets": "Orçamentos",
  "C": "C",
  "Cancel": "Cancelar",
  "Categories": "Categorias",
  "Category": "Categoria",
  "Category disabled": "Categoria desativada",
  "Category enabled": "Categoria ativada",
  "Category not found in the budget.": "Categoria não encontrada no orçamento.",
  "Category unavailable.": "Categoria indisponível.",
  "Category \"{{name}}\" will become a group. It can no longer be selected in new transactions and budgets. Existing records will remain unchanged.": "A categoria \"{{name}}\" se tornará um grupo. Ela não poderá mais ser selecionada em novas transações e orçamentos. Os registros existentes permanecerão inalterados.",
  "Category will become a group": "A categoria se tornará um grupo",
  "Change balance": "Alterar saldo",
  "Change password": "Alterar a senha",
  "Check your email": "Verifique seu e-mail",
  "Checking authentication...": "Verificando autenticação...",
  "Choose an App Store or Google Play product below.": "Escolha um produto da App Store ou do Google Play abaixo.",
  "Comment": "Comentário",
  "Complete all password fields.": "Preencha todos os campos de senha.",
  "Confirm new password": "Confirme a nova senha",
  "Confirm password": "Confirmar senha",
  "Contact support": "Entrar em contato com o suporte",
  "Continue": "Continuar",
  "Create": "Criar",
  "Create account": "Criar uma conta",
  "Creating...": "Criando...",
  "Currency": "Moeda",
  "Current password": "Senha atual",
  "Current plan": "Plano atual",
  "Custom": "Personalizado",
  "DONE": "FEITO",
  "Dashboard": "Painel",
  "Date": "Data",
  "Date YYYY-MM-DD": "Data AAAA-MM-DD",
  "Delete": "Excluir",
  "Delete account?": "Excluir conta?",
  "Delete category": "Excluir categoria",
  "Delete category?": "Excluir categoria?",
  "Delete transaction": "Excluir transação",
  "Delete transaction?": "Excluir transação?",
  "Deleting...": "Excluindo...",
  "Description": "Descrição",
  "Disabled": "Desativado",
  "Edit": "Editar",
  "Edit account": "Editar conta",
  "Edit transaction": "Editar transação",
  "Editing": "Edição",
  "Email": "E-mail",
  "Email resent. Retry in {{seconds}} seconds.": "E-mail reenviado. Tente novamente em {{seconds}} segundos.",
  "Email sent. You can retry in about {{seconds}} seconds.": "E-mail enviado. Você pode tentar novamente em cerca de {{seconds}} segundos.",
  "Email verification": "Verificação de e-mail",
  "Email verified. You can now sign in.": "E-mail verificado. Agora você pode fazer login.",
  "Email was not sent. Try again in {{seconds}} seconds.": "O e-mail não foi enviado. Tente novamente em {{seconds}} segundos.",
  "End date": "Data de término",
  "Enter a category name.": "Insira um nome de categoria.",
  "Enter a date.": "Insira uma data.",
  "Enter a message.": "Digite uma mensagem.",
  "Enter a new password.": "Digite uma nova senha.",
  "Enter a subject.": "Insira um assunto.",
  "Enter a valid amount.": "Insira um valor válido.",
  "Enter a valid balance.": "Insira um saldo válido.",
  "Enter a valid email address.": "Insira um endereço de e-mail válido.",
  "Enter a valid planned amount greater than 0.": "Insira um valor planejado válido maior que 0.",
  "Enter an account name.": "Insira um nome de conta.",
  "Enter an amount greater than zero.": "Insira um valor maior que zero.",
  "Enter your email": "Digite seu e-mail",
  "Enter your email, name, and password.": "Digite seu e-mail, nome e senha.",
  "Enter your email.": "Digite seu e-mail.",
  "Enter your name": "Digite seu nome",
  "Expense": "Despesa",
  "Expense categories": "Categorias de despesas",
  "Expense categories are not available yet.": "As categorias de despesas ainda não estão disponíveis.",
  "Expense not submitted: complete the required fields.": "Despesa não enviada: preencha os campos obrigatórios.",
  "Expenses": "Despesas",
  "Expenses and income": "Despesas e receitas",
  "Expenses this period": "Despesas neste período",
  "Fill password": "Preencha a senha",
  "Forgot password?": "Esqueceu a senha?",
  "Free": "Grátis",
  "From {{date}}": "De {{date}}",
  "Go to sign in": "Ir para o login",
  "Goal reached! 🎉": "Meta alcançada! 🎉",
  "Google Sign-In is not configured for this build.": "O Login do Google não está configurado para esta versão.",
  "Google did not return an ID token.": "O Google não retornou um token de ID.",
  "Group": "Grupo",
  "Hide": "Ocultar",
  "Hide form": "Ocultar formulário",
  "Hide password": "Ocultar senha",
  "Home": "Início",
  "I have a token": "Eu tenho um token",
  "Icon": "Ícone",
  "If the account exists, an email has been sent.": "Se a conta existir, um email foi enviado.",
  "If the account exists, an email has been sent. Retry in {{seconds}} seconds.": "Se a conta existir, um email foi enviado. Tente novamente em {{seconds}} segundos.",
  "If the email contains a production link, paste the token manually for local testing.": "Se o email contiver um link de produção, cole o token manualmente para teste local.",
  "Income": "Receitas",
  "Income categories": "Categorias de receitas",
  "Income categories are not available yet.": "As categorias de receitas ainda não estão disponíveis.",
  "Income this period": "Receitas neste período",
  "Initial setup": "Configuração inicial",
  "Interface language": "Idioma da interface",
  "Invalid accounts response format.": "Formato de resposta de contas inválido.",
  "Invalid budget response format.": "Formato de resposta de orçamento inválido.",
  "Keep an eye on all of your balances.": "Fique de olho em todos os seus saldos.",
  "Language and base currency": "Idioma e moeda base",
  "LiqPay subscription can be cancelled only in the web version of the app.": "A assinatura do LiqPay só pode ser cancelada na versão web do aplicativo.",
  "Loading accounts...": "Carregando contas...",
  "Loading budget...": "Carregando orçamento...",
  "Loading budgets...": "Carregando orçamentos...",
  "Loading categories...": "Carregando categorias...",
  "Loading dashboard...": "Carregando painel...",
  "Loading icons...": "Carregando ícones...",
  "Loading onboarding...": "Carregando configuração inicial...",
  "Loading settings...": "Carregando configurações...",
  "Loading store products...": "Carregando produtos da loja...",
  "Loading subscription status...": "Carregando status da assinatura...",
  "Loading...": "Carregando...",
  "Log in": "Entrar",
  "Login with Google": "Entrar com o Google",
  "Logout": "Sair",
  "Manage on web": "Gerenciar na web",
  "Manage premium access": "Gerenciar acesso premium",
  "Manage subscription": "Gerenciar assinatura",
  "Maximum category depth is 2 levels": "A profundidade máxima da categoria é de 2 níveis",
  "Maximum category depth is 2 levels.": "A profundidade máxima da categoria é de 2 níveis.",
  "Message": "Mensagem",
  "Missing Android subscription offer token for selected product.": "Falta o token de oferta de assinatura do Android para o produto selecionado.",
  "Missing account ID.": "ID da conta ausente.",
  "Missing budgetId.": "ID do orçamento ausente.",
  "Missing reset token.": "Token de redefinição ausente.",
  "MoneyDrive.me": "MoneyDrive.me",
  "Month": "Mês",
  "More": "Mais",
  "More service sections": "Mais seções de serviço",
  "Most frequent": "Mais frequente",
  "Name": "Nome",
  "New account": "Nova conta",
  "New balance": "Novo saldo",
  "New category": "Nova categoria",
  "New email awaiting verification: {{email}}": "Novo e-mail aguardando verificação: {{email}}",
  "New password": "Nova Senha",
  "New planned amount": "Novo valor planejado",
  "No App Store Sandbox account is connected on this device. Add a sandbox tester in Settings > App Store > Sandbox Account.": "Nenhuma conta do App Store Sandbox está conectada neste dispositivo. Adicione um testador sandbox em Configurações > App Store > Conta Sandbox.",
  "No account": "Nenhuma conta",
  "No account data.": "Nenhum dado da conta.",
  "No accounts.": "Sem contas.",
  "No active purchases found.": "Nenhuma compra ativa encontrada.",
  "No active store source": "Nenhuma loja ativa",
  "No budget has been created for the selected month.": "Nenhum orçamento foi criado para o mês selecionado.",
  "No budgets for the selected period.": "Não há orçamentos para o período selecionado.",
  "No budgets found yet.": "Nenhum orçamento encontrado ainda.",
  "No categories available to add.": "Nenhuma categoria disponível para adicionar.",
  "No categories found for the selected type.": "Nenhuma categoria encontrada para o tipo selecionado.",
  "No categories found.": "Nenhuma categoria encontrada.",
  "No categories.": "Sem categorias.",
  "No data for the selected period.": "Não há dados para o período selecionado.",
  "No data.": "Sem dados.",
  "No external management action is available.": "Nenhuma ação de gestão externa está disponível.",
  "No period selected": "Nenhum período selecionado",
  "No transaction data.": "Nenhum dado de transação.",
  "No transactions yet.": "Nenhuma transação ainda.",
  "Not enough data to add the category.": "Não há dados suficientes para adicionar a categoria.",
  "Not set": "Não definido",
  "Note": "Observação",
  "Open": "Abrir",
  "Open App Store account settings and choose Subscriptions.": "Abra as configurações da conta da App Store e escolha Assinaturas.",
  "Open the subscription provider account settings to manage this plan.": "Abra as configurações da conta do provedor de assinatura para gerenciar este plano.",
  "Overspent by {{amount}}": "Excedido em {{amount}}",
  "Parent: {{name}}": "Categoria principal: {{name}}",
  "Password": "Senha",
  "Password changed.": "Senha alterada.",
  "Password recovery": "Recuperação de senha",
  "Password updated. You can now sign in.": "Senha atualizada. Agora você pode fazer login.",
  "Passwords do not match.": "As senhas não coincidem.",
  "Paste the verification token.": "Cole o token de verificação.",
  "Period: {{period}}": "Período: {{period}}",
  "Plan ({{currency}})": "Plano ({{currency}})",
  "Plan / actual / remaining by category": "Planejado/real/restante por categoria",
  "Plan {{plan}} · Actual {{actual}}": "Planejado {{plan}} · Realizado {{actual}}",
  "Plans and billing": "Planos e faturamento",
  "Planned amount ({{currency}})": "Valor planejado ({{currency}})",
  "Planned expense": "Despesa planejada",
  "Planned income": "Receita planejada",
  "Popular categories": "Categorias populares",
  "Premium": "Premium",
  "Premium is active.": "O Premium está ativo.",
  "Premium is active. The plan change will take effect on the next App Store renewal.": "O Premium está ativo. A mudança de plano entrará em vigor na próxima renovação da App Store.",
  "Processing...": "Processamento...",
  "Product temporarily unavailable.": "Produto temporariamente indisponível.",
  "Product: {{product}}": "Produto: {{product}}",
  "Products for {{platform}}": "Produtos para {{platform}}",
  "Profile": "Perfil",
  "Profile and security": "Perfil e segurança",
  "Profile saved.": "Perfil salvo.",
  "Profile, language, and security": "Perfil, idioma e segurança",
  "Purchase not confirmed. Try again.": "Compra não confirmada. Tente novamente.",
  "Recent transactions": "Transações recentes",
  "Registration": "Cadastro",
  "Remaining": "Restante",
  "Renewal canceled": "Renovação cancelada",
  "Request failed (HTTP {{status}}).": "Falha na solicitação (HTTP {{status}}).",
  "Resend email": "Reenviar e-mail",
  "Restore purchases": "Restaurar compras",
  "Restored purchases: {{count}}.": "Compras restauradas: {{count}}.",
  "Restoring...": "Restaurando...",
  "Retry": "Tentar novamente",
  "Root level": "Nível raiz",
  "Runtime category tree": "Árvore de categorias de tempo de execução",
  "Save": "Salvar",
  "Save and continue": "Salvar e continuar",
  "Save balance": "Salvar saldo",
  "Save password": "Salvar senha",
  "Saving...": "Salvando...",
  "Segments show amounts by category.": "Os segmentos mostram valores por categoria.",
  "Select": "Selecione",
  "Select a base currency.": "Selecione uma moeda base.",
  "Select a category": "Selecione uma categoria",
  "Select a category and an account.": "Selecione uma categoria e uma conta.",
  "Select a category.": "Selecione uma categoria.",
  "Select a currency": "Selecione uma moeda",
  "Select a date": "Selecione uma data",
  "Select a language": "Selecione um idioma",
  "Select a subcategory. A parent category cannot be added.": "Selecione uma subcategoria. Uma categoria pai não pode ser adicionada.",
  "Select account": "Selecione a conta",
  "Select an account.": "Selecione uma conta.",
  "Select an icon from the shared catalog": "Selecione um ícone do catálogo compartilhado",
  "Select an interface language.": "Selecione um idioma de interface.",
  "Select the interface language and analytics currency.": "Selecione o idioma da interface e a moeda analítica.",
  "Send a request": "Enviar uma solicitação",
  "Send email": "Enviar e-mail",
  "Send request": "Enviar solicitação",
  "Sending...": "Enviando...",
  "Show": "Mostrar",
  "Show password": "Mostrar senha",
  "Settings": "Configurações",
  "Sign in": "Entrar",
  "Signing in with Google...": "Fazendo login com o Google...",
  "Signing in...": "Fazendo login...",
  "Some store products are not available yet: {{products}}.": "Alguns produtos da loja ainda não estão disponíveis: {{products}}.",
  "Spending across all accounts": "Gastos em todas as contas",
  "Start date": "Data de início",
  "Step {{current}} of 2: {{screen}}": "Etapa {{current}} de 2: {{screen}}",
  "Store products are available only on iOS and Android.": "Os produtos da loja estão disponíveis apenas para iOS e Android.",
  "Store products are not available yet. Please check App Store or Google Play product setup.": "Os produtos da loja ainda não estão disponíveis. Verifique a configuração do produto na App Store ou no Google Play.",
  "Store purchases are available only on iOS and Android.": "As compras na loja estão disponíveis apenas para iOS e Android.",
  "Store purchases require iOS or Android": "As compras na loja exigem iOS ou Android",
  "Store transaction is missing orderId.": "A transação da loja não possui o orderId.",
  "Store transaction is missing originalTransactionId.": "A transação da loja não possui originalTransactionId.",
  "Store transaction is missing packageName.": "A transação da loja está faltando packageName.",
  "Store transaction is missing purchaseToken.": "A transação da loja não possui purchaseToken.",
  "Store transaction is missing signed payload.": "A transação da loja não possui carga assinada.",
  "Store transaction is missing transactionId.": "A transação da loja não possui o transactionId.",
  "Subcategories": "Subcategorias",
  "Subject": "Assunto",
  "Subscribe": "Assinar",
  "Subscription": "Assinatura",
  "Subscription management": "Gerenciamento de assinaturas",
  "Subscriptions": "Assinaturas",
  "Support": "Suporte",
  "Tap the icon to select": "Toque no ícone para selecionar",
  "Telegram username": "Nome de usuário do Telegram",
  "The account will be deleted.": "A conta será excluída.",
  "The base currency cannot be changed because budgets or transactions already exist.": "A moeda base não pode ser alterada porque já existem orçamentos ou transações.",
  "The budget category list for this month is empty.": "A lista de categorias de orçamento deste mês está vazia.",
  "The category will be removed from this month's budget.": "A categoria será retirada do orçamento deste mês.",
  "The payment is overdue. Premium access remains available through the grace-period date above.": "O pagamento está atrasado. O acesso premium permanece disponível até a data de término do período de carência indicada acima.",
  "The purchase was not confirmed by the store. Try again.": "A compra não foi confirmada pela loja. Tente novamente.",
  "The server did not respond in time. Try again.": "O servidor não respondeu a tempo. Tente novamente.",
  "The transaction will be permanently deleted.": "A transação será excluída permanentemente.",
  "The verified purchase is not active.": "A compra verificada não está ativa.",
  "This account has no password. Password setup is handled separately.": "Esta conta não possui senha. A configuração da senha é feita separadamente.",
  "This purchase has already been received. Tap Restore purchases to restore the subscription.": "Esta compra já foi recebida. Toque em Restaurar compras para restaurar a assinatura.",
  "This purchase is linked to another MoneyDrive account. Sign in to the linked account or use a different App Store Sandbox account.": "Esta compra está vinculada a outra conta MoneyDrive. Faça login na conta vinculada ou use uma conta diferente do App Store Sandbox.",
  "This purchase period has already expired.": "Este período de compra já expirou.",
  "This purchase period has expired. Select a current subscription.": "Este período de compra expirou. Selecione uma assinatura atual.",
  "This takes less than a minute.": "Isso leva menos de um minuto.",
  "To goal: {{amount}}": "Para a meta: {{amount}}",
  "To renew with LiqPay, open the web version and complete a new checkout.": "Para renovar com LiqPay, abra a versão web e conclua um novo checkout.",
  "Top categories by spending ({{currency}})": "Principais categorias por gasto ({{currency}})",
  "Total": "Total",
  "Total balance": "Saldo total",
  "Transactions": "Transações",
  "Transfer": "Transferência",
  "Type": "Tipo",
  "Type: {{type}}": "Tipo: {{type}}",
  "Unable to add the budget category (HTTP {{status}}).": "Não foi possível adicionar a categoria de orçamento (HTTP {{status}}).",
  "Unable to change password.": "Não foi possível alterar a senha.",
  "Unable to connect to the server.": "Não é possível conectar-se ao servidor.",
  "Unable to create budget (HTTP {{status}}).": "Não foi possível criar o orçamento (HTTP {{status}}).",
  "Unable to create the account.": "Não foi possível criar a conta.",
  "Unable to create the category (HTTP {{status}}).": "Não foi possível criar a categoria (HTTP {{status}}).",
  "Unable to delete the account.": "Não foi possível excluir a conta.",
  "Unable to delete the category (HTTP {{status}}).": "Não foi possível excluir a categoria (HTTP {{status}}).",
  "Unable to delete the transaction.": "Não foi possível excluir a transação.",
  "Unable to load accounts (HTTP {{status}}).": "Não foi possível carregar contas (HTTP {{status}}).",
  "Unable to load accounts.": "Não foi possível carregar contas.",
  "Unable to load budget (HTTP {{status}}).": "Não foi possível carregar o orçamento (HTTP {{status}}).",
  "Unable to load budgets (HTTP {{status}}).": "Não foi possível carregar orçamentos (HTTP {{status}}).",
  "Unable to load categories.": "Não foi possível carregar categorias.",
  "Unable to load category icons (HTTP {{status}}).": "Não foi possível carregar ícones de categoria (HTTP {{status}}).",
  "Unable to load category icons.": "Não foi possível carregar ícones de categoria.",
  "Unable to load dashboard (HTTP {{status}}).": "Não foi possível carregar o painel (HTTP {{status}}).",
  "Unable to load frequent categories.": "Não foi possível carregar categorias frequentes.",
  "Unable to load settings.": "Não foi possível carregar as configurações.",
  "Unable to load subscription products.": "Não foi possível carregar produtos de assinatura.",
  "Unable to load subscription status.": "Não foi possível carregar o status da assinatura.",
  "Unable to load transactions.": "Não foi possível carregar transações.",
  "Unable to open onboarding.": "Não foi possível abrir a configuração inicial.",
  "Unable to open the account.": "Não foi possível abrir a conta.",
  "Unable to open the category for editing.": "Não foi possível abrir a categoria para edição.",
  "Unable to open the category.": "Não foi possível abrir a categoria.",
  "Unable to open the transaction.": "Não foi possível abrir a transação.",
  "Unable to prepare the expense form.": "Não foi possível preparar o formulário de despesas.",
  "Unable to remove the budget category (HTTP {{status}}).": "Não foi possível remover a categoria de orçamento (HTTP {{status}}).",
  "Unable to resend the email.": "Não foi possível reenviar o e-mail.",
  "Unable to save the profile.": "Não foi possível salvar o perfil.",
  "Unable to save the transaction.": "Não foi possível salvar a transação.",
  "Unable to send request.": "Não foi possível enviar a solicitação.",
  "Unable to update balance.": "Não foi possível atualizar o saldo.",
  "Unable to update the account.": "Não foi possível atualizar a conta.",
  "Unable to update the budget category (HTTP {{status}}).": "Não foi possível atualizar a categoria de orçamento (HTTP {{status}}).",
  "Unable to update the category (HTTP {{status}}).": "Não foi possível atualizar a categoria (HTTP {{status}}).",
  "Uncategorized": "Sem categoria",
  "Until {{date}}": "Até {{date}}",
  "Untitled": "Sem título",
  "Unverified": "Não verificado",
  "Update": "Atualizar",
  "Verification": "Verificação",
  "Verification token": "Token de verificação",
  "Verified": "Verificado",
  "Verify email": "Verificar e-mail",
  "Verify with token": "Verificar com token",
  "Verifying email...": "Verificando e-mail...",
  "View all": "Ver tudo",
  "View budgets": "Ver orçamentos",
  "We sent a verification email to {{email}}.": "Enviamos um e-mail de verificação para {{email}}.",
  "We usually respond within one business day.": "Geralmente respondemos dentro de um dia útil.",
  "Your account and data are safe. Buy a new subscription to restore business features.": "Sua conta e dados estão seguros. Compre uma nova assinatura para restaurar recursos comerciais.",
  "Your email": "Seu e-mail",
  "Your request has been sent to our support team.": "Sua solicitação foi enviada para nossa equipe de suporte.",
  "Your session has expired. Sign in again.": "Sua sessão expirou. Faça login novamente.",
  "categories": "categorias",
  "the specified address": "o endereço especificado",
  "{{amount}} remaining": "{{amount}} restante",
  "{{percent}}% of plan": "{{percent}}% do plano",
  "‹ Back": "‹ Voltar",
  "Account \"{{name}}\" will be deleted.": "A conta \"{{name}}\" será excluída.",
  "Category \"{{name}}\" will be deleted.": "A categoria \"{{name}}\" será excluída.",
} as const;

export default ptBR;
