const pt = {
  "+{{amount}} above plan 🚀": "+{{amount}} acima do planeado 🚀",
  "30 days": "30 dias",
  "A subcategory cannot contain nested subcategories.": "Uma subcategoria não pode conter subcategorias aninhadas.",
  "Access denied.": "Acesso negado.",
  "Access until: {{date}}": "Acesso até: {{date}}",
  Account: "Conta",
  "Account settings": "Definições da conta",
  "Account unavailable.": "Conta indisponível.",
  "Account: {{name}}": "Conta: {{name}}",
  Accounts: "Contas",
  "Across all accounts": "Em todas as contas",
  Actual: "Real",
  "Actual expense": "Despesa real",
  "Actual income": "Receita real",
  Add: "Adicionar",
  "Add account": "Adicionar conta",
  "Add budget": "Adicionar orçamento",
  "Add category": "Adicionar categoria",
  "Add details": "Adicionar detalhes",
  "Add subcategory": "Adicionar subcategoria",
  "Add to budget": "Adicionar ao orçamento",
  "Add transaction": "Adicionar transação",
  "Add your first expense": "Adicione a sua primeira despesa",
  "Adding...": "A adicionar...",
  "All accounts": "Todas as contas",
  "All categories": "Todas as categorias",
  "All recorded income categories": "Todas as categorias de receitas registadas",
  "All steps completed": "Todos os passos concluídos",
  "All time": "Todo o período",
  "All types": "Todos os tipos",
  Amount: "Valor",
  "Analytics period": "Período de análise",
  "Another store purchase is already in progress.": "Já existe outra compra na loja em curso.",
  "Apple did not return an identity token.": "A Apple não devolveu um token de identidade.",
  "App Store saved {{actualProductId}} instead of {{requestedProductId}}. Check the current plan in App Store subscription settings.": "A App Store guardou {{actualProductId}} em vez de {{requestedProductId}}. Verifique o plano atual nas definições de subscrições da App Store.",
  "Auto-renew off": "Renovação automática desativada",
  "Auto-renewal is off. Premium access remains available through the date above.": "A renovação automática está desativada. O acesso Premium continuará disponível até à data indicada acima.",
  "Available plans": "Planos disponíveis",
  Back: "Voltar",
  "Back to sign in": "Voltar ao início de sessão",
  Balance: "Saldo",
  "Balance update timed out. Check that the backend API is available.": "O tempo para atualizar o saldo esgotou-se. Verifique se a API do backend está disponível.",
  "Base currency": "Moeda base",
  Budget: "Orçamento",
  "Budget category": "Categoria do orçamento",
  "Budget changes and category editing will be added after the backend API is extended.": "As alterações ao orçamento e a edição de categorias serão adicionadas após a extensão da API do backend.",
  "Budget details": "Detalhes do orçamento",
  "Budget not found.": "Orçamento não encontrado.",
  "Budget progress": "Progresso do orçamento",
  Budgets: "Orçamentos",
  C: "C",
  Cancel: "Cancelar",
  Categories: "Categorias",
  Category: "Categoria",
  "Category disabled": "Categoria desativada",
  "Category enabled": "Categoria ativada",
  "Category not found in the budget.": "Categoria não encontrada no orçamento.",
  "Category unavailable.": "Categoria indisponível.",
  'Category "{{name}}" will become a group. It can no longer be selected in new transactions and budgets. Existing records will remain unchanged.': 'A categoria "{{name}}" tornar-se-á um grupo. Deixará de poder ser selecionada em novas transações e orçamentos. Os registos existentes não serão alterados.',
  "Category will become a group": "A categoria tornar-se-á um grupo",
  "Change balance": "Alterar saldo",
  "Change password": "Alterar palavra-passe",
  "Check your email": "Verifique o seu email",
  "Checking authentication...": "A verificar a autenticação...",
  "Choose an App Store or Google Play product below.": "Escolha abaixo um produto da App Store ou do Google Play.",
  Comment: "Comentário",
  "Complete all password fields.": "Preencha todos os campos de palavra-passe.",
  "Confirm new password": "Confirmar nova palavra-passe",
  "Confirm password": "Confirmar palavra-passe",
  "Contact support": "Contactar o suporte",
  Continue: "Continuar",
  Create: "Criar",
  "Create account": "Criar conta",
  "Creating...": "A criar...",
  Currency: "Moeda",
  "Current password": "Palavra-passe atual",
  "Current plan": "Plano atual",
  Custom: "Personalizado",
  DONE: "CONCLUÍDO",
  Dashboard: "Painel",
  Date: "Data",
  "Date YYYY-MM-DD": "Data AAAA-MM-DD",
  Delete: "Eliminar",
  "Delete account?": "Eliminar a conta?",
  "Delete category": "Eliminar categoria",
  "Delete category?": "Eliminar a categoria?",
  "Delete transaction": "Eliminar transação",
  "Delete transaction?": "Eliminar a transação?",
  "Deleting...": "A eliminar...",
  Description: "Descrição",
  Disabled: "Desativado",
  Edit: "Editar",
  "Edit account": "Editar conta",
  "Edit transaction": "Editar transação",
  Editing: "Edição",
  Email: "Email",
  "Email resent. Retry in {{seconds}} seconds.": "Email reenviado. Tente novamente dentro de {{seconds}} segundos.",
  "Email sent. You can retry in about {{seconds}} seconds.": "Email enviado. Pode tentar novamente dentro de cerca de {{seconds}} segundos.",
  "Email verification": "Verificação do email",
  "Email verified. You can now sign in.": "Email verificado. Já pode iniciar sessão.",
  "Email was not sent. Try again in {{seconds}} seconds.": "O email não foi enviado. Tente novamente dentro de {{seconds}} segundos.",
  "End date": "Data de fim",
  "Enter a category name.": "Introduza um nome para a categoria.",
  "Enter a date.": "Introduza uma data.",
  "Enter a message.": "Introduza uma mensagem.",
  "Enter a new password.": "Introduza uma nova palavra-passe.",
  "Enter a subject.": "Introduza um assunto.",
  "Enter a valid amount.": "Introduza um valor válido.",
  "Enter a valid balance.": "Introduza um saldo válido.",
  "Enter a valid email address.": "Introduza um endereço de email válido.",
  "Enter a valid planned amount greater than 0.": "Introduza um valor planeado válido superior a 0.",
  "Enter an account name.": "Introduza um nome para a conta.",
  "Enter an amount greater than zero.": "Introduza um valor superior a zero.",
  "Enter your email": "Introduza o seu email",
  "Enter your email, name, and password.": "Introduza o seu email, nome e palavra-passe.",
  "Enter your email.": "Introduza o seu email.",
  "Enter your name": "Introduza o seu nome",
  Expense: "Despesa",
  "Expense categories": "Categorias de despesas",
  "Expense categories are not available yet.": "As categorias de despesas ainda não estão disponíveis.",
  "Expense not submitted: complete the required fields.": "A despesa não foi guardada: preencha os campos obrigatórios.",
  Expenses: "Despesas",
  "Expenses and income": "Despesas e receitas",
  "Expenses this period": "Despesas deste período",
  "Fill password": "Introduzir palavra-passe",
  "Forgot password?": "Esqueceu-se da palavra-passe?",
  Free: "Gratuito",
  "From {{date}}": "Desde {{date}}",
  "Go to sign in": "Ir para o início de sessão",
  "Goal reached! 🎉": "Objetivo alcançado! 🎉",
  "Google Sign-In is not configured for this build.": "O início de sessão com o Google não está configurado para esta compilação.",
  "Google did not return an ID token.": "O Google não devolveu um token de ID.",
  Group: "Grupo",
  Hide: "Ocultar",
  "Hide form": "Ocultar formulário",
  "Hide password": "Ocultar palavra-passe",
  Home: "Início",
  "I have a token": "Tenho um token",
  Icon: "Ícone",
  "If the account exists, an email has been sent.": "Se a conta existir, foi enviado um email.",
  "If the account exists, an email has been sent. Retry in {{seconds}} seconds.": "Se a conta existir, foi enviado um email. Tente novamente dentro de {{seconds}} segundos.",
  "If the email contains a production link, paste the token manually for local testing.": "Se o email contiver uma ligação de produção, cole manualmente o token para testes locais.",
  Income: "Receita",
  "Income categories": "Categorias de receitas",
  "Income categories are not available yet.": "As categorias de receitas ainda não estão disponíveis.",
  "Income this period": "Receitas deste período",
  "Initial setup": "Configuração inicial",
  "Interface language": "Idioma da interface",
  "Invalid accounts response format.": "Formato de resposta das contas inválido.",
  "Invalid budget response format.": "Formato de resposta do orçamento inválido.",
  "Keep an eye on all of your balances.": "Acompanhe todos os seus saldos.",
  "Language and base currency": "Idioma e moeda base",
  "LiqPay subscription can be cancelled only in the web version of the app.": "A subscrição LiqPay só pode ser cancelada na versão web da aplicação.",
  "Loading accounts...": "A carregar contas...",
  "Loading budget...": "A carregar orçamento...",
  "Loading budgets...": "A carregar orçamentos...",
  "Loading categories...": "A carregar categorias...",
  "Loading dashboard...": "A carregar painel...",
  "Loading icons...": "A carregar ícones...",
  "Loading onboarding...": "A carregar configuração inicial...",
  "Loading settings...": "A carregar definições...",
  "Loading store products...": "A carregar produtos da loja...",
  "Loading subscription status...": "A carregar estado da subscrição...",
  "Loading...": "A carregar...",
  "Log in": "Iniciar sessão",
  "Login with Google": "Iniciar sessão com o Google",
  Logout: "Terminar sessão",
  "Manage on web": "Gerir na web",
  "Manage premium access": "Gerir acesso Premium",
  "Manage subscription": "Gerir subscrição",
  "Maximum category depth is 2 levels": "A profundidade máxima das categorias é de 2 níveis",
  "Maximum category depth is 2 levels.": "A profundidade máxima das categorias é de 2 níveis.",
  Message: "Mensagem",
  "Missing Android subscription offer token for selected product.": "Falta o token da oferta de subscrição Android para o produto selecionado.",
  "Missing account ID.": "Falta o ID da conta.",
  "Missing budgetId.": "Falta budgetId.",
  "Missing reset token.": "Falta o token de reposição.",
  "MoneyDrive.me": "MoneyDrive.me",
  Month: "Mês",
  More: "Mais",
  "More service sections": "Mais secções do serviço",
  "Most frequent": "Mais frequentes",
  Name: "Nome",
  "New account": "Nova conta",
  "New balance": "Novo saldo",
  "New category": "Nova categoria",
  "New email awaiting verification: {{email}}": "Novo email a aguardar verificação: {{email}}",
  "New password": "Nova palavra-passe",
  "New planned amount": "Novo valor planeado",
  "No App Store Sandbox account is connected on this device. Add a sandbox tester in Settings > App Store > Sandbox Account.": "Não existe uma conta App Store Sandbox ligada a este dispositivo. Adicione um utilizador de teste em Definições > App Store > Conta Sandbox.",
  "No account": "Sem conta",
  "No account data.": "Não existem dados da conta.",
  "No accounts.": "Não existem contas.",
  "No active purchases found.": "Não foram encontradas compras ativas.",
  "No active store source": "Sem origem de loja ativa",
  "No budget has been created for the selected month.": "Não foi criado nenhum orçamento para o mês selecionado.",
  "No budgets for the selected period.": "Não existem orçamentos para o período selecionado.",
  "No budgets found yet.": "Ainda não foram encontrados orçamentos.",
  "No categories available to add.": "Não existem categorias disponíveis para adicionar.",
  "No categories found for the selected type.": "Não foram encontradas categorias para o tipo selecionado.",
  "No categories found.": "Não foram encontradas categorias.",
  "No categories.": "Não existem categorias.",
  "No data for the selected period.": "Não existem dados para o período selecionado.",
  "No data.": "Não existem dados.",
  "No external management action is available.": "Não existe nenhuma ação de gestão externa disponível.",
  "No period selected": "Nenhum período selecionado",
  "No transaction data.": "Não existem dados de transações.",
  "No transactions yet.": "Ainda não existem transações.",
  "Not enough data to add the category.": "Não existem dados suficientes para adicionar a categoria.",
  "Not set": "Não definido",
  Note: "Nota",
  Open: "Abrir",
  "Open App Store account settings and choose Subscriptions.": "Abra as definições da conta da App Store e selecione Subscrições.",
  "Open the subscription provider account settings to manage this plan.": "Abra as definições da conta do fornecedor da subscrição para gerir este plano.",
  "Overspent by {{amount}}": "Excesso de despesa de {{amount}}",
  "Parent: {{name}}": "Principal: {{name}}",
  Password: "Palavra-passe",
  "Password changed.": "Palavra-passe alterada.",
  "Password recovery": "Recuperação da palavra-passe",
  "Password updated. You can now sign in.": "Palavra-passe atualizada. Já pode iniciar sessão.",
  "Passwords do not match.": "As palavras-passe não coincidem.",
  "Paste the verification token.": "Cole o token de verificação.",
  "Period: {{period}}": "Período: {{period}}",
  "Plan ({{currency}})": "Plano ({{currency}})",
  "Plan / actual / remaining by category": "Planeado / real / restante por categoria",
  "Plan {{plan}} · Actual {{actual}}": "Planeado {{plan}} · Real {{actual}}",
  "Plans and billing": "Planos e faturação",
  "Planned amount ({{currency}})": "Valor planeado ({{currency}})",
  "Planned expense": "Despesa planeada",
  "Planned income": "Receita planeada",
  "Popular categories": "Categorias populares",
  Premium: "Premium",
  "Premium is active.": "O Premium está ativo.",
  "Premium is active. The plan change will take effect on the next App Store renewal.": "O Premium está ativo. A alteração do plano terá efeito na próxima renovação da App Store.",
  "Processing...": "A processar...",
  "Product temporarily unavailable.": "Produto temporariamente indisponível.",
  "Product: {{product}}": "Produto: {{product}}",
  "Products for {{platform}}": "Produtos para {{platform}}",
  Profile: "Perfil",
  "Profile and security": "Perfil e segurança",
  "Profile saved.": "Perfil guardado.",
  "Profile, language, and security": "Perfil, idioma e segurança",
  "Purchase not confirmed. Try again.": "Compra não confirmada. Tente novamente.",
  "Recent transactions": "Transações recentes",
  Registration: "Registo",
  Remaining: "Restante",
  "Renewal canceled": "Renovação cancelada",
  "Request failed (HTTP {{status}}).": "O pedido falhou (HTTP {{status}}).",
  "Resend email": "Reenviar email",
  "Restore purchases": "Restaurar compras",
  "Restored purchases: {{count}}.": "Compras restauradas: {{count}}.",
  "Restoring...": "A restaurar...",
  Retry: "Tentar novamente",
  "Root level": "Nível raiz",
  "Runtime category tree": "Árvore atual de categorias",
  Save: "Guardar",
  "Save and continue": "Guardar e continuar",
  "Save balance": "Guardar saldo",
  "Save password": "Guardar palavra-passe",
  "Saving...": "A guardar...",
  "Segments show amounts by category.": "Os segmentos mostram os valores por categoria.",
  Select: "Selecionar",
  "Select a base currency.": "Selecione uma moeda base.",
  "Select a category": "Selecione uma categoria",
  "Select a category and an account.": "Selecione uma categoria e uma conta.",
  "Select a category.": "Selecione uma categoria.",
  "Select a currency": "Selecione uma moeda",
  "Select a date": "Selecione uma data",
  "Select a language": "Selecione um idioma",
  "Select a subcategory. A parent category cannot be added.": "Selecione uma subcategoria. Não é possível adicionar uma categoria principal.",
  "Select account": "Selecione uma conta",
  "Select an account.": "Selecione uma conta.",
  "Select an icon from the shared catalog": "Selecione um ícone do catálogo partilhado",
  "Select an interface language.": "Selecione um idioma para a interface.",
  "Select the interface language and analytics currency.": "Selecione o idioma da interface e a moeda de análise.",
  "Send a request": "Enviar um pedido",
  "Send email": "Enviar email",
  "Send request": "Enviar pedido",
  "Sending...": "A enviar...",
  Show: "Mostrar",
  "Show password": "Mostrar palavra-passe",
  Settings: "Definições",
  "Sign in": "Iniciar sessão",
  "Signing in with Google...": "A iniciar sessão com o Google...",
  "Signing in...": "A iniciar sessão...",
  "Some store products are not available yet: {{products}}.": "Alguns produtos da loja ainda não estão disponíveis: {{products}}.",
  "Spending across all accounts": "Despesas em todas as contas",
  "Start date": "Data de início",
  "Step {{current}} of 2: {{screen}}": "Passo {{current}} de 2: {{screen}}",
  "Store products are available only on iOS and Android.": "Os produtos da loja só estão disponíveis em iOS e Android.",
  "Store products are not available yet. Please check App Store or Google Play product setup.": "Os produtos da loja ainda não estão disponíveis. Verifique a configuração dos produtos da App Store ou do Google Play.",
  "Store purchases are available only on iOS and Android.": "As compras na loja só estão disponíveis em iOS e Android.",
  "Store purchases require iOS or Android": "As compras na loja requerem iOS ou Android",
  "Store transaction is missing orderId.": "Falta orderId na transação da loja.",
  "Store transaction is missing originalTransactionId.": "Falta originalTransactionId na transação da loja.",
  "Store transaction is missing packageName.": "Falta packageName na transação da loja.",
  "Store transaction is missing purchaseToken.": "Falta purchaseToken na transação da loja.",
  "Store transaction is missing signed payload.": "Faltam os dados assinados na transação da loja.",
  "Store transaction is missing transactionId.": "Falta transactionId na transação da loja.",
  Subcategories: "Subcategorias",
  Subject: "Assunto",
  Subscribe: "Subscrever",
  Subscription: "Subscrição",
  "Subscription management": "Gestão da subscrição",
  Subscriptions: "Subscrições",
  Support: "Suporte",
  "Tap the icon to select": "Toque no ícone para selecionar",
  "Telegram username": "Nome de utilizador do Telegram",
  "The account will be deleted.": "A conta será eliminada.",
  "The base currency cannot be changed because budgets or transactions already exist.": "A moeda base não pode ser alterada porque já existem orçamentos ou transações.",
  "The budget category list for this month is empty.": "A lista de categorias do orçamento deste mês está vazia.",
  "The category will be removed from this month's budget.": "A categoria será removida do orçamento deste mês.",
  "The payment is overdue. Premium access remains available through the grace-period date above.": "O pagamento está em atraso. O acesso Premium continuará disponível até à data do período de tolerância indicada acima.",
  "The purchase was not confirmed by the store. Try again.": "A compra não foi confirmada pela loja. Tente novamente.",
  "The server did not respond in time. Try again.": "O servidor não respondeu a tempo. Tente novamente.",
  "The transaction will be permanently deleted.": "A transação será eliminada permanentemente.",
  "The verified purchase is not active.": "A compra verificada não está ativa.",
  "This account has no password. Password setup is handled separately.": "Esta conta não tem palavra-passe. A configuração da palavra-passe é efetuada separadamente.",
  "This purchase has already been received. Tap Restore purchases to restore the subscription.": "Esta compra já foi recebida. Toque em Restaurar compras para recuperar a subscrição.",
  "This purchase is linked to another MoneyDrive account. Sign in to the linked account or use a different App Store Sandbox account.": "Esta compra está associada a outra conta MoneyDrive. Inicie sessão na conta associada ou utilize outra conta App Store Sandbox.",
  "This purchase period has already expired.": "O período desta compra já expirou.",
  "This purchase period has expired. Select a current subscription.": "O período desta compra expirou. Selecione uma subscrição atual.",
  "This takes less than a minute.": "Demora menos de um minuto.",
  "To goal: {{amount}}": "Para o objetivo: {{amount}}",
  "To renew with LiqPay, open the web version and complete a new checkout.": "Para renovar com o LiqPay, abra a versão web e conclua uma nova compra.",
  "Top categories by spending ({{currency}})": "Principais categorias por despesa ({{currency}})",
  Total: "Total",
  "Total balance": "Saldo total",
  Transactions: "Transações",
  Transfer: "Transferência",
  Type: "Tipo",
  "Type: {{type}}": "Tipo: {{type}}",
  "Unable to add the budget category (HTTP {{status}}).": "Não foi possível adicionar a categoria ao orçamento (HTTP {{status}}).",
  "Unable to change password.": "Não foi possível alterar a palavra-passe.",
  "Unable to connect to the server.": "Não foi possível estabelecer ligação ao servidor.",
  "Unable to create budget (HTTP {{status}}).": "Não foi possível criar o orçamento (HTTP {{status}}).",
  "Unable to create the account.": "Não foi possível criar a conta.",
  "Unable to create the category (HTTP {{status}}).": "Não foi possível criar a categoria (HTTP {{status}}).",
  "Unable to delete the category (HTTP {{status}}).": "Não foi possível eliminar a categoria (HTTP {{status}}).",
  "Unable to delete the transaction.": "Não foi possível eliminar a transação.",
  "Unable to load accounts (HTTP {{status}}).": "Não foi possível carregar as contas (HTTP {{status}}).",
  "Unable to load accounts.": "Não foi possível carregar as contas.",
  "Unable to load budget (HTTP {{status}}).": "Não foi possível carregar o orçamento (HTTP {{status}}).",
  "Unable to load budgets (HTTP {{status}}).": "Não foi possível carregar os orçamentos (HTTP {{status}}).",
  "Unable to load categories.": "Não foi possível carregar as categorias.",
  "Unable to load category icons (HTTP {{status}}).": "Não foi possível carregar os ícones das categorias (HTTP {{status}}).",
  "Unable to load category icons.": "Não foi possível carregar os ícones das categorias.",
  "Unable to load dashboard (HTTP {{status}}).": "Não foi possível carregar o painel (HTTP {{status}}).",
  "Unable to load frequent categories.": "Não foi possível carregar as categorias frequentes.",
  "Unable to load settings.": "Não foi possível carregar as definições.",
  "Unable to load subscription products.": "Não foi possível carregar os produtos de subscrição.",
  "Unable to load subscription status.": "Não foi possível carregar o estado da subscrição.",
  "Unable to load transactions.": "Não foi possível carregar as transações.",
  "Unable to open onboarding.": "Não foi possível abrir a configuração inicial.",
  "Unable to open the account.": "Não foi possível abrir a conta.",
  "Unable to open the category for editing.": "Não foi possível abrir a categoria para edição.",
  "Unable to open the category.": "Não foi possível abrir a categoria.",
  "Unable to open the transaction.": "Não foi possível abrir a transação.",
  "Unable to prepare the expense form.": "Não foi possível preparar o formulário de despesas.",
  "Unable to remove the budget category (HTTP {{status}}).": "Não foi possível remover a categoria do orçamento (HTTP {{status}}).",
  "Unable to resend the email.": "Não foi possível reenviar o email.",
  "Unable to save the profile.": "Não foi possível guardar o perfil.",
  "Unable to save the transaction.": "Não foi possível guardar a transação.",
  "Unable to send request.": "Não foi possível enviar o pedido.",
  "Unable to update balance.": "Não foi possível atualizar o saldo.",
  "Unable to update the account.": "Não foi possível atualizar a conta.",
  "Unable to update the budget category (HTTP {{status}}).": "Não foi possível atualizar a categoria do orçamento (HTTP {{status}}).",
  "Unable to update the category (HTTP {{status}}).": "Não foi possível atualizar a categoria (HTTP {{status}}).",
  Uncategorized: "Sem categoria",
  "Until {{date}}": "Até {{date}}",
  Untitled: "Sem título",
  Unverified: "Não verificado",
  Update: "Atualizar",
  Verification: "Verificação",
  "Verification token": "Token de verificação",
  Verified: "Verificado",
  "Verify email": "Verificar email",
  "Verify with token": "Verificar com token",
  "Verifying email...": "A verificar o email...",
  "View all": "Ver tudo",
  "View budgets": "Ver orçamentos",
  "We sent a verification email to {{email}}.": "Enviámos um email de verificação para {{email}}.",
  "We usually respond within one business day.": "Normalmente respondemos no prazo de um dia útil.",
  "Your account and data are safe. Buy a new subscription to restore business features.": "A sua conta e os seus dados estão seguros. Compre uma nova subscrição para restaurar as funcionalidades empresariais.",
  "Your email": "O seu email",
  "Your request has been sent to our support team.": "O seu pedido foi enviado para a nossa equipa de suporte.",
  "Your session has expired. Sign in again.": "A sua sessão expirou. Inicie sessão novamente.",
  categories: "categorias",
  "the specified address": "o endereço indicado",
  "{{amount}} remaining": "Restam {{amount}}",
  "{{percent}}% of plan": "{{percent}}% do planeado",
  "‹ Back": "‹ Voltar",
  'Account "{{name}}" will be deleted.': 'A conta "{{name}}" será eliminada.',
  'Category "{{name}}" will be deleted.': 'A categoria "{{name}}" será eliminada.',
  "Account deleted": "Conta eliminada",
  "Accounts, categories, budgets, transactions, transfers, settings, and access tokens will be deleted.": "Contas, categorias, orçamentos, transações, transferências, definições e tokens de acesso serão eliminados.",
  "Apple did not return credentials required for account deletion.": "A Apple não devolveu as credenciais necessárias para eliminar a conta.",
  "Apple Sign-In is not available on this device.": "O início de sessão com a Apple não está disponível neste dispositivo.",
  "Apple Sign-In was cancelled.": "O início de sessão com a Apple foi cancelado.",
  "Choose a verification method. Sign-in will open after you press the final delete button.": "Escolha um método de verificação. O início de sessão será aberto depois de premir o botão final de eliminação.",
  "Confirm your identity": "Confirme a sua identidade",
  "Continue with Apple and delete account": "Continuar com Apple e eliminar a conta",
  "Continue with Google and delete account": "Continuar com Google e eliminar a conta",
  "Danger zone": "Zona de perigo",
  "Delete MoneyDrive account": "Eliminar conta MoneyDrive",
  "Delete MoneyDrive account permanently": "Eliminar permanentemente a conta MoneyDrive",
  "Deleting account...": "A eliminar conta...",
  "Deleting your account permanently removes your profile and financial data. This action cannot be undone.": "Eliminar permanentemente a conta remove o perfil e os dados financeiros. Esta ação não pode ser anulada.",
  "Deleting MoneyDrive does not cancel App Store billing. Cancel the subscription in Apple settings if you no longer want it.": "Eliminar o MoneyDrive não cancela a cobrança da App Store. Cancele a assinatura nas definições da Apple se já não a quiser.",
  "Google Sign-In": "Iniciar sessão com Google",
  "Manage Apple subscription": "Gerir assinatura Apple",
  "Sign in with Apple": "Iniciar sessão com Apple",
  "Type DELETE to confirm": "Escreva DELETE para confirmar",
  "Unable to delete the account.": "Não foi possível eliminar a conta.",
  "Unable to open subscription management.": "Não foi possível abrir a gestão de assinaturas.",
} as const;

export default pt;
