const trTR = {
  "+{{amount}} above plan 🚀": "+{{amount}} planın üstünde 🚀",
  "30 days": "30 gün",
  "A subcategory cannot contain nested subcategories.": "Bir alt kategori iç içe geçmiş alt kategoriler içeremez.",
  "Access denied.": "Erişim engellendi.",
  "Access until: {{date}}": "Erişim tarihi: {{date}}",
  "Account": "Hesap",
  "Account settings": "Hesap ayarları",
  "Account unavailable.": "Hesap kullanılamıyor.",
  "Account: {{name}}": "Hesap: {{name}}",
  "Accounts": "Hesaplar",
  "Across all accounts": "Tüm hesaplarda",
  "Actual": "Gerçek",
  "Actual expense": "Fiili gider",
  "Actual income": "Gerçek gelir",
  "Add": "Ekle",
  "Add account": "Hesap ekle",
  "Add budget": "Bütçe ekle",
  "Add category": "Kategori ekle",
  "Add details": "Ayrıntıları ekle",
  "Add subcategory": "Alt kategori ekle",
  "Add to budget": "Bütçeye ekle",
  "Add transaction": "İşlem ekle",
  "Add your first expense": "İlk masrafınızı ekleyin",
  "Adding...": "Ekleniyor...",
  "All accounts": "Tüm hesaplar",
  "All categories": "Tüm kategoriler",
  "All recorded income categories": "Kaydedilen tüm gelir kategorileri",
  "All steps completed": "Tüm adımlar tamamlandı",
  "All time": "Tüm zamanlar",
  "All types": "Tüm türler",
  "Amount": "Miktar",
  "Analytics period": "Analitik dönemi",
  "Another store purchase is already in progress.": "Başka bir mağaza satın alma işlemi halihazırda devam ediyor.",
  "Apple did not return an identity token.": "Apple bir kimlik belirteci iade etmedi.",
  "App Store saved {{actualProductId}} instead of {{requestedProductId}}. Check the current plan in App Store subscription settings.": "App Store, {{requestedProductId}} yerine {{actualProductId}}'yi kaydetti. App Store abonelik ayarlarında mevcut planı kontrol edin.",
  "Auto-renew off": "Otomatik yenileme kapalı",
  "Auto-renewal is off. Premium access remains available through the date above.": "Otomatik yenileme kapalı. Premium erişim yukarıdaki tarihe kadar mevcut olmaya devam edecektir.",
  "Available plans": "Mevcut planlar",
  "Back": "Geri",
  "Back to sign in": "Oturum açmak için geri dön",
  "Balance": "Bakiye",
  "Balance update timed out. Check that the backend API is available.": "Bakiye güncellemesi zaman aşımına uğradı. Arka uç API'sinin mevcut olup olmadığını kontrol edin.",
  "Base currency": "Temel para birimi",
  "Budget": "Bütçe",
  "Budget category": "Bütçe kategorisi",
  "Budget changes and category editing will be added after the backend API is extended.": "Arka uç API'si genişletildikten sonra bütçe değişiklikleri ve kategori düzenleme eklenecektir.",
  "Budget details": "Bütçe ayrıntıları",
  "Budget not found.": "Bütçe bulunamadı.",
  "Budget progress": "Bütçe ilerlemesi",
  "Budgets": "Bütçeler",
  "C": "C",
  "Cancel": "İptal",
  "Categories": "Kategoriler",
  "Category": "Kategori",
  "Category disabled": "Kategori devre dışı",
  "Category enabled": "Kategori etkin",
  "Category not found in the budget.": "Kategori bütçede bulunamadı.",
  "Category unavailable.": "Kategori kullanılamıyor.",
  "Category \"{{name}}\" will become a group. It can no longer be selected in new transactions and budgets. Existing records will remain unchanged.": "\"{{name}}\" kategorisi bir grup haline gelecektir. Artık yeni işlemlerde ve bütçelerde seçilemez. Mevcut kayıtlar değişmeden kalacaktır.",
  "Category will become a group": "Kategori bir grup haline gelecektir",
  "Change balance": "Bakiyeyi değiştir",
  "Change password": "Şifre değiştir",
  "Check your email": "E-postanızı kontrol edin",
  "Checking authentication...": "Kimlik doğrulaması kontrol ediliyor...",
  "Choose an App Store or Google Play product below.": "Aşağıdan bir App Store veya Google Play ürünü seçin.",
  "Comment": "Yorum",
  "Complete all password fields.": "Tüm şifre alanlarını doldurun.",
  "Confirm new password": "Yeni şifreyi onayla",
  "Confirm password": "Şifreyi doğrula",
  "Contact support": "Destek ile iletişime geç",
  "Continue": "Devam et",
  "Create": "Oluştur",
  "Create account": "Hesap oluştur",
  "Creating...": "Oluşturuluyor...",
  "Currency": "Para birimi",
  "Current password": "Mevcut Şifre",
  "Current plan": "Mevcut plan",
  "Custom": "Özel",
  "DONE": "TAMAM",
  "Dashboard": "Kontrol Paneli",
  "Date": "Tarih",
  "Date YYYY-MM-DD": "Tarih YYYY-AA-GG",
  "Delete": "Sil",
  "Delete account?": "Hesap silinsin mi?",
  "Delete category": "Kategoriyi sil",
  "Delete category?": "Kategori silinsin mi?",
  "Delete transaction": "İşlemi sil",
  "Delete transaction?": "İşlem silinsin mi?",
  "Deleting...": "Siliniyor...",
  "Description": "Tanım",
  "Disabled": "Devre dışı",
  "Edit": "Düzenle",
  "Edit account": "Hesabı düzenle",
  "Edit transaction": "İşlemi düzenle",
  "Editing": "Düzenleme",
  "Email": "E-posta",
  "Email resent. Retry in {{seconds}} seconds.": "E-posta yeniden gönderildi. {{seconds}} saniye içinde yeniden deneyin.",
  "Email sent. You can retry in about {{seconds}} seconds.": "E-posta gönderildi. Yaklaşık {{seconds}} saniye içinde yeniden deneyebilirsiniz.",
  "Email verification": "E-posta doğrulaması",
  "Email verified. You can now sign in.": "E-posta doğrulandı. Artık oturum açabilirsiniz.",
  "Email was not sent. Try again in {{seconds}} seconds.": "E-posta gönderilmedi. {{seconds}} saniye içinde tekrar deneyin.",
  "End date": "Bitiş tarihi",
  "Enter a category name.": "Bir kategori adı girin.",
  "Enter a date.": "Bir tarih girin.",
  "Enter a message.": "Bir mesaj girin.",
  "Enter a new password.": "Yeni bir şifre girin.",
  "Enter a subject.": "Bir konu girin.",
  "Enter a valid amount.": "Geçerli bir tutar girin.",
  "Enter a valid balance.": "Geçerli bir bakiye girin.",
  "Enter a valid email address.": "Geçerli bir e-posta adresi girin.",
  "Enter a valid planned amount greater than 0.": "0'dan büyük, geçerli bir planlanan tutar girin.",
  "Enter an account name.": "Bir hesap adı girin.",
  "Enter an amount greater than zero.": "Sıfırdan büyük bir miktar girin.",
  "Enter your email": "E-postanızı girin",
  "Enter your email, name, and password.": "E-postanızı, adınızı ve şifrenizi girin.",
  "Enter your email.": "E-postanızı girin.",
  "Enter your name": "Adınızı girin",
  "Expense": "Gider",
  "Expense categories": "Gider kategorileri",
  "Expense categories are not available yet.": "Gider kategorileri henüz mevcut değil.",
  "Expense not submitted: complete the required fields.": "Gider gönderilmedi: gerekli alanları doldurun.",
  "Expenses": "Giderler",
  "Expenses and income": "Giderler ve gelir",
  "Expenses this period": "Bu dönemdeki giderler",
  "Fill password": "Şifreyi doldur",
  "Forgot password?": "Şifrenizi mi unuttunuz?",
  "Free": "Ücretsiz",
  "From {{date}}": "{{date}}'den",
  "Go to sign in": "Oturum açmaya git",
  "Goal reached! 🎉": "Hedefe ulaşıldı! 🎉",
  "Google Sign-In is not configured for this build.": "Google ile Oturum Açma bu yapı için yapılandırılmadı.",
  "Google did not return an ID token.": "Google bir kimlik belirteci döndürmedi.",
  "Group": "Grup",
  "Hide": "Gizle",
  "Hide form": "Formu gizle",
  "Hide password": "Şifreyi gizle",
  "Home": "Ana Sayfa",
  "I have a token": "bir jetonum var",
  "Icon": "Simge",
  "If the account exists, an email has been sent.": "Hesap mevcutsa bir e-posta gönderildi.",
  "If the account exists, an email has been sent. Retry in {{seconds}} seconds.": "Hesap mevcutsa bir e-posta gönderildi. {{seconds}} saniye içinde yeniden deneyin.",
  "If the email contains a production link, paste the token manually for local testing.": "E-posta bir üretim bağlantısı içeriyorsa yerel test için belirteci manuel olarak yapıştırın.",
  "Income": "Gelir",
  "Income categories": "Gelir kategorileri",
  "Income categories are not available yet.": "Gelir kategorileri henüz mevcut değil.",
  "Income this period": "Bu dönemdeki gelir",
  "Initial setup": "İlk kurulum",
  "Interface language": "Arayüz dili",
  "Invalid accounts response format.": "Geçersiz hesap yanıt biçimi.",
  "Invalid budget response format.": "Geçersiz bütçe yanıt biçimi.",
  "Keep an eye on all of your balances.": "Tüm bakiyelerinize dikkat edin.",
  "Language and base currency": "Dil ve temel para birimi",
  "LiqPay subscription can be cancelled only in the web version of the app.": "LiqPay aboneliği yalnızca uygulamanın web sürümünde iptal edilebilir.",
  "Loading accounts...": "Hesaplar yükleniyor...",
  "Loading budget...": "Bütçe yükleniyor...",
  "Loading budgets...": "Bütçeler yükleniyor...",
  "Loading categories...": "Kategoriler yükleniyor...",
  "Loading dashboard...": "Kontrol paneli yükleniyor...",
  "Loading icons...": "Simgeler yükleniyor...",
  "Loading onboarding...": "İlk katılım yükleniyor...",
  "Loading settings...": "Ayarlar yükleniyor...",
  "Loading store products...": "Mağaza ürünleri yükleniyor...",
  "Loading subscription status...": "Abonelik durumu yükleniyor...",
  "Loading...": "Yükleniyor...",
  "Log in": "Giriş yap",
  "Login with Google": "Google ile giriş yap",
  "Logout": "Oturumu kapat",
  "Manage on web": "Web'de yönet",
  "Manage premium access": "Premium erişimi yönetin",
  "Manage subscription": "Aboneliği yönet",
  "Maximum category depth is 2 levels": "Maksimum kategori derinliği 2 seviyedir",
  "Maximum category depth is 2 levels.": "Maksimum kategori derinliği 2 seviyedir.",
  "Message": "Mesaj",
  "Missing Android subscription offer token for selected product.": "Seçilen ürün için Android abonelik teklifi jetonu eksik.",
  "Missing account ID.": "Hesap kimliği eksik.",
  "Missing budgetId.": "Eksik bütçe kimliği.",
  "Missing reset token.": "Sıfırlama jetonu eksik.",
  "MoneyDrive.me": "MoneyDrive.me",
  "Month": "Ay",
  "More": "Daha",
  "More service sections": "Daha fazla hizmet bölümü",
  "Most frequent": "En sık",
  "Name": "İsim",
  "New account": "Yeni hesap",
  "New balance": "Yeni bakiye",
  "New category": "Yeni kategori",
  "New email awaiting verification: {{email}}": "Doğrulanmayı bekleyen yeni e-posta: {{email}}",
  "New password": "Yeni Şifre",
  "New planned amount": "Yeni planlanan miktar",
  "No App Store Sandbox account is connected on this device. Add a sandbox tester in Settings > App Store > Sandbox Account.": "Bu cihaza hiçbir App Store Sandbox hesabı bağlı değil. Ayarlar > App Store > Sandbox Hesabı'na bir sandbox test cihazı ekleyin.",
  "No account": "Hesap yok",
  "No account data.": "Hesap verisi yok.",
  "No accounts.": "Hesap yok.",
  "No active purchases found.": "Aktif satın alma bulunamadı.",
  "No active store source": "Etkin mağaza kaynağı yok",
  "No budget has been created for the selected month.": "Seçilen ay için bütçe oluşturulmadı.",
  "No budgets for the selected period.": "Seçilen dönem için bütçe yok.",
  "No budgets found yet.": "Henüz bütçe bulunamadı.",
  "No categories available to add.": "Eklenebilecek kategori yok.",
  "No categories found for the selected type.": "Seçilen tür için kategori bulunamadı.",
  "No categories found.": "Hiçbir kategori bulunamadı.",
  "No categories.": "Kategori yok.",
  "No data for the selected period.": "Seçilen döneme ait veri yok.",
  "No data.": "Veri yok.",
  "No external management action is available.": "Hiçbir harici yönetim eylemi mevcut değildir.",
  "No period selected": "Dönem seçilmedi",
  "No transaction data.": "İşlem verisi yok.",
  "No transactions yet.": "Henüz işlem yok.",
  "Not enough data to add the category.": "Kategoriyi eklemek için yeterli veri yok.",
  "Not set": "Ayarlanmadı",
  "Note": "Not",
  "Open": "Aç",
  "Open App Store account settings and choose Subscriptions.": "App Store hesap ayarlarını açın ve Abonelikler'i seçin.",
  "Open the subscription provider account settings to manage this plan.": "Bu planı yönetmek için abonelik sağlayıcı hesap ayarlarını açın.",
  "Overspent by {{amount}}": "Bütçe {{amount}} aşıldı",
  "Parent: {{name}}": "Ebeveyn: {{name}}",
  "Password": "Şifre",
  "Password changed.": "Şifre değiştirildi.",
  "Password recovery": "Şifre kurtarma",
  "Password updated. You can now sign in.": "Şifre güncellendi. Artık oturum açabilirsiniz.",
  "Passwords do not match.": "Şifreler eşleşmiyor.",
  "Paste the verification token.": "Doğrulama jetonunu yapıştırın.",
  "Period: {{period}}": "Dönem: {{period}}",
  "Plan ({{currency}})": "Planı ({{currency}})",
  "Plan / actual / remaining by category": "Kategoriye göre plan / fiili / kalan",
  "Plan {{plan}} · Actual {{actual}}": "Plan {{plan}} · Gerçekleşen {{actual}}",
  "Plans and billing": "Planlar ve faturalandırma",
  "Planned amount ({{currency}})": "Planlanan tutar ({{currency}})",
  "Planned expense": "Planlanan gider",
  "Planned income": "Planlanan gelir",
  "Popular categories": "Popüler kategoriler",
  "Premium": "Premium",
  "Premium is active.": "Premium aktif.",
  "Premium is active. The plan change will take effect on the next App Store renewal.": "Premium aktif. Plan değişikliği bir sonraki App Store yenilemesinde geçerli olacaktır.",
  "Processing...": "İşleme...",
  "Product temporarily unavailable.": "Ürün geçici olarak kullanılamıyor.",
  "Product: {{product}}": "Ürün: {{product}}",
  "Products for {{platform}}": "{{platform}} için ürünler",
  "Profile": "Profil",
  "Profile and security": "Profil ve güvenlik",
  "Profile saved.": "Profil kaydedildi.",
  "Profile, language, and security": "Profil, dil ve güvenlik",
  "Purchase not confirmed. Try again.": "Satın alma onaylanmadı. Tekrar deneyin.",
  "Recent transactions": "Son işlemler",
  "Registration": "Kayıt",
  "Remaining": "Kalan",
  "Renewal canceled": "Yenileme iptal edildi",
  "Request failed (HTTP {{status}}).": "İstek başarısız oldu (HTTP {{status}}).",
  "Resend email": "E-postayı yeniden gönder",
  "Restore purchases": "Satın alınanları geri yükle",
  "Restored purchases: {{count}}.": "Geri yüklenen satın almalar: {{count}}.",
  "Restoring...": "Geri yükleniyor...",
  "Retry": "Yeniden dene",
  "Root level": "Ana seviye",
  "Runtime category tree": "Çalışma zamanı kategori yapısı",
  "Save": "Kaydet",
  "Save and continue": "Kaydet ve devam et",
  "Save balance": "Bakiyeyi kaydet",
  "Save password": "Şifreyi kaydet",
  "Saving...": "Kaydediliyor...",
  "Segments show amounts by category.": "Segmentler kategoriye göre tutarları gösterir.",
  "Select": "Seç",
  "Select a base currency.": "Bir temel para birimi seçin.",
  "Select a category": "Bir kategori seçin",
  "Select a category and an account.": "Bir kategori ve hesap seçin.",
  "Select a category.": "Bir kategori seçin.",
  "Select a currency": "Bir para birimi seçin",
  "Select a date": "Bir tarih seçin",
  "Select a language": "Bir dil seçin",
  "Select a subcategory. A parent category cannot be added.": "Bir alt kategori seçin. Üst kategori eklenemez.",
  "Select account": "Hesap seçin",
  "Select an account.": "Bir hesap seçin.",
  "Select an icon from the shared catalog": "Paylaşılan katalogdan bir simge seçin",
  "Select an interface language.": "Bir arayüz dili seçin.",
  "Select the interface language and analytics currency.": "Arayüz dilini ve analiz para birimini seçin.",
  "Send a request": "Bir istek gönder",
  "Send email": "E-posta gönder",
  "Send request": "Talep gönder",
  "Sending...": "Gönderiliyor...",
  "Show": "Göster",
  "Show password": "Şifreyi göster",
  "Settings": "Ayarlar",
  "Sign in": "Oturum aç",
  "Signing in with Google...": "Google ile oturum açılıyor...",
  "Signing in...": "Oturum açılıyor...",
  "Some store products are not available yet: {{products}}.": "Bazı mağaza ürünleri henüz mevcut değil: {{products}}.",
  "Spending across all accounts": "Tüm hesaplarda harcama",
  "Start date": "Başlangıç tarihi",
  "Step {{current}} of 2: {{screen}}": "Adım {{current}}/2: {{screen}}",
  "Store products are available only on iOS and Android.": "Mağaza ürünleri yalnızca iOS ve Android'de mevcuttur.",
  "Store products are not available yet. Please check App Store or Google Play product setup.": "Mağaza ürünleri henüz mevcut değil. Lütfen App Store veya Google Play ürün kurulumunu kontrol edin.",
  "Store purchases are available only on iOS and Android.": "Mağazadan satın alınanlar yalnızca iOS ve Android'de kullanılabilir.",
  "Store purchases require iOS or Android": "Mağazadan satın alınanlar için iOS veya Android gerekir",
  "Store transaction is missing orderId.": "Mağaza işleminde orderId eksik.",
  "Store transaction is missing originalTransactionId.": "Mağaza işleminde originalTransactionId eksik.",
  "Store transaction is missing packageName.": "Mağaza işleminde packageName eksik.",
  "Store transaction is missing purchaseToken.": "Mağaza işleminde purchaseToken eksik.",
  "Store transaction is missing signed payload.": "Mağaza işleminde imzalı veri eksik.",
  "Store transaction is missing transactionId.": "Mağaza işleminde transactionId eksik.",
  "Subcategories": "Alt kategoriler",
  "Subject": "Konu",
  "Subscribe": "Abone ol",
  "Subscription": "Abonelik",
  "Subscription management": "Abonelik yönetimi",
  "Subscriptions": "Abonelikler",
  "Support": "Destek",
  "Tap the icon to select": "Seçmek için simgeye dokunun",
  "Telegram username": "Telegram kullanıcı adı",
  "The account will be deleted.": "Hesap silinecek.",
  "The base currency cannot be changed because budgets or transactions already exist.": "Bütçeler veya işlemler zaten mevcut olduğundan temel para birimi değiştirilemez.",
  "The budget category list for this month is empty.": "Bu aya ait bütçe kategorisi listesi boş.",
  "The category will be removed from this month's budget.": "Kategori bu ayın bütçesinden kaldırılacak.",
  "The payment is overdue. Premium access remains available through the grace-period date above.": "Ödeme gecikmiştir. Premium erişim, yukarıda belirtilen ek süre sonu tarihine kadar kullanılabilir.",
  "The purchase was not confirmed by the store. Try again.": "Satın alma işlemi mağaza tarafından onaylanmadı. Tekrar deneyin.",
  "The server did not respond in time. Try again.": "Sunucu zamanında yanıt vermedi. Tekrar deneyin.",
  "The transaction will be permanently deleted.": "İşlem kalıcı olarak silinecek.",
  "The verified purchase is not active.": "Doğrulanmış satın alma etkin değil.",
  "This account has no password. Password setup is handled separately.": "Bu hesabın şifresi yok. Şifre kurulumu ayrı olarak gerçekleştirilir.",
  "This purchase has already been received. Tap Restore purchases to restore the subscription.": "Bu satın alma işlemi zaten alındı. Aboneliği geri yüklemek için Satın alınanları geri yükle'ye dokunun.",
  "This purchase is linked to another MoneyDrive account. Sign in to the linked account or use a different App Store Sandbox account.": "Bu satın alma başka bir MoneyDrive hesabına bağlı. Bağlı hesapta oturum açın veya farklı bir App Store Sandbox hesabı kullanın.",
  "This purchase period has already expired.": "Bu satın alma süresi zaten doldu.",
  "This purchase period has expired. Select a current subscription.": "Bu satın alma süresi sona erdi. Mevcut bir aboneliği seçin.",
  "This takes less than a minute.": "Bu bir dakikadan az sürer.",
  "To goal: {{amount}}": "Hedefe kalan: {{amount}}",
  "To renew with LiqPay, open the web version and complete a new checkout.": "LiqPay ile yenilemek için web sürümünü açın ve yeni bir ödeme işlemini tamamlayın.",
  "Top categories by spending ({{currency}})": "Harcamaya göre en iyi kategoriler ({{currency}})",
  "Total": "Toplam",
  "Total balance": "Toplam bakiye",
  "Transactions": "İşlemler",
  "Transfer": "Transfer",
  "Type": "Tip",
  "Type: {{type}}": "Tür: {{type}}",
  "Unable to add the budget category (HTTP {{status}}).": "Bütçe kategorisi eklenemiyor (HTTP {{status}}).",
  "Unable to change password.": "Şifre değiştirilemiyor.",
  "Unable to connect to the server.": "Sunucuya bağlanılamıyor.",
  "Unable to create budget (HTTP {{status}}).": "Bütçe oluşturulamıyor (HTTP {{status}}).",
  "Unable to create the account.": "Hesap oluşturulamıyor.",
  "Unable to create the category (HTTP {{status}}).": "Kategori (HTTP {{status}}) oluşturulamıyor.",
  "Unable to delete the account.": "Hesap silinemiyor.",
  "Unable to delete the category (HTTP {{status}}).": "Kategori silinemiyor (HTTP {{status}}).",
  "Unable to delete the transaction.": "İşlem silinemiyor.",
  "Unable to load accounts (HTTP {{status}}).": "Hesaplar yüklenemiyor (HTTP {{status}}).",
  "Unable to load accounts.": "Hesaplar yüklenemiyor.",
  "Unable to load budget (HTTP {{status}}).": "Bütçe yüklenemiyor (HTTP {{status}}).",
  "Unable to load budgets (HTTP {{status}}).": "Bütçeler yüklenemiyor (HTTP {{status}}).",
  "Unable to load categories.": "Kategoriler yüklenemiyor.",
  "Unable to load category icons (HTTP {{status}}).": "Kategori simgeleri yüklenemiyor (HTTP {{status}}).",
  "Unable to load category icons.": "Kategori simgeleri yüklenemiyor.",
  "Unable to load dashboard (HTTP {{status}}).": "Kontrol paneli yüklenemiyor (HTTP {{status}}).",
  "Unable to load frequent categories.": "Sık kullanılan kategoriler yüklenemiyor.",
  "Unable to load settings.": "Ayarlar yüklenemiyor.",
  "Unable to load subscription products.": "Abonelik ürünleri yüklenemiyor.",
  "Unable to load subscription status.": "Abonelik durumu yüklenemiyor.",
  "Unable to load transactions.": "İşlemler yüklenemiyor.",
  "Unable to open onboarding.": "İlk katılım açılamıyor.",
  "Unable to open the account.": "Hesap açılamıyor.",
  "Unable to open the category for editing.": "Kategori düzenleme için açılamıyor.",
  "Unable to open the category.": "Kategori açılamıyor.",
  "Unable to open the transaction.": "İşlem açılamıyor.",
  "Unable to prepare the expense form.": "Gider formu hazırlanamadı.",
  "Unable to remove the budget category (HTTP {{status}}).": "Bütçe kategorisi kaldırılamıyor (HTTP {{status}}).",
  "Unable to resend the email.": "E-posta yeniden gönderilemiyor.",
  "Unable to save the profile.": "Profil kaydedilemiyor.",
  "Unable to save the transaction.": "İşlem kaydedilemiyor.",
  "Unable to send request.": "İstek gönderilemiyor.",
  "Unable to update balance.": "Bakiye güncellenemiyor.",
  "Unable to update the account.": "Hesap güncellenemiyor.",
  "Unable to update the budget category (HTTP {{status}}).": "Bütçe kategorisi güncellenemiyor (HTTP {{status}}).",
  "Unable to update the category (HTTP {{status}}).": "Kategori güncellenemiyor (HTTP {{status}}).",
  "Uncategorized": "Kategorize edilmemiş",
  "Until {{date}}": "{{date}}'ye kadar",
  "Untitled": "İsimsiz",
  "Unverified": "Doğrulanmamış",
  "Update": "Güncelle",
  "Verification": "Doğrulama",
  "Verification token": "Doğrulama jetonu",
  "Verified": "Doğrulandı",
  "Verify email": "E-postayı doğrula",
  "Verify with token": "Jetonla doğrula",
  "Verifying email...": "E-posta doğrulanıyor...",
  "View all": "Tümünü görüntüle",
  "View budgets": "Bütçeleri görüntüle",
  "We sent a verification email to {{email}}.": "{{email}} adresine bir doğrulama e-postası gönderdik.",
  "We usually respond within one business day.": "Genellikle bir iş günü içinde yanıt veririz.",
  "Your account and data are safe. Buy a new subscription to restore business features.": "Hesabınız ve verileriniz güvende. İş özelliklerini geri yüklemek için yeni bir abonelik satın alın.",
  "Your email": "E-postanız",
  "Your request has been sent to our support team.": "Talebiniz destek ekibimize iletilmiştir.",
  "Your session has expired. Sign in again.": "Oturumunuzun süresi doldu. Tekrar oturum açın.",
  "categories": "kategoriler",
  "the specified address": "belirtilen adres",
  "{{amount}} remaining": "{{amount}} kaldı",
  "{{percent}}% of plan": "Planın %{{percent}}'si",
  "‹ Back": "‹ Geri",
  "Account \"{{name}}\" will be deleted.": "\"{{name}}\" hesabı silinecek.",
  "Category \"{{name}}\" will be deleted.": "\"{{name}}\" kategorisi silinecek.",
  "Account deleted": "Hesap silindi",
  "Accounts, categories, budgets, transactions, transfers, settings, and access tokens will be deleted.": "Hesaplar, kategoriler, bütçeler, işlemler, transferler, ayarlar ve erişim belirteçleri silinecek.",
  "Apple did not return credentials required for account deletion.": "Apple, hesabı silmek için gereken kimlik bilgilerini döndürmedi.",
  "Confirm your identity": "Kimliğinizi doğrulayın",
  "Danger zone": "Tehlikeli bölge",
  "Delete MoneyDrive account": "MoneyDrive hesabını sil",
  "Delete MoneyDrive account permanently": "MoneyDrive hesabını kalıcı olarak sil",
  "Deleting account...": "Hesap siliniyor...",
  "Deleting your account permanently removes your profile and financial data. This action cannot be undone.": "Hesabınızı kalıcı olarak silmek profilinizi ve finansal verilerinizi kaldırır. Bu işlem geri alınamaz.",
  "Deleting MoneyDrive does not cancel App Store billing. Cancel the subscription in Apple settings if you no longer want it.": "MoneyDrive'ı silmek App Store faturalandırmasını iptal etmez. Artık istemiyorsanız Apple ayarlarından aboneliği iptal edin.",
  "Google Sign-In": "Google ile giriş",
  "Manage Apple subscription": "Apple aboneliğini yönet",
  "Sign in with Apple": "Apple ile giriş yap",
  "Type DELETE to confirm": "Onaylamak için DELETE yazın",
  "Unable to open subscription management.": "Abonelik yönetimi açılamadı.",
} as const;

export default trTR;
