const ua = {
  "+{{amount}} above plan 🚀": "+{{amount}} понад план 🚀",
  "30 days": "30 днів",
  "A subcategory cannot contain nested subcategories.": "Підкатегорія не може містити вкладені підкатегорії.",
  "Access denied.": "Доступ заборонено.",
  "Access until: {{date}}": "Доступ до: {{date}}",
  Account: "Рахунок",
  "Account settings": "Налаштування рахунку",
  "Account unavailable.": "Рахунок недоступний.",
  "Account: {{name}}": "Рахунок: {{name}}",
  Accounts: "Рахунки",
  "Across all accounts": "За всіма рахунками",
  Actual: "Фактично",
  "Actual expense": "Фактичні витрати",
  "Actual income": "Фактичний дохід",
  Add: "Додати",
  "Add account": "Додати рахунок",
  "Add budget": "Додати бюджет",
  "Add category": "Додати категорію",
  "Add details": "Додати деталі",
  "Add subcategory": "Додати підкатегорію",
  "Add to budget": "Додати до бюджету",
  "Add transaction": "Додати транзакцію",
  "Add your first expense": "Додайте першу витрату",
  "Adding...": "Додавання...",
  "All accounts": "Усі рахунки",
  "All categories": "Усі категорії",
  "All recorded income categories": "Усі збережені категорії доходів",
  "All steps completed": "Усі кроки завершено",
  "All time": "За весь час",
  "All types": "Усі типи",
  Amount: "Сума",
  "Analytics period": "Період аналітики",
  "Another store purchase is already in progress.": "Інша покупка в магазині вже виконується.",
  "Apple did not return an identity token.": "Apple не повернула токен ідентифікації.",
  "App Store saved {{actualProductId}} instead of {{requestedProductId}}. Check the current plan in App Store subscription settings.": "App Store зберіг {{actualProductId}} замість {{requestedProductId}}. Перевірте поточний план у налаштуваннях підписок App Store.",
  "Auto-renew off": "Автоподовження вимкнено",
  "Auto-renewal is off. Premium access remains available through the date above.": "Автоподовження вимкнено. Доступ Premium залишатиметься доступним до зазначеної вище дати.",
  "Available plans": "Доступні плани",
  Back: "Назад",
  "Back to sign in": "Повернутися до входу",
  Balance: "Баланс",
  "Balance update timed out. Check that the backend API is available.": "Час очікування оновлення балансу вичерпано. Перевірте доступність backend API.",
  "Base currency": "Базова валюта",
  Budget: "Бюджет",
  "Budget category": "Категорія бюджету",
  "Budget changes and category editing will be added after the backend API is extended.": "Зміни бюджету та редагування категорій буде додано після розширення backend API.",
  "Budget details": "Деталі бюджету",
  "Budget not found.": "Бюджет не знайдено.",
  "Budget progress": "Прогрес бюджету",
  Budgets: "Бюджети",
  C: "C",
  Cancel: "Скасувати",
  Categories: "Категорії",
  Category: "Категорія",
  "Category disabled": "Категорію вимкнено",
  "Category enabled": "Категорію увімкнено",
  "Category not found in the budget.": "Категорію не знайдено в бюджеті.",
  "Category unavailable.": "Категорія недоступна.",
  'Category "{{name}}" will become a group. It can no longer be selected in new transactions and budgets. Existing records will remain unchanged.': 'Категорія "{{name}}" стане групою. Її більше не можна буде вибирати в нових транзакціях і бюджетах. Наявні записи залишаться без змін.',
  "Category will become a group": "Категорія стане групою",
  "Change balance": "Змінити баланс",
  "Change password": "Змінити пароль",
  "Check your email": "Перевірте електронну пошту",
  "Checking authentication...": "Перевірка автентифікації...",
  "Choose an App Store or Google Play product below.": "Оберіть нижче продукт App Store або Google Play.",
  Comment: "Коментар",
  "Complete all password fields.": "Заповніть усі поля пароля.",
  "Confirm new password": "Підтвердьте новий пароль",
  "Confirm password": "Підтвердьте пароль",
  "Contact support": "Зв'язатися з підтримкою",
  Continue: "Продовжити",
  Create: "Створити",
  "Create account": "Створити обліковий запис",
  "Creating...": "Створення...",
  Currency: "Валюта",
  "Current password": "Поточний пароль",
  "Current plan": "Поточний план",
  Custom: "Власний",
  DONE: "ГОТОВО",
  Dashboard: "Огляд",
  Date: "Дата",
  "Date YYYY-MM-DD": "Дата РРРР-ММ-ДД",
  Delete: "Видалити",
  "Delete account?": "Видалити рахунок?",
  "Delete category": "Видалити категорію",
  "Delete category?": "Видалити категорію?",
  "Delete transaction": "Видалити транзакцію",
  "Delete transaction?": "Видалити транзакцію?",
  "Deleting...": "Видалення...",
  Description: "Опис",
  Disabled: "Вимкнено",
  Edit: "Редагувати",
  "Edit account": "Редагувати рахунок",
  "Edit transaction": "Редагувати транзакцію",
  Editing: "Редагування",
  "Email": "Електронна пошта",
  "Email resent. Retry in {{seconds}} seconds.": "Електронний лист надіслано повторно. Спробуйте ще раз через {{seconds}} с.",
  "Email sent. You can retry in about {{seconds}} seconds.": "Електронний лист надіслано. Спробуйте ще раз приблизно через {{seconds}} с.",
  "Email verification": "Підтвердження електронної пошти",
  "Email verified. You can now sign in.": "Електронну пошту підтверджено. Тепер можна увійти.",
  "Email was not sent. Try again in {{seconds}} seconds.": "Електронний лист не надіслано. Спробуйте ще раз через {{seconds}} с.",
  "End date": "Кінцева дата",
  "Enter a category name.": "Введіть назву категорії.",
  "Enter a date.": "Введіть дату.",
  "Enter a message.": "Введіть повідомлення.",
  "Enter a new password.": "Введіть новий пароль.",
  "Enter a subject.": "Введіть тему.",
  "Enter a valid amount.": "Введіть коректну суму.",
  "Enter a valid balance.": "Введіть коректний баланс.",
  "Enter a valid email address.": "Введіть коректну адресу електронної пошти.",
  "Enter a valid planned amount greater than 0.": "Введіть коректну планову суму, більшу за 0.",
  "Enter an account name.": "Введіть назву рахунку.",
  "Enter an amount greater than zero.": "Введіть суму, більшу за нуль.",
  "Enter your email": "Введіть електронну пошту",
  "Enter your email, name, and password.": "Введіть електронну пошту, ім'я та пароль.",
  "Enter your email.": "Введіть електронну пошту.",
  "Enter your name": "Введіть ім'я",
  Expense: "Витрата",
  "Expense categories": "Категорії витрат",
  "Expense categories are not available yet.": "Категорії витрат поки недоступні.",
  "Expense not submitted: complete the required fields.": "Витрату не збережено: заповніть обов'язкові поля.",
  Expenses: "Витрати",
  "Expenses and income": "Витрати та доходи",
  "Expenses this period": "Витрати за період",
  "Fill password": "Заповнити пароль",
  "Forgot password?": "Забули пароль?",
  Free: "Безкоштовний",
  "From {{date}}": "Від {{date}}",
  "Go to sign in": "Перейти до входу",
  "Goal reached! 🎉": "Мету досягнуто! 🎉",
  "Google Sign-In is not configured for this build.": "Вхід через Google не налаштовано для цієї збірки.",
  "Google did not return an ID token.": "Google не повернув ID-токен.",
  Group: "Група",
  Hide: "Приховати",
  "Hide form": "Приховати форму",
  "Hide password": "Приховати пароль",
  Home: "Дім",
  "I have a token": "У мене є токен",
  Icon: "Іконка",
  "If the account exists, an email has been sent.": "Якщо обліковий запис існує, електронний лист надіслано.",
  "If the account exists, an email has been sent. Retry in {{seconds}} seconds.": "Якщо обліковий запис існує, електронний лист надіслано. Спробуйте ще раз через {{seconds}} с.",
  "If the email contains a production link, paste the token manually for local testing.": "Якщо електронний лист містить production-посилання, вставте токен вручну для локального тестування.",
  Income: "Дохід",
  "Income categories": "Категорії доходів",
  "Income categories are not available yet.": "Категорії доходів поки недоступні.",
  "Income this period": "Доходи за період",
  "Initial setup": "Початкове налаштування",
  "Interface language": "Мова інтерфейсу",
  "Invalid accounts response format.": "Некоректний формат відповіді рахунків.",
  "Invalid budget response format.": "Некоректний формат відповіді бюджету.",
  "Keep an eye on all of your balances.": "Слідкуйте за всіма балансами.",
  "Language and base currency": "Мова та базова валюта",
  "LiqPay subscription can be cancelled only in the web version of the app.": "Підписку LiqPay можна скасувати лише у вебверсії застосунку.",
  "Loading accounts...": "Завантаження рахунків...",
  "Loading budget...": "Завантаження бюджету...",
  "Loading budgets...": "Завантаження бюджетів...",
  "Loading categories...": "Завантаження категорій...",
  "Loading dashboard...": "Завантаження огляду...",
  "Loading icons...": "Завантаження іконок...",
  "Loading onboarding...": "Завантаження онбордингу...",
  "Loading settings...": "Завантаження налаштувань...",
  "Loading store products...": "Завантаження продуктів магазину...",
  "Loading subscription status...": "Завантаження статусу підписки...",
  "Loading...": "Завантаження...",
  "Log in": "Увійти",
  "Login with Google": "Увійти через Google",
  Logout: "Вийти",
  "Manage on web": "Керувати у вебверсії",
  "Manage premium access": "Керувати Premium-доступом",
  "Manage subscription": "Керувати підпискою",
  "Maximum category depth is 2 levels": "Максимальна глибина категорій — 2 рівні",
  "Maximum category depth is 2 levels.": "Максимальна глибина категорій — 2 рівні.",
  Message: "Повідомлення",
  "Missing Android subscription offer token for selected product.": "Для вибраного продукту відсутній токен пропозиції Android-підписки.",
  "Missing account ID.": "Відсутній ідентифікатор рахунку.",
  "Missing budgetId.": "Відсутній budgetId.",
  "Missing reset token.": "Відсутній токен скидання.",
  "MoneyDrive.me": "MoneyDrive.me",
  "Month": "Місяць",
  More: "Ще",
  "More service sections": "Інші розділи сервісу",
  "Most frequent": "Найчастіші",
  Name: "Ім'я",
  "New account": "Новий рахунок",
  "New balance": "Новий баланс",
  "New category": "Нова категорія",
  "New email awaiting verification: {{email}}": "Нова електронна пошта очікує підтвердження: {{email}}",
  "New password": "Новий пароль",
  "New planned amount": "Нова планова сума",
  "No App Store Sandbox account is connected on this device. Add a sandbox tester in Settings > App Store > Sandbox Account.": "На цьому пристрої не підключено обліковий запис App Store Sandbox. Додайте sandbox-тестувальника в Settings > App Store > Sandbox Account.",
  "No account": "Немає рахунку",
  "No account data.": "Немає даних про рахунок.",
  "No accounts.": "Немає рахунків.",
  "No active purchases found.": "Активних покупок не знайдено.",
  "No active store source": "Немає активного джерела магазину",
  "No budget has been created for the selected month.": "За вибраний місяць бюджет ще не створено.",
  "No budgets for the selected period.": "За вибраний період немає бюджетів.",
  "No budgets found yet.": "Бюджетів поки не знайдено.",
  "No categories available to add.": "Немає доступних категорій для додавання.",
  "No categories found for the selected type.": "Для вибраного типу категорій не знайдено.",
  "No categories found.": "Категорій не знайдено.",
  "No categories.": "Немає категорій.",
  "No data for the selected period.": "За вибраний період немає даних.",
  "No data.": "Немає даних.",
  "No external management action is available.": "Зовнішня дія керування недоступна.",
  "No period selected": "Період не вибрано",
  "No transaction data.": "Немає даних про транзакції.",
  "No transactions yet.": "Транзакцій ще немає.",
  "Not enough data to add the category.": "Недостатньо даних для додавання категорії.",
  "Not set": "Не встановлено",
  Note: "Нотатка",
  Open: "Відкрити",
  "Open App Store account settings and choose Subscriptions.": "Відкрийте налаштування облікового запису App Store та виберіть Subscriptions.",
  "Open the subscription provider account settings to manage this plan.": "Відкрийте налаштування облікового запису постачальника підписки, щоб керувати цим планом.",
  "Overspent by {{amount}}": "Перевищення витрат на {{amount}}",
  "Parent: {{name}}": "Батьківська категорія: {{name}}",
  Password: "Пароль",
  "Password changed.": "Пароль змінено.",
  "Password recovery": "Відновлення пароля",
  "Password updated. You can now sign in.": "Пароль оновлено. Тепер можна увійти.",
  "Passwords do not match.": "Паролі не збігаються.",
  "Paste the verification token.": "Вставте токен підтвердження.",
  "Period: {{period}}": "Період: {{period}}",
  "Plan ({{currency}})": "План ({{currency}})",
  "Plan / actual / remaining by category": "План / факт / залишок за категоріями",
  "Plan {{plan}} · Actual {{actual}}": "План {{plan}} · Факт {{actual}}",
  "Plans and billing": "Плани й оплата",
  "Planned amount ({{currency}})": "Планова сума ({{currency}})",
  "Planned expense": "Планові витрати",
  "Planned income": "Плановий дохід",
  "Popular categories": "Популярні категорії",
  Premium: "Premium",
  "Premium is active.": "Premium активний.",
  "Premium is active. The plan change will take effect on the next App Store renewal.": "Premium активний. Зміна плану набуде чинності під час наступного продовження в App Store.",
  "Processing...": "Обробка...",
  "Product temporarily unavailable.": "Продукт тимчасово недоступний.",
  "Product: {{product}}": "Продукт: {{product}}",
  "Products for {{platform}}": "Продукти для {{platform}}",
  Profile: "Профіль",
  "Profile and security": "Профіль і безпека",
  "Profile saved.": "Профіль збережено.",
  "Profile, language, and security": "Профіль, мова та безпека",
  "Purchase not confirmed. Try again.": "Покупку не підтверджено. Спробуйте ще раз.",
  "Recent transactions": "Останні транзакції",
  Registration: "Реєстрація",
  Remaining: "Залишок",
  "Renewal canceled": "Продовження скасовано",
  "Request failed (HTTP {{status}}).": "Запит не виконано (HTTP {{status}}).",
  "Resend email": "Надіслати лист повторно",
  "Restore purchases": "Відновити покупки",
  "Restored purchases: {{count}}.": "Відновлено покупок: {{count}}.",
  "Restoring...": "Відновлення...",
  Retry: "Повторити",
  "Root level": "Кореневий рівень",
  "Runtime category tree": "Поточне дерево категорій",
  Save: "Зберегти",
  "Save and continue": "Зберегти та продовжити",
  "Save balance": "Зберегти баланс",
  "Save password": "Зберегти пароль",
  "Saving...": "Збереження...",
  "Segments show amounts by category.": "Сегменти показують суми за категоріями.",
  Select: "Вибрати",
  "Select a base currency.": "Виберіть базову валюту.",
  "Select a category": "Виберіть категорію",
  "Select a category and an account.": "Виберіть категорію та рахунок.",
  "Select a category.": "Виберіть категорію.",
  "Select a currency": "Виберіть валюту",
  "Select a date": "Виберіть дату",
  "Select a language": "Виберіть мову",
  "Select a subcategory. A parent category cannot be added.": "Виберіть підкатегорію. Батьківську категорію додати не можна.",
  "Select account": "Виберіть рахунок",
  "Select an account.": "Виберіть рахунок.",
  "Select an icon from the shared catalog": "Виберіть іконку зі спільного каталогу",
  "Select an interface language.": "Виберіть мову інтерфейсу.",
  "Select the interface language and analytics currency.": "Виберіть мову інтерфейсу та валюту аналітики.",
  "Send a request": "Надіслати запит",
  "Send email": "Надіслати лист",
  "Send request": "Надіслати запит",
  "Sending...": "Надсилання...",
  Show: "Показати",
  "Show password": "Показати пароль",
  Settings: "Налаштування",
  "Sign in": "Увійти",
  "Signing in with Google...": "Вхід через Google...",
  "Signing in...": "Вхід...",
  "Some store products are not available yet: {{products}}.": "Деякі продукти магазину поки недоступні: {{products}}.",
  "Spending across all accounts": "Витрати за всіма рахунками",
  "Start date": "Початкова дата",
  "Step {{current}} of 2: {{screen}}": "Крок {{current}} з 2: {{screen}}",
  "Store products are available only on iOS and Android.": "Продукти магазину доступні лише на iOS та Android.",
  "Store products are not available yet. Please check App Store or Google Play product setup.": "Продукти магазину поки недоступні. Перевірте налаштування продуктів App Store або Google Play.",
  "Store purchases are available only on iOS and Android.": "Покупки в магазині доступні лише на iOS та Android.",
  "Store purchases require iOS or Android": "Для покупок у магазині потрібні iOS або Android",
  "Store transaction is missing orderId.": "У транзакції магазину відсутній orderId.",
  "Store transaction is missing originalTransactionId.": "У транзакції магазину відсутній originalTransactionId.",
  "Store transaction is missing packageName.": "У транзакції магазину відсутній packageName.",
  "Store transaction is missing purchaseToken.": "У транзакції магазину відсутній purchaseToken.",
  "Store transaction is missing signed payload.": "У транзакції магазину відсутні підписані дані.",
  "Store transaction is missing transactionId.": "У транзакції магазину відсутній transactionId.",
  Subcategories: "Підкатегорії",
  Subject: "Тема",
  Subscribe: "Підписатися",
  Subscription: "Підписка",
  "Subscription management": "Керування підпискою",
  Subscriptions: "Підписки",
  Support: "Підтримка",
  "Tap the icon to select": "Торкніться іконки, щоб вибрати",
  "Telegram username": "Ім'я користувача Telegram",
  "The account will be deleted.": "Рахунок буде видалено.",
  "The base currency cannot be changed because budgets or transactions already exist.": "Базову валюту не можна змінити, оскільки вже існують бюджети або транзакції.",
  "The budget category list for this month is empty.": "Список категорій бюджету за цей місяць порожній.",
  "The category will be removed from this month's budget.": "Категорію буде видалено з бюджету цього місяця.",
  "The payment is overdue. Premium access remains available through the grace-period date above.": "Платіж прострочено. Доступ Premium залишається доступним до завершення пільгового періоду, зазначеного вище.",
  "The purchase was not confirmed by the store. Try again.": "Магазин не підтвердив покупку. Спробуйте ще раз.",
  "The server did not respond in time. Try again.": "Сервер не відповів вчасно. Спробуйте ще раз.",
  "The transaction will be permanently deleted.": "Транзакцію буде видалено назавжди.",
  "The verified purchase is not active.": "Підтверджена покупка неактивна.",
  "This account has no password. Password setup is handled separately.": "Цей обліковий запис не має пароля. Налаштування пароля виконується окремо.",
  "This purchase has already been received. Tap Restore purchases to restore the subscription.": "Цю покупку вже отримано. Натисніть «Відновити покупки», щоб відновити підписку.",
  "This purchase is linked to another MoneyDrive account. Sign in to the linked account or use a different App Store Sandbox account.": "Цю покупку пов'язано з іншим обліковим записом MoneyDrive. Увійдіть до пов'язаного облікового запису або використайте інший обліковий запис App Store Sandbox.",
  "This purchase period has already expired.": "Період цієї покупки вже завершився.",
  "This purchase period has expired. Select a current subscription.": "Період цієї покупки завершився. Виберіть актуальну підписку.",
  "This takes less than a minute.": "Це займе менше хвилини.",
  "To goal: {{amount}}": "До мети: {{amount}}",
  "To renew with LiqPay, open the web version and complete a new checkout.": "Щоб поновити підписку через LiqPay, відкрийте вебверсію та оформіть нову покупку.",
  "Top categories by spending ({{currency}})": "Найбільші категорії витрат ({{currency}})",
  Total: "Усього",
  "Total balance": "Загальний баланс",
  Transactions: "Транзакції",
  Transfer: "Переказ",
  Type: "Тип",
  "Type: {{type}}": "Тип: {{type}}",
  "Unable to add the budget category (HTTP {{status}}).": "Не вдалося додати категорію бюджету (HTTP {{status}}).",
  "Unable to change password.": "Не вдалося змінити пароль.",
  "Unable to connect to the server.": "Не вдалося підключитися до сервера.",
  "Unable to create budget (HTTP {{status}}).": "Не вдалося створити бюджет (HTTP {{status}}).",
  "Unable to create the account.": "Не вдалося створити рахунок.",
  "Unable to create the category (HTTP {{status}}).": "Не вдалося створити категорію (HTTP {{status}}).",
  "Unable to delete the account.": "Не вдалося видалити рахунок.",
  "Unable to delete the category (HTTP {{status}}).": "Не вдалося видалити категорію (HTTP {{status}}).",
  "Unable to delete the transaction.": "Не вдалося видалити транзакцію.",
  "Unable to load accounts (HTTP {{status}}).": "Не вдалося завантажити рахунки (HTTP {{status}}).",
  "Unable to load accounts.": "Не вдалося завантажити рахунки.",
  "Unable to load budget (HTTP {{status}}).": "Не вдалося завантажити бюджет (HTTP {{status}}).",
  "Unable to load budgets (HTTP {{status}}).": "Не вдалося завантажити бюджети (HTTP {{status}}).",
  "Unable to load categories.": "Не вдалося завантажити категорії.",
  "Unable to load category icons (HTTP {{status}}).": "Не вдалося завантажити іконки категорій (HTTP {{status}}).",
  "Unable to load category icons.": "Не вдалося завантажити іконки категорій.",
  "Unable to load dashboard (HTTP {{status}}).": "Не вдалося завантажити огляд (HTTP {{status}}).",
  "Unable to load frequent categories.": "Не вдалося завантажити найчастіші категорії.",
  "Unable to load settings.": "Не вдалося завантажити налаштування.",
  "Unable to load subscription products.": "Не вдалося завантажити продукти підписки.",
  "Unable to load subscription status.": "Не вдалося завантажити статус підписки.",
  "Unable to load transactions.": "Не вдалося завантажити транзакції.",
  "Unable to open onboarding.": "Не вдалося відкрити онбординг.",
  "Unable to open the account.": "Не вдалося відкрити рахунок.",
  "Unable to open the category for editing.": "Не вдалося відкрити категорію для редагування.",
  "Unable to open the category.": "Не вдалося відкрити категорію.",
  "Unable to open the transaction.": "Не вдалося відкрити транзакцію.",
  "Unable to prepare the expense form.": "Не вдалося підготувати форму витрати.",
  "Unable to remove the budget category (HTTP {{status}}).": "Не вдалося вилучити категорію бюджету (HTTP {{status}}).",
  "Unable to resend the email.": "Не вдалося повторно надіслати електронний лист.",
  "Unable to save the profile.": "Не вдалося зберегти профіль.",
  "Unable to save the transaction.": "Не вдалося зберегти транзакцію.",
  "Unable to send request.": "Не вдалося надіслати запит.",
  "Unable to update balance.": "Не вдалося оновити баланс.",
  "Unable to update the account.": "Не вдалося оновити рахунок.",
  "Unable to update the budget category (HTTP {{status}}).": "Не вдалося оновити категорію бюджету (HTTP {{status}}).",
  "Unable to update the category (HTTP {{status}}).": "Не вдалося оновити категорію (HTTP {{status}}).",
  Uncategorized: "Без категорії",
  "Until {{date}}": "До {{date}}",
  Untitled: "Без назви",
  Unverified: "Не підтверджено",
  Update: "Оновити",
  Verification: "Підтвердження",
  "Verification token": "Токен підтвердження",
  Verified: "Підтверджено",
  "Verify email": "Підтвердити електронну пошту",
  "Verify with token": "Підтвердити токеном",
  "Verifying email...": "Підтвердження електронної пошти...",
  "View all": "Переглянути все",
  "View budgets": "Переглянути бюджети",
  "We sent a verification email to {{email}}.": "Ми надіслали лист для підтвердження на адресу {{email}}.",
  "We usually respond within one business day.": "Зазвичай ми відповідаємо протягом одного робочого дня.",
  "Your account and data are safe. Buy a new subscription to restore business features.": "Ваш обліковий запис і дані в безпеці. Придбайте нову підписку, щоб відновити функції бізнесу.",
  "Your email": "Ваша електронна пошта",
  "Your request has been sent to our support team.": "Ваш запит надіслано до служби підтримки.",
  "Your session has expired. Sign in again.": "Ваш сеанс завершився. Увійдіть знову.",
  categories: "категорій",
  "the specified address": "вказану адресу",
  "{{amount}} remaining": "Залишилося {{amount}}",
  "{{percent}}% of plan": "{{percent}}% плану",
  "‹ Back": "‹ Назад",
  'Account "{{name}}" will be deleted.': 'Рахунок «{{name}}» буде видалено.',
  'Category "{{name}}" will be deleted.': 'Категорію «{{name}}» буде видалено.',
} as const;

export default ua;
