const zhCN = {
  "+{{amount}} above plan 🚀": "超出预算 {{amount}} 🚀",
  "30 days": "30天",
  "A subcategory cannot contain nested subcategories.": "子类别不能包含嵌套子类别。",
  "Access denied.": "拒绝访问。",
  "Access until: {{date}}": "访问截止时间：{{date}}",
  "Account": "账户",
  "Account settings": "账户设置",
  "Account unavailable.": "帐户不可用。",
  "Account: {{name}}": "账号：{{name}}",
  "Accounts": "账户",
  "Across all accounts": "跨所有账户",
  "Actual": "实际",
  "Actual expense": "实际费用",
  "Actual income": "实际收入",
  "Add": "添加",
  "Add account": "添加帐户",
  "Add budget": "添加预算",
  "Add category": "添加类别",
  "Add details": "添加详细信息",
  "Add subcategory": "添加子类别",
  "Add to budget": "添加到预算",
  "Add transaction": "添加交易",
  "Add your first expense": "添加您的第一笔费用",
  "Adding...": "添加...",
  "All accounts": "所有账户",
  "All categories": "所有类别",
  "All recorded income categories": "所有记录的收入类别",
  "All steps completed": "所有步骤已完成",
  "All time": "所有时间",
  "All types": "所有类型",
  "Amount": "金额",
  "Analytics period": "分析期",
  "Another store purchase is already in progress.": "另一家商店的采购已经在进行中。",
  "Apple did not return an identity token.": "Apple 没有返回身份令牌。",
  "App Store saved {{actualProductId}} instead of {{requestedProductId}}. Check the current plan in App Store subscription settings.": "App Store 保存的是 {{actualProductId}} 而不是 {{requestedProductId}}。请在 App Store 订阅设置中检查当前订阅方案。",
  "Auto-renew off": "自动续订关闭",
  "Auto-renewal is off. Premium access remains available through the date above.": "自动续订已关闭。在上述日期之前，高级访问权限仍然可用。",
  "Available plans": "可选订阅方案",
  "Back": "返回",
  "Back to sign in": "返回登录",
  "Balance": "余额",
  "Balance update timed out. Check that the backend API is available.": "余额更新超时。检查后端API是否可用。",
  "Base currency": "基础货币",
  "Budget": "预算",
  "Budget category": "预算类别",
  "Budget changes and category editing will be added after the backend API is extended.": "后端API扩展后将增加预算变更和类别编辑功能。",
  "Budget details": "预算详情",
  "Budget not found.": "未找到预算。",
  "Budget progress": "预算进度",
  "Budgets": "预算",
  "C": "C",
  "Cancel": "取消",
  "Categories": "类别",
  "Category": "类别",
  "Category disabled": "类别已禁用",
  "Category enabled": "已启用类别",
  "Category not found in the budget.": "预算中未找到类别。",
  "Category unavailable.": "类别不可用。",
  "Category \"{{name}}\" will become a group. It can no longer be selected in new transactions and budgets. Existing records will remain unchanged.": "类别“{{name}}”将成为一个组。不能再在新的交易和预算中选择它。现有记录将保持不变。",
  "Category will become a group": "类别将成为一个组",
  "Change balance": "更改余额",
  "Change password": "更改密码",
  "Check your email": "检查您的电子邮件",
  "Checking authentication...": "正在检查身份验证...",
  "Choose an App Store or Google Play product below.": "在下面选择一个 App Store 或 Google Play 产品。",
  "Comment": "评论",
  "Complete all password fields.": "填写所有密码字段。",
  "Confirm new password": "确认新密码",
  "Confirm password": "确认密码",
  "Contact support": "联系支持团队",
  "Continue": "继续",
  "Create": "创建",
  "Create account": "创建账户",
  "Creating...": "正在创建...",
  "Currency": "货币",
  "Current password": "当前密码",
  "Current plan": "当前订阅方案",
  "Custom": "自定义",
  "DONE": "完毕",
  "Dashboard": "仪表板",
  "Date": "日期",
  "Date YYYY-MM-DD": "日期 YYYY-MM-DD",
  "Delete": "删除",
  "Delete account?": "删除帐户？",
  "Delete category": "删除类别",
  "Delete category?": "删除类别？",
  "Delete transaction": "删除交易",
  "Delete transaction?": "删除交易？",
  "Deleting...": "正在删除...",
  "Description": "描述",
  "Disabled": "禁用",
  "Edit": "编辑",
  "Edit account": "编辑帐户",
  "Edit transaction": "编辑交易",
  "Editing": "编辑",
  "Email": "电子邮件",
  "Email resent. Retry in {{seconds}} seconds.": "电子邮件已重新发送。在 {{seconds}} 秒后重试。",
  "Email sent. You can retry in about {{seconds}} seconds.": "电子邮件已发送。您可以在大约 {{seconds}} 秒后重试。",
  "Email verification": "邮箱验证",
  "Email verified. You can now sign in.": "电子邮件已验证。您现在可以登录。",
  "Email was not sent. Try again in {{seconds}} seconds.": "电子邮件未发送。 {{seconds}} 秒后重试。",
  "End date": "结束日期",
  "Enter a category name.": "输入类别名称。",
  "Enter a date.": "输入日期。",
  "Enter a message.": "输入消息。",
  "Enter a new password.": "输入新密码。",
  "Enter a subject.": "输入主题。",
  "Enter a valid amount.": "输入有效金额。",
  "Enter a valid balance.": "输入有效余额。",
  "Enter a valid email address.": "输入有效的电子邮件地址。",
  "Enter a valid planned amount greater than 0.": "输入大于 0 的有效计划金额。",
  "Enter an account name.": "输入帐户名。",
  "Enter an amount greater than zero.": "输入大于零的金额。",
  "Enter your email": "输入您的电子邮件",
  "Enter your email, name, and password.": "输入您的电子邮件、姓名和密码。",
  "Enter your email.": "输入您的电子邮件。",
  "Enter your name": "输入你的名字",
  "Expense": "支出",
  "Expense categories": "支出类别",
  "Expense categories are not available yet.": "费用类别尚不可用。",
  "Expense not submitted: complete the required fields.": "未提交费用：填写必填字段。",
  "Expenses": "支出",
  "Expenses and income": "费用和收入",
  "Expenses this period": "本期费用",
  "Fill password": "填写密码",
  "Forgot password?": "忘记密码？",
  "Free": "免费",
  "From {{date}}": "来自{{date}}",
  "Go to sign in": "前往登录",
  "Goal reached! 🎉": "目标达到了！ 🎉",
  "Google Sign-In is not configured for this build.": "未为此版本配置 Google 登录。",
  "Google did not return an ID token.": "Google 没有返回 ID 令牌。",
  "Group": "团体",
  "Hide": "隐藏",
  "Hide form": "隐藏表格",
  "Hide password": "隐藏密码",
  "Home": "首页",
  "I have a token": "我有一个令牌",
  "Icon": "图标",
  "If the account exists, an email has been sent.": "如果该帐户存在，则会发送电子邮件。",
  "If the account exists, an email has been sent. Retry in {{seconds}} seconds.": "如果该帐户存在，则会发送电子邮件。在 {{seconds}} 秒后重试。",
  "If the email contains a production link, paste the token manually for local testing.": "如果电子邮件包含生产链接，请手动粘贴令牌以进行本地测试。",
  "Income": "收入",
  "Income categories": "收入类别",
  "Income categories are not available yet.": "收入类别尚不可用。",
  "Income this period": "本期收入",
  "Initial setup": "初始设置",
  "Interface language": "界面语言",
  "Invalid accounts response format.": "帐户响应格式​​无效。",
  "Invalid budget response format.": "预算回复格式无效。",
  "Keep an eye on all of your balances.": "密切关注您的所有余额。",
  "Language and base currency": "语言和基础货币",
  "LiqPay subscription can be cancelled only in the web version of the app.": "LiqPay 订阅只能在应用程序的网页版中取消。",
  "Loading accounts...": "正在加载帐户...",
  "Loading budget...": "正在加载预算...",
  "Loading budgets...": "正在加载预算...",
  "Loading categories...": "正在加载类别...",
  "Loading dashboard...": "正在加载仪表板...",
  "Loading icons...": "正在加载图标...",
  "Loading onboarding...": "正在加载初始设置...",
  "Loading settings...": "正在加载设置...",
  "Loading store products...": "正在加载商店产品...",
  "Loading subscription status...": "正在加载订阅状态...",
  "Loading...": "加载中...",
  "Log in": "登录",
  "Login with Google": "使用 Google 登录",
  "Logout": "退出",
  "Manage on web": "在网络上管理",
  "Manage premium access": "管理高级访问权限",
  "Manage subscription": "管理订阅",
  "Maximum category depth is 2 levels": "最大类别深度为 2 级",
  "Maximum category depth is 2 levels.": "最大类别深度为 2 级。",
  "Message": "消息",
  "Missing Android subscription offer token for selected product.": "缺少所选产品的 Android 订阅优惠令牌。",
  "Missing account ID.": "缺少帐户 ID。",
  "Missing budgetId.": "缺少预算 ID。",
  "Missing reset token.": "缺少重置令牌。",
  "MoneyDrive.me": "MoneyDrive.me",
  "Month": "月",
  "More": "更多的",
  "More service sections": "更多服务板块",
  "Most frequent": "最常见的",
  "Name": "名称",
  "New account": "新账户",
  "New balance": "新余额",
  "New category": "新类别",
  "New email awaiting verification: {{email}}": "新电子邮件等待验证：{{email}}",
  "New password": "新密码",
  "New planned amount": "新计划金额",
  "No App Store Sandbox account is connected on this device. Add a sandbox tester in Settings > App Store > Sandbox Account.": "此设备上没有连接 App Store Sandbox 帐户。在“设置”>“App Store”>“沙盒帐户”中添加沙盒测试人员。",
  "No account": "没有账户",
  "No account data.": "没有帐户数据。",
  "No accounts.": "没有账户。",
  "No active purchases found.": "未发现活跃购买。",
  "No active store source": "没有活跃的商店来源",
  "No budget has been created for the selected month.": "尚未为所选月份创建预算。",
  "No budgets for the selected period.": "所选期间没有预算。",
  "No budgets found yet.": "尚未找到预算。",
  "No categories available to add.": "没有可添加的类别。",
  "No categories found for the selected type.": "未找到所选类型的类别。",
  "No categories found.": "未找到类别。",
  "No categories.": "没有类别。",
  "No data for the selected period.": "所选期间没有数据。",
  "No data.": "没有数据。",
  "No external management action is available.": "没有可用的外部管理措施。",
  "No period selected": "未选择期间",
  "No transaction data.": "无交易数据。",
  "No transactions yet.": "还没有交易。",
  "Not enough data to add the category.": "数据不足，无法添加类别。",
  "Not set": "未设置",
  "Note": "笔记",
  "Open": "打开",
  "Open App Store account settings and choose Subscriptions.": "打开 App Store 帐户设置并选择订阅。",
  "Open the subscription provider account settings to manage this plan.": "打开订阅提供商的账户设置以管理此订阅方案。",
  "Overspent by {{amount}}": "{{amount}} 超支",
  "Parent: {{name}}": "父级：{{name}}",
  "Password": "密码",
  "Password changed.": "密码已更改。",
  "Password recovery": "密码恢复",
  "Password updated. You can now sign in.": "密码已更新。您现在可以登录。",
  "Passwords do not match.": "密码不匹配。",
  "Paste the verification token.": "粘贴验证令牌。",
  "Period: {{period}}": "期间：{{period}}",
  "Plan ({{currency}})": "计划（{{currency}}）",
  "Plan / actual / remaining by category": "计划/实际/剩余（按类别）",
  "Plan {{plan}} · Actual {{actual}}": "计划 {{plan}} · 实际 {{actual}}",
  "Plans and billing": "订阅方案与账单",
  "Planned amount ({{currency}})": "计划金额（{{currency}}）",
  "Planned expense": "计划费用",
  "Planned income": "计划收入",
  "Popular categories": "热门类别",
  "Premium": "Premium",
  "Premium is active.": "高级版已激活。",
  "Premium is active. The plan change will take effect on the next App Store renewal.": "Premium 已激活。订阅方案变更将在下一次 App Store 续订时生效。",
  "Processing...": "处理中...",
  "Product temporarily unavailable.": "产品暂时不可用。",
  "Product: {{product}}": "产品：{{product}}",
  "Products for {{platform}}": "适用于 {{platform}} 的产品",
  "Profile": "个人资料",
  "Profile and security": "个人资料和安全性",
  "Profile saved.": "个人资料已保存。",
  "Profile, language, and security": "个人资料、语言和安全性",
  "Purchase not confirmed. Try again.": "购买未确认。再试一次。",
  "Recent transactions": "最近交易",
  "Registration": "登记",
  "Remaining": "其余的",
  "Renewal canceled": "续订已取消",
  "Request failed (HTTP {{status}}).": "请求失败（HTTP {{status}}）。",
  "Resend email": "重新发送电子邮件",
  "Restore purchases": "恢复购买",
  "Restored purchases: {{count}}.": "恢复购买：{{count}}。",
  "Restoring...": "正在恢复...",
  "Retry": "重试",
  "Root level": "根级",
  "Runtime category tree": "运行时类别树",
  "Save": "保存",
  "Save and continue": "保存并继续",
  "Save balance": "保存余额",
  "Save password": "保存密码",
  "Saving...": "保存...",
  "Segments show amounts by category.": "细分按类别显示金额。",
  "Select": "选择",
  "Select a base currency.": "选择基础货币。",
  "Select a category": "选择一个类别",
  "Select a category and an account.": "选择类别和帐户。",
  "Select a category.": "选择一个类别。",
  "Select a currency": "选择货币",
  "Select a date": "选择日期",
  "Select a language": "选择语言",
  "Select a subcategory. A parent category cannot be added.": "选择一个子类别。无法添加父类别。",
  "Select account": "选择账户",
  "Select an account.": "选择一个帐户。",
  "Select an icon from the shared catalog": "从共享目录中选择一个图标",
  "Select an interface language.": "选择界面语言。",
  "Select the interface language and analytics currency.": "选择界面语言和分析货币。",
  "Send a request": "发送请求",
  "Send email": "发送电子邮件",
  "Send request": "发送请求",
  "Sending...": "正在发送...",
  "Show": "展示",
  "Show password": "显示密码",
  "Settings": "设置",
  "Sign in": "登录",
  "Signing in with Google...": "正在使用 Google 登录...",
  "Signing in...": "正在登录...",
  "Some store products are not available yet: {{products}}.": "部分商店产品尚未上市：{{products}}。",
  "Spending across all accounts": "所有账户的支出",
  "Start date": "开始日期",
  "Step {{current}} of 2: {{screen}}": "第 2 步中的步骤 {{current}}：{{screen}}",
  "Store products are available only on iOS and Android.": "商店产品仅适用于 iOS 和 Android。",
  "Store products are not available yet. Please check App Store or Google Play product setup.": "商店产品尚未上市。请检查 App Store 或 Google Play 产品设置。",
  "Store purchases are available only on iOS and Android.": "商店购买仅适用于 iOS 和 Android。",
  "Store purchases require iOS or Android": "商店购买需要 iOS 或 Android",
  "Store transaction is missing orderId.": "商店交易缺少 orderId。",
  "Store transaction is missing originalTransactionId.": "商店交易缺少originalTransactionId。",
  "Store transaction is missing packageName.": "商店交易缺少 packageName。",
  "Store transaction is missing purchaseToken.": "商店交易缺少purchaseToken。",
  "Store transaction is missing signed payload.": "商店交易缺少签名有效载荷。",
  "Store transaction is missing transactionId.": "商店交易缺少 transactionId。",
  "Subcategories": "子类别",
  "Subject": "主题",
  "Subscribe": "订阅",
  "Subscription": "订阅",
  "Subscription management": "订阅管理",
  "Subscriptions": "订阅",
  "Support": "支持",
  "Tap the icon to select": "点击图标进行选择",
  "Telegram username": "电报用户名",
  "The account will be deleted.": "该帐户将被删除。",
  "The base currency cannot be changed because budgets or transactions already exist.": "由于预算或交易已存在，因此无法更改基础货币。",
  "The budget category list for this month is empty.": "本月的预算类别列表为空。",
  "The category will be removed from this month's budget.": "该类别将从本月的预算中删除。",
  "The payment is overdue. Premium access remains available through the grace-period date above.": "付款已逾期。Premium 权益可使用至上述宽限期结束日期。",
  "The purchase was not confirmed by the store. Try again.": "该购买未经商店确认。再试一次。",
  "The server did not respond in time. Try again.": "服务器没有及时响应。再试一次。",
  "The transaction will be permanently deleted.": "该交易将被永久删除。",
  "The verified purchase is not active.": "已验证的购买未激活。",
  "This account has no password. Password setup is handled separately.": "该帐户没有密码。密码设置单独处理。",
  "This purchase has already been received. Tap Restore purchases to restore the subscription.": "此购买已收到。点击恢复购买以恢复订阅。",
  "This purchase is linked to another MoneyDrive account. Sign in to the linked account or use a different App Store Sandbox account.": "此购买链接到另一个 MoneyDrive 帐户。登录链接的帐户或使用其他 App Store Sandbox 帐户。",
  "This purchase period has already expired.": "此购买期限已过。",
  "This purchase period has expired. Select a current subscription.": "本次购买期限已过。选择当前订阅。",
  "This takes less than a minute.": "这需要不到一分钟的时间。",
  "To goal: {{amount}}": "目标：{{amount}}",
  "To renew with LiqPay, open the web version and complete a new checkout.": "要使用 LiqPay 续订，请打开网页版本并完成新的结账。",
  "Top categories by spending ({{currency}})": "按支出排名最高的类别 ({{currency}})",
  "Total": "总计",
  "Total balance": "总余额",
  "Transactions": "交易",
  "Transfer": "转账",
  "Type": "类型",
  "Type: {{type}}": "类型：{{type}}",
  "Unable to add the budget category (HTTP {{status}}).": "无法添加预算类别 (HTTP {{status}})。",
  "Unable to change password.": "无法更改密码。",
  "Unable to connect to the server.": "无法连接到服务器。",
  "Unable to create budget (HTTP {{status}}).": "无法创建预算 (HTTP {{status}})。",
  "Unable to create the account.": "无法创建帐户。",
  "Unable to create the category (HTTP {{status}}).": "无法创建类别 (HTTP {{status}})。",
  "Unable to delete the account.": "无法删除帐户。",
  "Unable to delete the category (HTTP {{status}}).": "无法删除类别 (HTTP {{status}})。",
  "Unable to delete the transaction.": "无法删除交易。",
  "Unable to load accounts (HTTP {{status}}).": "无法加载帐户 (HTTP {{status}})。",
  "Unable to load accounts.": "无法加载帐户。",
  "Unable to load budget (HTTP {{status}}).": "无法加载预算 (HTTP {{status}})。",
  "Unable to load budgets (HTTP {{status}}).": "无法加载预算 (HTTP {{status}})。",
  "Unable to load categories.": "无法加载类别。",
  "Unable to load category icons (HTTP {{status}}).": "无法加载类别图标 (HTTP {{status}})。",
  "Unable to load category icons.": "无法加载类别图标。",
  "Unable to load dashboard (HTTP {{status}}).": "无法加载仪表板 (HTTP {{status}})。",
  "Unable to load frequent categories.": "无法加载常用类别。",
  "Unable to load settings.": "无法加载设置。",
  "Unable to load subscription products.": "无法加载订阅产品。",
  "Unable to load subscription status.": "无法加载订阅状态。",
  "Unable to load transactions.": "无法加载交易。",
  "Unable to open onboarding.": "无法打开初始设置。",
  "Unable to open the account.": "无法开设账户。",
  "Unable to open the category for editing.": "无法打开类别进行编辑。",
  "Unable to open the category.": "无法打开类别。",
  "Unable to open the transaction.": "无法打开交易。",
  "Unable to prepare the expense form.": "无法准备费用表格。",
  "Unable to remove the budget category (HTTP {{status}}).": "无法删除预算类别 (HTTP {{status}})。",
  "Unable to resend the email.": "无法重新发送电子邮件。",
  "Unable to save the profile.": "无法保存配置文件。",
  "Unable to save the transaction.": "无法保存交易。",
  "Unable to send request.": "无法发送请求。",
  "Unable to update balance.": "无法更新余额。",
  "Unable to update the account.": "无法更新帐户。",
  "Unable to update the budget category (HTTP {{status}}).": "无法更新预算类别 (HTTP {{status}})。",
  "Unable to update the category (HTTP {{status}}).": "无法更新类别 (HTTP {{status}})。",
  "Uncategorized": "未分类",
  "Until {{date}}": "直到{{date}}",
  "Untitled": "无题",
  "Unverified": "未验证",
  "Update": "更新",
  "Verification": "确认",
  "Verification token": "验证令牌",
  "Verified": "已验证",
  "Verify email": "验证电子邮件",
  "Verify with token": "使用令牌验证",
  "Verifying email...": "正在验证电子邮件...",
  "View all": "查看全部",
  "View budgets": "查看预算",
  "We sent a verification email to {{email}}.": "我们向 {{email}} 发送了一封验证电子邮件。",
  "We usually respond within one business day.": "我们通常会在一个工作日内回复。",
  "Your account and data are safe. Buy a new subscription to restore business features.": "您的帐户和数据是安全的。购买新的订阅以恢复业务功能。",
  "Your email": "您的电子邮件",
  "Your request has been sent to our support team.": "您的请求已发送给我们的支持团队。",
  "Your session has expired. Sign in again.": "您的会话已过期。再次登录。",
  "categories": "类别",
  "the specified address": "指定地址",
  "{{amount}} remaining": "剩余{{amount}}",
  "{{percent}}% of plan": "计划的 {{percent}}%",
  "‹ Back": "‹ 返回",
  "Account \"{{name}}\" will be deleted.": "帐户“{{name}}”将被删除。",
  "Category \"{{name}}\" will be deleted.": "类别“{{name}}”将被删除。",
  "Account deleted": "账户已删除",
  "Accounts, categories, budgets, transactions, transfers, settings, and access tokens will be deleted.": "账户、类别、预算、交易、转账、设置和访问令牌将被删除。",
  "Apple did not return credentials required for account deletion.": "Apple 未返回删除账户所需的凭据。",
  "Apple Sign-In is not available on this device.": "此设备无法使用 Apple 登录。",
  "Apple Sign-In was cancelled.": "Apple 登录已取消。",
  "Choose a verification method. Sign-in will open after you press the final delete button.": "请选择验证方式。按下最终删除按钮后将打开登录界面。",
  "Confirm your identity": "确认您的身份",
  "Continue with Apple and delete account": "使用 Apple 继续并删除账户",
  "Continue with Google and delete account": "使用 Google 继续并删除账户",
  "Danger zone": "危险区域",
  "Delete MoneyDrive account": "删除 MoneyDrive 账户",
  "Delete MoneyDrive account permanently": "永久删除 MoneyDrive 账户",
  "Deleting account...": "正在删除账户...",
  "Deleting your account permanently removes your profile and financial data. This action cannot be undone.": "删除账户将永久移除您的个人资料和财务数据。此操作无法撤销。",
  "Deleting MoneyDrive does not cancel App Store billing. Cancel the subscription in Apple settings if you no longer want it.": "删除 MoneyDrive 不会取消 App Store 扣费。如不再需要，请在 Apple 设置中取消订阅。",
  "Google Sign-In": "使用 Google 登录",
  "Manage Apple subscription": "管理 Apple 订阅",
  "Sign in with Apple": "使用 Apple 登录",
  "Type DELETE to confirm": "输入 DELETE 以确认",
  "Unable to open subscription management.": "无法打开订阅管理。",
} as const;

export default zhCN;
