const zhTW = {
  "+{{amount}} above plan 🚀": "超出預算 {{amount}} 🚀",
  "30 days": "30天",
  "A subcategory cannot contain nested subcategories.": "子類別不能包含巢狀子類別。",
  "Access denied.": "拒絕訪問。",
  "Access until: {{date}}": "訪問截止時間：{{date}}",
  "Account": "帳戶",
  "Account settings": "帳戶設定",
  "Account unavailable.": "帳戶不可用。",
  "Account: {{name}}": "帳號：{{name}}",
  "Accounts": "帳戶",
  "Across all accounts": "跨所有帳戶",
  "Actual": "實際",
  "Actual expense": "實際費用",
  "Actual income": "實際收入",
  "Add": "新增",
  "Add account": "新增帳戶",
  "Add budget": "新增預算",
  "Add category": "新增類別",
  "Add details": "新增詳細資料",
  "Add subcategory": "新增子類別",
  "Add to budget": "新增至預算",
  "Add transaction": "新增交易",
  "Add your first expense": "新增您的第一筆費用",
  "Adding...": "新增...",
  "All accounts": "所有帳戶",
  "All categories": "所有類別",
  "All recorded income categories": "所有記錄的收入類別",
  "All steps completed": "所有步驟已完成",
  "All time": "所有時間",
  "All types": "所有類型",
  "Amount": "金額",
  "Analytics period": "分析期間",
  "Another store purchase is already in progress.": "另一家商店的採購已經在進行中。",
  "Apple did not return an identity token.": "Apple 沒有回傳身分令牌。",
  "App Store saved {{actualProductId}} instead of {{requestedProductId}}. Check the current plan in App Store subscription settings.": "App Store 儲存的是 {{actualProductId}} 而不是 {{requestedProductId}}。請在 App Store 訂閱設定中檢查目前的訂閱方案。",
  "Auto-renew off": "自動續訂關閉",
  "Auto-renewal is off. Premium access remains available through the date above.": "自動續訂已關閉。在上述日期之前，高級存取權限仍然可用。",
  "Available plans": "可選訂閱方案",
  "Back": "返回",
  "Back to sign in": "返回登入",
  "Balance": "餘額",
  "Balance update timed out. Check that the backend API is available.": "餘額更新逾時。檢查後端API是否可用。",
  "Base currency": "基礎貨幣",
  "Budget": "預算",
  "Budget category": "預算類別",
  "Budget changes and category editing will be added after the backend API is extended.": "後端API擴充後將增加預算變更和類別編輯功能。",
  "Budget details": "預算詳情",
  "Budget not found.": "未找到預算。",
  "Budget progress": "預算進度",
  "Budgets": "預算",
  "C": "C",
  "Cancel": "取消",
  "Categories": "類別",
  "Category": "類別",
  "Category disabled": "類別已停用",
  "Category enabled": "已啟用類別",
  "Category not found in the budget.": "預算中未找到類別。",
  "Category unavailable.": "類別不可用。",
  "Category \"{{name}}\" will become a group. It can no longer be selected in new transactions and budgets. Existing records will remain unchanged.": "類別“{{name}}”將成為一個群組。不能再在新的交易和預算中選擇它。現有記錄將保持不變。",
  "Category will become a group": "類別將成為一個群組",
  "Change balance": "更改餘額",
  "Change password": "更改密碼",
  "Check your email": "檢查您的電子郵件",
  "Checking authentication...": "正在檢查身份驗證...",
  "Choose an App Store or Google Play product below.": "在下方選擇一個 App Store 或 Google Play 產品。",
  "Comment": "評論",
  "Complete all password fields.": "填寫所有密碼欄位。",
  "Confirm new password": "確認新密碼",
  "Confirm password": "確認密碼",
  "Contact support": "聯絡支援團隊",
  "Continue": "繼續",
  "Create": "建立",
  "Create account": "建立帳戶",
  "Creating...": "正在建立...",
  "Currency": "貨幣",
  "Current password": "當前密碼",
  "Current plan": "目前的訂閱方案",
  "Custom": "自訂",
  "DONE": "完畢",
  "Dashboard": "儀表板",
  "Date": "日期",
  "Date YYYY-MM-DD": "日期 YYYY-MM-DD",
  "Delete": "刪除",
  "Delete account?": "刪除帳戶？",
  "Delete category": "刪除類別",
  "Delete category?": "刪除類別？",
  "Delete transaction": "刪除交易",
  "Delete transaction?": "刪除交易？",
  "Deleting...": "正在刪除...",
  "Description": "描述",
  "Disabled": "停用",
  "Edit": "編輯",
  "Edit account": "編輯帳戶",
  "Edit transaction": "編輯交易",
  "Editing": "編輯",
  "Email": "電子郵件",
  "Email resent. Retry in {{seconds}} seconds.": "電子郵件已重新傳送。在 {{seconds}} 秒後重試。",
  "Email sent. You can retry in about {{seconds}} seconds.": "電子郵件已發送。您可以在大約 {{seconds}} 秒後重試。",
  "Email verification": "信箱驗證",
  "Email verified. You can now sign in.": "電子郵件已驗證。您現在可以登入。",
  "Email was not sent. Try again in {{seconds}} seconds.": "電子郵件未發送。 {{seconds}} 秒後重試。",
  "End date": "結束日期",
  "Enter a category name.": "輸入類別名稱。",
  "Enter a date.": "輸入日期。",
  "Enter a message.": "輸入訊息。",
  "Enter a new password.": "輸入新密碼。",
  "Enter a subject.": "輸入主題。",
  "Enter a valid amount.": "輸入有效金額。",
  "Enter a valid balance.": "輸入有效餘額。",
  "Enter a valid email address.": "輸入有效的電子郵件地址。",
  "Enter a valid planned amount greater than 0.": "輸入大於 0 的有效計畫金額。",
  "Enter an account name.": "輸入帳戶名稱。",
  "Enter an amount greater than zero.": "輸入大於零的金額。",
  "Enter your email": "輸入您的電子郵件",
  "Enter your email, name, and password.": "輸入您的電子郵件、姓名和密碼。",
  "Enter your email.": "輸入您的電子郵件。",
  "Enter your name": "輸入你的名字",
  "Expense": "支出",
  "Expense categories": "支出類別",
  "Expense categories are not available yet.": "費用類別尚不可用。",
  "Expense not submitted: complete the required fields.": "未提交費用：填寫必填欄位。",
  "Expenses": "支出",
  "Expenses and income": "費用和收入",
  "Expenses this period": "本期費用",
  "Fill password": "填寫密碼",
  "Forgot password?": "忘記密碼？",
  "Free": "免費",
  "From {{date}}": "來自{{date}}",
  "Go to sign in": "前往登入",
  "Goal reached! 🎉": "目標達到了！ 🎉",
  "Google Sign-In is not configured for this build.": "未為此版本配置 Google 登入。",
  "Google did not return an ID token.": "Google 沒有回傳 ID 令牌。",
  "Group": "團體",
  "Hide": "隱藏",
  "Hide form": "隱藏表格",
  "Hide password": "隱藏密碼",
  "Home": "首頁",
  "I have a token": "我有一個令牌",
  "Icon": "圖示",
  "If the account exists, an email has been sent.": "如果該帳戶存在，則會傳送電子郵件。",
  "If the account exists, an email has been sent. Retry in {{seconds}} seconds.": "如果該帳戶存在，則會傳送電子郵件。在 {{seconds}} 秒後重試。",
  "If the email contains a production link, paste the token manually for local testing.": "如果電子郵件包含生產鏈接，請手動貼上令牌以進行本地測試。",
  "Income": "收入",
  "Income categories": "收入類別",
  "Income categories are not available yet.": "收入類別尚不可用。",
  "Income this period": "本期收入",
  "Initial setup": "初始設定",
  "Interface language": "介面語言",
  "Invalid accounts response format.": "帳戶回應格式無效。",
  "Invalid budget response format.": "預算回覆格式無效。",
  "Keep an eye on all of your balances.": "密切注意您的所有餘額。",
  "Language and base currency": "語言和基礎貨幣",
  "LiqPay subscription can be cancelled only in the web version of the app.": "LiqPay 訂閱只能在應用程式的網頁版中取消。",
  "Loading accounts...": "正在載入帳戶...",
  "Loading budget...": "正在載入預算...",
  "Loading budgets...": "正在載入預算...",
  "Loading categories...": "正在載入類別...",
  "Loading dashboard...": "正在載入儀表板...",
  "Loading icons...": "正在載入圖示...",
  "Loading onboarding...": "正在載入初始設定...",
  "Loading settings...": "正在載入設定...",
  "Loading store products...": "正在載入商店產品...",
  "Loading subscription status...": "正在載入訂閱狀態...",
  "Loading...": "載入中...",
  "Log in": "登入",
  "Login with Google": "使用 Google 登入",
  "Logout": "登出",
  "Manage on web": "在網路上管理",
  "Manage premium access": "管理進階存取權限",
  "Manage subscription": "管理訂閱",
  "Maximum category depth is 2 levels": "最大類別深度為 2 級",
  "Maximum category depth is 2 levels.": "最大類別深度為 2 級。",
  "Message": "訊息",
  "Missing Android subscription offer token for selected product.": "缺少所選產品的 Android 訂閱優惠令牌。",
  "Missing account ID.": "缺少帳戶 ID。",
  "Missing budgetId.": "缺少預算 ID。",
  "Missing reset token.": "缺少重置令牌。",
  "MoneyDrive.me": "MoneyDrive.me",
  "Month": "月",
  "More": "更多的",
  "More service sections": "更多服務板塊",
  "Most frequent": "最常見的",
  "Name": "名稱",
  "New account": "新帳戶",
  "New balance": "新餘額",
  "New category": "新類別",
  "New email awaiting verification: {{email}}": "新電子郵件等待驗證：{{email}}",
  "New password": "新密碼",
  "New planned amount": "新計畫金額",
  "No App Store Sandbox account is connected on this device. Add a sandbox tester in Settings > App Store > Sandbox Account.": "此裝置上沒有連接 App Store Sandbox 帳戶。在「設定」>「App Store」>「沙盒帳戶」中新增沙盒測試人員。",
  "No account": "沒有帳戶",
  "No account data.": "沒有帳戶資料。",
  "No accounts.": "沒有帳戶。",
  "No active purchases found.": "未發現活躍購買。",
  "No active store source": "沒有活躍的商店來源",
  "No budget has been created for the selected month.": "尚未為所選月份建立預算。",
  "No budgets for the selected period.": "所選期間沒有預算。",
  "No budgets found yet.": "尚未找到預算。",
  "No categories available to add.": "沒有可新增的類別。",
  "No categories found for the selected type.": "未找到所選類型的類別。",
  "No categories found.": "未找到類別。",
  "No categories.": "沒有類別。",
  "No data for the selected period.": "所選期間沒有資料。",
  "No data.": "沒有資料。",
  "No external management action is available.": "沒有可用的外部管理措施。",
  "No period selected": "未選擇期間",
  "No transaction data.": "無交易資料。",
  "No transactions yet.": "還沒有交易。",
  "Not enough data to add the category.": "資料不足，無法新增類別。",
  "Not set": "未設定",
  "Note": "筆記",
  "Open": "打開",
  "Open App Store account settings and choose Subscriptions.": "開啟 App Store 帳戶設定並選擇訂閱。",
  "Open the subscription provider account settings to manage this plan.": "開啟訂閱提供者的帳戶設定以管理此訂閱方案。",
  "Overspent by {{amount}}": "{{amount}} 超支",
  "Parent: {{name}}": "父級：{{name}}",
  "Password": "密碼",
  "Password changed.": "密碼已更改。",
  "Password recovery": "密碼恢復",
  "Password updated. You can now sign in.": "密碼已更新。您現在可以登入。",
  "Passwords do not match.": "密碼不符。",
  "Paste the verification token.": "貼上驗證令牌。",
  "Period: {{period}}": "期間：{{period}}",
  "Plan ({{currency}})": "計畫（{{currency}}）",
  "Plan / actual / remaining by category": "計畫/實際/剩餘（按類別）",
  "Plan {{plan}} · Actual {{actual}}": "計畫 {{plan}} · 實際 {{actual}}",
  "Plans and billing": "訂閱方案與帳單",
  "Planned amount ({{currency}})": "計畫金額（{{currency}}）",
  "Planned expense": "預計支出",
  "Planned income": "預計收入",
  "Popular categories": "熱門類別",
  "Premium": "Premium",
  "Premium is active.": "高級版已啟用。",
  "Premium is active. The plan change will take effect on the next App Store renewal.": "Premium 已啟用。訂閱方案變更將於下次 App Store 續約時生效。",
  "Processing...": "處理中...",
  "Product temporarily unavailable.": "產品暫時無法使用。",
  "Product: {{product}}": "產品：{{product}}",
  "Products for {{platform}}": "適用於 {{platform}} 的產品",
  "Profile": "個人資料",
  "Profile and security": "個人資料和安全性",
  "Profile saved.": "個人資料已儲存。",
  "Profile, language, and security": "個人資料、語言和安全性",
  "Purchase not confirmed. Try again.": "購買未確認。再試一次。",
  "Recent transactions": "最近交易",
  "Registration": "登記",
  "Remaining": "其餘的",
  "Renewal canceled": "續訂取消",
  "Request failed (HTTP {{status}}).": "請求失敗（HTTP {{status}}）。",
  "Resend email": "重新發送電子郵件",
  "Restore purchases": "恢復購買",
  "Restored purchases: {{count}}.": "恢復購買：{{count}}。",
  "Restoring...": "正在恢復...",
  "Retry": "重試",
  "Root level": "根級",
  "Runtime category tree": "運行時類別樹",
  "Save": "儲存",
  "Save and continue": "儲存並繼續",
  "Save balance": "儲存餘額",
  "Save password": "儲存密碼",
  "Saving...": "儲存...",
  "Segments show amounts by category.": "細分市場按類別顯示金額。",
  "Select": "選擇",
  "Select a base currency.": "選擇基礎貨幣。",
  "Select a category": "選擇一個類別",
  "Select a category and an account.": "選擇類別和帳戶。",
  "Select a category.": "選擇一個類別。",
  "Select a currency": "選擇貨幣",
  "Select a date": "選擇日期",
  "Select a language": "選擇語言",
  "Select a subcategory. A parent category cannot be added.": "選擇一個子類別。無法新增父類別。",
  "Select account": "選擇帳戶",
  "Select an account.": "選擇一個帳戶。",
  "Select an icon from the shared catalog": "從共用目錄中選擇圖示",
  "Select an interface language.": "選擇介面語言。",
  "Select the interface language and analytics currency.": "選擇介面語言和分析貨幣。",
  "Send a request": "發送請求",
  "Send email": "傳送電子郵件",
  "Send request": "送出請求",
  "Sending...": "正在發送...",
  "Show": "顯示",
  "Show password": "顯示密碼",
  "Settings": "設定",
  "Sign in": "登入",
  "Signing in with Google...": "正在使用 Google 登入...",
  "Signing in...": "正在登入...",
  "Some store products are not available yet: {{products}}.": "部分商店產品尚未上市：{{products}}。",
  "Spending across all accounts": "所有帳戶的支出",
  "Start date": "開始日期",
  "Step {{current}} of 2: {{screen}}": "步驟 2 中的步驟 {{current}}：{{screen}}",
  "Store products are available only on iOS and Android.": "商店產品僅適用於 iOS 和 Android。",
  "Store products are not available yet. Please check App Store or Google Play product setup.": "商店產品尚未上市。請檢查 App Store 或 Google Play 產品設定。",
  "Store purchases are available only on iOS and Android.": "商店購買僅適用於 iOS 和 Android。",
  "Store purchases require iOS or Android": "商店購買需要 iOS 或 Android",
  "Store transaction is missing orderId.": "商店交易缺少 orderId。",
  "Store transaction is missing originalTransactionId.": "商店交易缺少originalTransactionId。",
  "Store transaction is missing packageName.": "商店交易缺少 packageName。",
  "Store transaction is missing purchaseToken.": "商店交易缺少purchaseToken。",
  "Store transaction is missing signed payload.": "商店交易缺少簽署的有效負載。",
  "Store transaction is missing transactionId.": "商店交易缺少 transactionId。",
  "Subcategories": "子類別",
  "Subject": "主旨",
  "Subscribe": "訂閱",
  "Subscription": "訂閱",
  "Subscription management": "訂閱管理",
  "Subscriptions": "訂閱",
  "Support": "支援",
  "Tap the icon to select": "點擊圖示進行選擇",
  "Telegram username": "電報用戶名",
  "The account will be deleted.": "該帳戶將被刪除。",
  "The base currency cannot be changed because budgets or transactions already exist.": "由於預算或交易已存在，因此無法更改基礎貨幣。",
  "The budget category list for this month is empty.": "本月的預算類別清單為空。",
  "The category will be removed from this month's budget.": "該類別將從本月的預算中刪除。",
  "The payment is overdue. Premium access remains available through the grace-period date above.": "付款已逾期。Premium 權益可使用至上述寬限期結束日期。",
  "The purchase was not confirmed by the store. Try again.": "該購買未經商店確認。再試一次。",
  "The server did not respond in time. Try again.": "伺服器沒有及時響應。再試一次。",
  "The transaction will be permanently deleted.": "該交易將永久刪除。",
  "The verified purchase is not active.": "已驗證的購買未啟動。",
  "This account has no password. Password setup is handled separately.": "該帳戶沒有密碼。密碼設定單獨處理。",
  "This purchase has already been received. Tap Restore purchases to restore the subscription.": "此購買已收到。點擊恢復購買以恢復訂閱。",
  "This purchase is linked to another MoneyDrive account. Sign in to the linked account or use a different App Store Sandbox account.": "此購買連結到另一個 MoneyDrive 帳戶。登入連結的帳戶或使用其他 App Store Sandbox 帳戶。",
  "This purchase period has already expired.": "此購買期限已過。",
  "This purchase period has expired. Select a current subscription.": "本次購買期限已過。選擇當前訂閱。",
  "This takes less than a minute.": "這需要不到一分鐘的時間。",
  "To goal: {{amount}}": "目標：{{amount}}",
  "To renew with LiqPay, open the web version and complete a new checkout.": "若要使用 LiqPay 續訂，請開啟網頁版本並完成新的結帳。",
  "Top categories by spending ({{currency}})": "依支出排名最高的類別 ({{currency}})",
  "Total": "總計",
  "Total balance": "總餘額",
  "Transactions": "交易",
  "Transfer": "轉帳",
  "Type": "類型",
  "Type: {{type}}": "類型：{{type}}",
  "Unable to add the budget category (HTTP {{status}}).": "無法新增預算類別 (HTTP {{status}})。",
  "Unable to change password.": "無法更改密碼。",
  "Unable to connect to the server.": "無法連接到伺服器。",
  "Unable to create budget (HTTP {{status}}).": "無法建立預算 (HTTP {{status}})。",
  "Unable to create the account.": "無法建立帳戶。",
  "Unable to create the category (HTTP {{status}}).": "無法建立類別 (HTTP {{status}})。",
  "Unable to delete the category (HTTP {{status}}).": "無法刪除類別 (HTTP {{status}})。",
  "Unable to delete the transaction.": "無法刪除交易。",
  "Unable to load accounts (HTTP {{status}}).": "無法載入帳戶 (HTTP {{status}})。",
  "Unable to load accounts.": "無法載入帳戶。",
  "Unable to load budget (HTTP {{status}}).": "無法載入預算 (HTTP {{status}})。",
  "Unable to load budgets (HTTP {{status}}).": "無法載入預算 (HTTP {{status}})。",
  "Unable to load categories.": "無法載入類別。",
  "Unable to load category icons (HTTP {{status}}).": "無法載入類別圖示 (HTTP {{status}})。",
  "Unable to load category icons.": "無法載入類別圖示。",
  "Unable to load dashboard (HTTP {{status}}).": "無法載入儀表板 (HTTP {{status}})。",
  "Unable to load frequent categories.": "無法載入常用類別。",
  "Unable to load settings.": "無法載入設定。",
  "Unable to load subscription products.": "無法載入訂閱產品。",
  "Unable to load subscription status.": "無法載入訂閱狀態。",
  "Unable to load transactions.": "無法載入交易。",
  "Unable to open onboarding.": "無法開啟初始設定。",
  "Unable to open the account.": "無法開設帳戶。",
  "Unable to open the category for editing.": "無法開啟類別進行編輯。",
  "Unable to open the category.": "無法打開類別。",
  "Unable to open the transaction.": "無法開啟交易。",
  "Unable to prepare the expense form.": "無法準備費用表格。",
  "Unable to remove the budget category (HTTP {{status}}).": "無法刪除預算類別 (HTTP {{status}})。",
  "Unable to resend the email.": "無法重新傳送電子郵件。",
  "Unable to save the profile.": "無法儲存設定檔。",
  "Unable to save the transaction.": "無法儲存交易。",
  "Unable to send request.": "無法發送請求。",
  "Unable to update balance.": "無法更新餘額。",
  "Unable to update the account.": "無法更新帳戶。",
  "Unable to update the budget category (HTTP {{status}}).": "無法更新預算類別 (HTTP {{status}})。",
  "Unable to update the category (HTTP {{status}}).": "無法更新類別 (HTTP {{status}})。",
  "Uncategorized": "未分類",
  "Until {{date}}": "直到{{date}}",
  "Untitled": "無題",
  "Unverified": "未驗證",
  "Update": "更新",
  "Verification": "確認",
  "Verification token": "驗證令牌",
  "Verified": "已驗證",
  "Verify email": "驗證電子郵件",
  "Verify with token": "使用令牌驗證",
  "Verifying email...": "正在驗證電子郵件...",
  "View all": "查看全部",
  "View budgets": "查看預算",
  "We sent a verification email to {{email}}.": "我們向 {{email}} 發送了一封驗證電子郵件。",
  "We usually respond within one business day.": "我們通常會在一個工作天內回覆。",
  "Your account and data are safe. Buy a new subscription to restore business features.": "您的帳戶和資料是安全的。購買新的訂閱以恢復業務功能。",
  "Your email": "您的電子郵件",
  "Your request has been sent to our support team.": "您的請求已發送給我們的支援團隊。",
  "Your session has expired. Sign in again.": "您的會話已過期。再次登入。",
  "categories": "類別",
  "the specified address": "指定地址",
  "{{amount}} remaining": "剩餘{{amount}}",
  "{{percent}}% of plan": "計畫的 {{percent}}%",
  "‹ Back": "‹ 返回",
  "Account \"{{name}}\" will be deleted.": "帳戶“{{name}}”將被刪除。",
  "Category \"{{name}}\" will be deleted.": "類別“{{name}}”將被刪除。",
  "Account deleted": "帳戶已刪除",
  "Accounts, categories, budgets, transactions, transfers, settings, and access tokens will be deleted.": "帳戶、類別、預算、交易、轉帳、設定和存取權杖將被刪除。",
  "Apple did not return credentials required for account deletion.": "Apple 未傳回刪除帳戶所需的憑證。",
  "Apple Sign-In is not available on this device.": "此裝置無法使用 Apple 登入。",
  "Apple Sign-In was cancelled.": "Apple 登入已取消。",
  "Choose a verification method. Sign-in will open after you press the final delete button.": "請選擇驗證方式。按下最終刪除按鈕後將開啟登入畫面。",
  "Confirm your identity": "確認您的身分",
  "Continue with Apple and delete account": "使用 Apple 繼續並刪除帳戶",
  "Continue with Google and delete account": "使用 Google 繼續並刪除帳戶",
  "Danger zone": "危險區域",
  "Delete MoneyDrive account": "刪除 MoneyDrive 帳戶",
  "Delete MoneyDrive account permanently": "永久刪除 MoneyDrive 帳戶",
  "Deleting account...": "正在刪除帳戶...",
  "Deleting your account permanently removes your profile and financial data. This action cannot be undone.": "刪除帳戶將永久移除您的個人資料和財務資料。此操作無法復原。",
  "Deleting MoneyDrive does not cancel App Store billing. Cancel the subscription in Apple settings if you no longer want it.": "刪除 MoneyDrive 不會取消 App Store 計費。如不再需要，請在 Apple 設定中取消訂閱。",
  "Google Sign-In": "使用 Google 登入",
  "Manage Apple subscription": "管理 Apple 訂閱",
  "Sign in with Apple": "使用 Apple 登入",
  "Type DELETE to confirm": "輸入 DELETE 以確認",
  "Unable to delete the account.": "無法刪除帳戶。",
  "Unable to open subscription management.": "無法開啟訂閱管理。",
  Legal: "法律資訊",
  "Privacy Policy": "隱私權政策",
  "Unable to open the Privacy Policy.": "無法開啟隱私權政策。",
} as const;

export default zhTW;
